import assert from'node:assert/strict';
import{readFile}from'node:fs/promises';

const html=await readFile(new URL('../dist/asset-studio/index.html',import.meta.url),'utf8');
const app=await readFile(new URL('../dist/asset-studio/app.js',import.meta.url),'utf8');
const css=await readFile(new URL('../dist/asset-studio/styles.css',import.meta.url),'utf8');

assert.ok(html.includes('PNG, JPG, WebP ou SVG · mantém tamanho e fundo'));
assert.ok(html.includes('accept="image/*,.svg,image/svg+xml"'),'seletor do favicon não aceita SVG explicitamente');
assert.ok(!html.includes('id="removeLightBg"'),'controle de remoção de fundo ainda aparece');
assert.ok(!html.includes('16 × 16'),'instrução de redimensionamento ainda aparece');
assert.ok(app.includes('canvas.width = width')&&app.includes('canvas.height = height'),'favicon não preserva as dimensões originais');
assert.ok(app.includes("if (blob.type === 'image/png')")&&app.includes('return { blob, width, height }'),'PNG original não é preservado sem recodificação');
assert.ok(app.includes("canvas.toBlob(result => result ? resolve(result)")&&app.includes("'image/png'"),'favicon não é convertido para PNG');
assert.ok(app.includes("blob.type === 'image/svg+xml'")&&app.includes("/\\.svg$/i.test(blob.name || '')"),'arquivo SVG não usa decodificação compatível');
assert.ok(app.includes("getData('image/svg+xml')")&&app.includes("new Blob([text], { type: 'image/svg+xml' })"),'SVG colado como texto não é reconhecido');
assert.ok(app.includes("image.onerror = () => reject(new Error('Não foi possível interpretar o SVG do favicon.'))"),'falha de leitura do SVG não é informada');
assert.ok(app.includes("async function setFaviconBlob")&&app.includes("$('#faviconMessage').textContent = 'Validando favicon…'"),'favicon SVG não é validado no momento da entrada');
assert.ok(!app.includes('removeLightBackground'),'remoção de fundo ainda está ativa');
for(const group of['operation','analysis','personal','curation','creation','products'])assert.ok(html.includes(`data-sidebar-group="${group}"`),`grupo lateral ${group} ausente`);
const personal=html.match(/data-sidebar-group="personal"[\s\S]*?<\/div>\s*<\/div>/)?.[0]||'';
assert.ok(personal.includes('Meu Tempo')&&!personal.includes('Observabilidade decisória'),'grupo pessoal deve conter Meu Tempo no Asset Studio');
const analysis=html.match(/data-sidebar-group="analysis"[\s\S]*?<\/div>\s*<\/div>/)?.[0]||'';
assert.ok(analysis.includes('Observabilidade decisória')&&analysis.includes('/?view=cpa')&&analysis.includes('/?view=accounts'),'grupo de análises incompleto no Asset Studio');
const products=html.match(/data-sidebar-group="products"[\s\S]*?<\/div>\s*<\/div>/)?.[0]||'';
assert.ok(products.includes('Produtos testados')&&products.includes('Diário do produto'),'grupo Produtos incompleto no Asset Studio');
assert.ok(html.includes('/?view=macro')&&html.includes('Controle Macro'),'Controle Macro ausente no grupo Operação do Asset Studio');
assert.ok(html.includes('painel-sidebar-grupo-aberto-v1'),'menu lateral não compartilha o acordeão do painel');
assert.ok(html.includes('class="active" href="/asset-studio/"'),'Asset Studio não fica ativo no próprio menu');
assert.ok(css.includes('color-scheme: dark')&&css.includes('grid-template-columns: 224px minmax(0, 1fr)'),'tema escuro ou largura do menu lateral ausente');
console.log('asset studio ok');
