import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';

const html=await readFile(new URL('../dist/index.html',import.meta.url),'utf8');
const databaseModule=await readFile(new URL('../dist/database.js',import.meta.url),'utf8');
const timeViewModule=await readFile(new URL('../dist/meu-tempo/meu-tempo-view.mjs',import.meta.url),'utf8');
const timeStorageModule=await readFile(new URL('../dist/meu-tempo/meu-tempo-storage.mjs',import.meta.url),'utf8');
const timeCss=await readFile(new URL('../dist/meu-tempo/meu-tempo.css',import.meta.url),'utf8');
const copyFichaView=await readFile(new URL('../dist/copy-ficha/copy-ficha-view.mjs',import.meta.url),'utf8');
const copyFichaDomain=await readFile(new URL('../dist/copy-ficha/copy-ficha-domain.mjs',import.meta.url),'utf8');
const copyFichaCss=await readFile(new URL('../dist/copy-ficha/copy-ficha.css',import.meta.url),'utf8');
assert.ok(html.includes('data:image/png;base64,'),'favicon ausente');
assert.ok(html.includes('Carregar base JSON'),'controle de base ausente');
assert.ok(html.includes('Registrar venda'),'registro provisório de venda ausente');
assert.ok(html.includes('flowtracking-copy-guide.png'),'referência visual do FlowTracking ausente');
assert.ok(html.includes('width:50%'),'referência do FlowTracking não está em cinquenta por cento');
assert.ok(html.includes('Produtos testados'),'página de produtos testados ausente');
assert.ok(html.includes('id="accountReportNav">Mapa por conta</button>'),'menu do relatório por conta ausente');
assert.ok(html.includes('id="accountReportView"'),'tela do relatório por conta ausente');
assert.ok(html.includes('id="timeNav">Meu Tempo</button>'),'menu Meu Tempo ausente');
assert.ok(html.includes('id="presellNav">Gerador de Pre-Sell</button>'),'menu Gerador de Pre-Sell ausente');
assert.ok(html.includes('id="copyFichaNav">Copy e Ficha</button>'),'menu Copy e Ficha ausente');
assert.ok(html.includes('id="copyFichaView"'),'tela Copy e Ficha ausente');
assert.ok(html.includes("import('./copy-ficha/copy-ficha-view.mjs?v=2')"),'módulo Copy e Ficha não é carregado sob demanda ou usa versão antiga');
assert.ok(copyFichaView.includes('Gerar copy e ficha')&&copyFichaView.includes('URL de afiliação (sempre separada)'),'fluxo Copy e Ficha não foi copiado para dist');
assert.ok(copyFichaView.includes("applyDetected(root,'copyProduct',result.productCandidate)")&&copyFichaView.includes("state.packages=result.packages;renderPackages(root)"),'análise não preenche automaticamente os dados e pacotes confirmados');
assert.ok(copyFichaView.includes('generationBlockers(data)')&&copyFichaView.includes('error.blockers=blockers')&&copyFichaView.includes('renderWarnings(root,blockers||[error.message],{blocked:Boolean(blockers)})'),'Copy e Ficha permite gerar com confirmações pendentes ou não mostra os bloqueios individualmente');
assert.ok(copyFichaView.includes("invalidateGeneratedOutputs(root,'Dados alterados. Revise as confirmações e gere novamente.')")&&!copyFichaView.includes("applyDetected(root,'copyUrgency'")&&!copyFichaView.includes("applyDetected(root,'copyScarcity'"),'edições mantêm saídas antigas ou urgência e escassez são aceitas sem validação');
assert.ok(copyFichaView.includes('id="copyGuaranteeStatus"')&&copyFichaView.includes('Não usar / não confirmada'),'interface não permite resolver explicitamente garantias, urgência e escassez ausentes');
assert.ok(copyFichaDomain.includes('export function buildFicha')&&copyFichaDomain.includes('mustContain'),'contrato JSON da ficha não foi copiado para dist');
assert.ok(copyFichaDomain.includes('export function generationBlockers'),'validação de bloqueios não foi copiada para dist');
assert.ok(copyFichaCss.includes('.copy-ficha-shell'),'CSS da tela Copy e Ficha não foi copiado para dist');
const copyFichaPendingCss=await readFile(new URL('../dist/copy-ficha/copy-ficha-pending.css',import.meta.url),'utf8');
assert.ok(html.includes('copy-ficha/copy-ficha-pending.css?v=1')&&copyFichaPendingCss.includes('.copy-ficha-warning-count')&&copyFichaPendingCss.includes('.copy-ficha-warning-list li::marker'),'pendências de Copy e Ficha não são exibidas como itens numerados com contagem destacada');
assert.ok(html.includes('href="asset-studio/">Asset Studio</a>'),'menu Asset Studio ausente');
assert.ok(html.includes('id="timeView"'),'tela Meu Tempo ausente');
assert.ok(html.includes('data-sidebar-group="operation"'),'grupo expansível Operação ausente');
assert.ok(html.includes('data-sidebar-group="curation"'),'grupo expansível Curadoria ausente');
assert.ok(html.includes('data-sidebar-group="products"'),'grupo expansível Produtos ausente');
assert.ok(html.includes("setSidebarGroup(isOpen?'':toggle.dataset.sidebarToggle)"),'acordeão lateral não fecha os demais grupos ao abrir um item');
assert.ok(html.includes("localStorage.setItem(SIDEBAR_GROUP_KEY,openName)"),'estado do menu expansível não é preservado');
assert.ok(html.includes("import('./meu-tempo/meu-tempo-view.mjs?v=12')"),'Meu Tempo não é carregado pelo módulo dedicado versionado');
assert.ok(html.includes('meu-tempo/meu-tempo.css?v=4'),'CSS do Meu Tempo não está versionado para invalidar cache');
assert.ok(timeViewModule.includes('painel-meu-tempo')||timeViewModule.includes("from'./meu-tempo-storage.mjs'"),'módulo Meu Tempo não foi copiado para dist');
assert.ok(timeViewModule.includes("input[data-manual],input[data-value]"),'campos manuais do Meu Tempo não registram pelo Enter');
assert.ok(timeViewModule.includes("input.dataset.submitting==='true'"),'Enter manual do Meu Tempo não impede registro duplicado');
const dailyViewBlock=timeViewModule.match(/function dailyView\(\)\{([\s\S]*?)\n\}/)?.[1]||'';
assert.ok(dailyViewBlock.includes('shell(')&&dailyViewBlock.includes('bindDaily(day)'),'eventos do Diário do Meu Tempo não são conectados após a renderização');
assert.ok(!dailyViewBlock.includes('return shell('),'Diário do Meu Tempo encerra antes de conectar seus eventos');
assert.ok(timeViewModule.includes('data-productive'),'marcação de produtividade não aparece no Diário');
assert.ok(timeViewModule.includes("items=data.items.filter(x=>x.active&&x.showInCharts&&x.id!=='item-dormindo')"),'Dormindo ainda aparece no seletor Item para evolução');
assert.ok(timeViewModule.includes("if(entry.itemId!=='item-dormindo'){\n   categoryTotals.set"),'Dormindo ainda entra nos gráficos por categoria ou por atividade');
assert.ok(timeViewModule.includes("dates.map(date=>`<th>${dateLabel(date)}</th>`)"),'datas da comparação do Meu Tempo não usam dia, mês e ano');
assert.ok(timeViewModule.includes("daily.map(x=>({label:dateLabel(x.date)"),'datas das análises do Meu Tempo não usam dia, mês e ano');
assert.ok(timeViewModule.includes('placeholder="dd/mm/aaaa"'),'campos de data do Meu Tempo não exibem o formato brasileiro');
assert.ok(!timeViewModule.includes('type="date"'),'Meu Tempo ainda depende do formato regional do navegador para exibir datas');
assert.ok(timeViewModule.includes('dailyTableScrollTop=tableWrap.scrollTop'),'rolagem do Lançamento rápido não é preservada após atualização');
assert.ok(!timeViewModule.includes('id="lastRecordedTime"'),'campo manual de último horário ainda aparece no Diário');
assert.ok(timeViewModule.includes('Domain.registeredIntervalUntil(daily.totalMinutes,currentMinutes)'),'Até agora não usa o tempo total registrado como base automática');
assert.ok(timeViewModule.includes('<th>Remover manualmente</th>')&&timeViewModule.includes('data-remove="${item.id}"'),'coluna Remover manualmente não aparece no Diário');
assert.ok(timeViewModule.includes('await Storage.removeDuration(selectedDate,itemId,minutes)'),'remoção manual não é aplicada à atividade e data selecionadas');
assert.ok(timeStorageModule.includes("store.index('date_item').getAll([date,itemId])"),'remoção manual não consulta somente os lançamentos da atividade no dia');
assert.ok(timeStorageModule.includes("store.index('itemId').getAll(item.id)"),'produtividade não é reaplicada ao histórico completo da atividade');
assert.ok(timeStorageModule.includes('for(const id of BOOLEAN_ITEM_IDS)')&&timeStorageModule.includes("item.type!=='boolean'"),'itens booleanos existentes não são atualizados com segurança');
assert.ok(timeCss.includes('.time-table .activity{min-width:210px;font-weight:400'),'nome da atividade permanece em negrito no Diário');
assert.ok(timeCss.includes('.time-table th,.time-table td{padding:5px 7px}') && timeCss.includes('.time-table .time-input,.time-table .time-select{padding:5px 7px}'),'linhas e controles do Diário não estão compactos');
assert.ok(timeCss.includes('.time-table{font-size:.77rem}'),'tamanho da fonte da tabela do Diário foi alterado');
assert.ok(timeViewModule.includes("class=\"${item.productive?'time-productive-row':''}\""),'linhas produtivas não são destacadas no Lançamento rápido');
assert.ok(timeViewModule.includes("row.item.productive?'time-productive-row ':''"),'linhas produtivas não são destacadas na comparação do Histórico');
assert.ok(timeViewModule.includes("class=\"${entry.productiveSnapshot?'time-productive-row':''}\""),'lançamentos produtivos não são destacados no Histórico detalhado');
assert.ok(timeCss.includes('.time-table tr.time-productive-row>td,.time-matrix tr.time-productive-row>td{background:rgba(52,211,153,.075)}'),'destaque verde sutil das linhas produtivas não foi definido');
assert.ok(timeViewModule.includes("time-behavior-start")&&timeCss.includes('.time-matrix tr.time-behavior-start>td{border-top:3px solid #4b6686}'),'Histórico não separa atividades de duração dos itens comportamentais');
assert.ok(timeViewModule.includes("item?.id==='item-alcool'")&&timeViewModule.includes("if(numeric===0)return'Não'")&&timeViewModule.includes("if(numeric===1)return'Sim'"),'Bebida alcoólica não é apresentada como Não/Sim no Histórico');
assert.ok(html.includes('<title>Visão geral</title>'),'título inicial do navegador não acompanha a Visão Geral');
assert.ok(html.includes("document.title=PanelViews.definition('cpa').title"),'título do navegador não acompanha as telas do painel');
assert.ok(timeViewModule.includes("setBrowserTitle(`Meu Tempo · ${titles[tab]||'Diário'}`)"),'título do navegador não acompanha as abas do Meu Tempo');
assert.ok(timeViewModule.includes("barChart('Top atividades do dia',topActivities,true,'time-daily-chart')"),'gráfico Top atividades do dia ausente no Diário');
assert.ok(!timeViewModule.includes('<h3>Lançamentos do dia</h3>'),'quadro Lançamentos do dia ainda aparece no Diário');
assert.ok(timeViewModule.includes("item.type==='duration'&&item.showInCharts&&item.id!=='item-dormindo'"),'Top atividades do dia não segue o mesmo recorte das análises');
assert.ok(timeCss.includes('.time-daily-table-wrap{overflow-x:auto;overflow-y:visible;max-height:none}'),'Lançamento rápido ainda possui rolagem vertical interna');
assert.ok(timeCss.includes('.time-daily-summary{display:flex;align-items:end;gap:8px;flex-wrap:nowrap}'),'data e indicadores diários não estão organizados na mesma linha');
assert.ok(html.includes('Matriz de produtos por conta'),'matriz produto por conta ausente');
assert.ok(html.includes('.account-matrix-wrap{overflow:visible;max-height:none}'),'matriz por conta ainda funciona como área de rolagem interna');
assert.ok(html.includes('.account-detail .table-wrap{max-height:none;overflow:visible}'),'campanhas do produto ainda funcionam como área de rolagem interna');
assert.ok(html.includes('body:has(#accountReportView:not(.hidden)){overflow:hidden}.main:has(#accountReportView:not(.hidden)){height:100vh;overflow-y:auto}'),'Mapa por Conta não possui rolagem vertical na área principal');
assert.ok(html.includes('.main:has(#accountReportView:not(.hidden)){overflow-y:scroll;scrollbar-gutter:stable;scrollbar-width:auto;scrollbar-color:#7893b2 #14243a}'),'Mapa por Conta não mantém a barra vertical visível');
assert.ok(html.includes('.main:has(#accountReportView:not(.hidden))::-webkit-scrollbar{width:14px}'),'barra vertical do Mapa por Conta não possui largura visível');
assert.ok(html.includes('id="accountScrollRail" class="account-scroll-rail"'),'indicador vertical persistente do Mapa por Conta ausente');
assert.ok(html.includes('function updateAccountScrollIndicator()'),'sincronização da barra vertical do Mapa por Conta ausente');
assert.ok(html.includes("accountScrollMain.addEventListener('scroll',updateAccountScrollIndicator"),'barra vertical do Mapa por Conta não acompanha a rolagem');
assert.ok(html.includes('body:has(#cpaReportView:not(.hidden)){overflow:hidden}'),'Análise por Faixa de CPA não isola a rolagem na área principal');
assert.ok(html.includes('.main:has(#cpaReportView:not(.hidden)){height:100vh;overflow-y:scroll;scrollbar-gutter:stable'),'Análise por Faixa de CPA não possui rolagem vertical da tela');
assert.ok(html.includes('body:has(#cpaReportView:not(.hidden)) .account-scroll-rail{display:block}'),'Análise por Faixa de CPA não exibe o indicador vertical');
assert.ok(html.includes("reportScrollObserver.observe($('#cpaReportView'))"),'barra vertical não acompanha as mudanças de conteúdo da Análise por Faixa de CPA');
assert.ok(html.includes('.account-kpis{display:flex;flex-wrap:wrap;gap:7px;margin-bottom:10px}'),'indicadores do Mapa por Conta não usam o formato compacto');
assert.ok(html.includes('function accountReportRows()'),'consolidação do relatório por conta ausente');
assert.ok(html.includes("accountReportStatus:'ativa'"),'Mapa por Conta não abre com o filtro Ativas');
assert.ok(html.includes('Quantidade de produtos por faixa de CPA')&&html.includes('id="accountCpaRangeBars"'),'quadro de quantidade de produtos por faixa de CPA ausente');
assert.ok(!html.includes('Distribuição de campanhas'),'quadro antigo de distribuição de campanhas ainda aparece no Mapa por Conta');
assert.ok(html.includes('function accountProductsByCpaRange(rows)')&&html.includes('productKeys:new Set()')&&html.includes('group.productKeys.add(row.productKey)'),'produtos não são contados de forma única por faixa de CPA');
assert.ok(html.includes('Faixas de CPA não exploradas')&&html.includes('id="accountCpaGapHead"')&&html.includes('id="accountCpaGapBody"'),'matriz de faixas de CPA não exploradas ausente');
assert.ok(html.includes('function accountCpaCoverage(rows,ranges)')&&html.includes("state.accountReportProduct==='all'||x.product===state.accountReportProduct"),'cobertura de CPA por produto não respeita o recorte do relatório');
assert.ok(html.includes('class="cpa-missing">Não explora')&&html.includes('class="cpa-explored"'),'estados de faixa explorada e não explorada não estão destacados');
assert.ok(html.includes("title.payoutCurrency==='USD'")&&html.includes('function accountCommissionLabel(product)')&&html.includes("${esc(product.name)} — ${esc(accountCommissionLabel(product))}"),'comissão em dólar não acompanha o nome do produto na matriz de faixas');
assert.ok(html.includes('function derivedContext()'),'contexto derivado reutilizável ausente');
assert.ok(html.includes('dailyByCampaign=new Map()'),'registros diários não são indexados por campanha');
assert.ok(html.includes('cpaRowsByKey:new Map()'),'resultados de CPA não são reutilizados entre filtros');
assert.ok(html.includes('totalsRowsByMode:new Map()'),'linhas da Visão Geral não são reutilizadas na ordenação');
assert.ok(html.includes('context.dailyByCampaign.get(stored.id)||[]'),'CPA ainda percorre o diário completo para cada campanha');
assert.ok(html.includes('context.totalsRowsByMode.get(state.totalsMode)'),'ordenação ainda recalcula as métricas da Visão Geral');
assert.ok(html.includes('derivedCache=null;derivedContext();renderStatus()'),'atualização da base não recalcula os índices derivados imediatamente');
assert.ok(!html.includes('CampaignDatabase.salesAdjustmentMap(state.database).get(stored.id)'),'vendas provisórias ainda são recalculadas para cada campanha');
assert.ok(html.includes('function accountProductIdentity(campaign,catalog)'),'normalização das variações do produto ausente');
assert.ok(html.includes("replace(/\\s+(?:(?:var(?:iação)?|campanha)\\s*)?#?0*\\d{1,3}$/i"),'sufixo numérico de variação não é removido');
assert.ok(html.includes("PanelViews.resolveRoute(location.pathname+location.search)"),'registro central não resolve a rota inicial');
assert.ok(html.includes("const view=PanelViews.definition('accounts')"),'relatório por conta não usa o registro central');
assert.ok(html.includes('href="preparador-MCC/?v=20260919-cpa">Preparador MCC</a>'),'Preparador MCC ausente da seção Operação');
assert.ok(html.includes('id="cpaReportNav">Análise por faixa de CPA</button>'),'menu da análise por faixa de CPA ausente');
assert.ok(html.includes('id="cpaReportView"'),'tela da análise por faixa de CPA ausente');
assert.ok(html.includes('function cpaValidation(c)'),'comparação entre título e CPA desejado ausente');
assert.ok(html.includes('commission:valueOf(m.valor_conversao)??valueOf(m.comissao_recebida)'),'Análise por Faixa de CPA não lê o valor de conversão de D0');
assert.ok(html.includes('P:{value:conversionValue}'),'Diário do Produto não recebe o valor de conversão importado');
assert.ok(html.includes("cpaMode:'history'"),'Análise por Faixa de CPA não abre no histórico consolidado');
assert.ok(html.includes("cpaStatus:'ativa'"),'Análise por Faixa de CPA não abre com o filtro Ativas');
assert.ok(html.includes('>D zero (hoje)</button>'),'visão diária de CPA permanece ambígua');
assert.ok(html.includes('Desempenho por faixa · Impressões'),'gráfico de impressões por faixa ausente');
assert.ok(html.includes('id="cpaImpressionsChart"'),'área do gráfico de impressões ausente');
assert.ok(html.includes('function renderCpaImpressionsChart()'),'renderização das impressões por faixa ausente');
assert.ok(html.includes('id="cpaProductsByRange"')&&html.includes('Quantidade de produtos por faixa de CPA'),'quadro de quantidade de produtos por faixa ausente na Análise por Faixa de CPA');
assert.ok(html.includes('function cpaProductsByRange(rows)')&&html.includes("group.products.add(row.product.toLocaleLowerCase('pt-BR'))"),'produtos não são contados de forma única por faixa na análise de CPA');
assert.ok(html.includes('renderCpaProductsByRange()'),'quadro de produtos por faixa não acompanha os filtros da análise de CPA');
assert.ok(html.includes('cpa-period-filter'),'período da análise de CPA não reserva duas colunas');
assert.ok(html.includes('placeholder="dd/mm/aaaa"'),'datas da análise de CPA não usam o padrão brasileiro');
assert.ok(html.includes('function parseBrazilianDate(value)'),'conversão da data brasileira ausente');
assert.ok(html.includes('cpa-summary-panel'),'painel expansível do resumo por faixa ausente');
assert.ok(html.includes('.cpa-summary{height:100%}'),'tabela de resumo não preenche a altura disponível');
assert.ok(html.includes("absolute<=.75?'ok':absolute<=2.5?'review':'bad'"),'faixas de tolerância da divergência de CPA ausentes');
assert.ok(html.includes('Faixa calculada'),'coluna da faixa calculada ausente');
assert.ok(html.includes('grid-template-columns:224px minmax(0,1fr)'),'menu lateral não foi compactado');
assert.ok(html.includes('Investimento ${totalLabel}'),'total de investimento ausente');
assert.ok(html.includes('Impressões ${totalLabel}'),'total de impressões ausente');
assert.ok(html.includes('Cliques ${totalLabel}'),'total de cliques ausente');
assert.ok(html.includes('Conversões ${totalLabel}'),'total de conversões ausente');
assert.ok(html.includes("['roi','ROI atual'],['account','Conta'],['limit','Limite de teste']"),'coluna Conta não está depois de ROI atual');
assert.ok(html.includes("[['date','Data'],['campaign','Campanha']"),'Data não está na primeira coluna da Visão Geral');
assert.ok(html.includes("[['date','Data'],['campaign','Campanha'],['zeroDays','Dias sem impressões']"),'Dias sem impressões não está na terceira coluna');
assert.ok(html.includes("['remaining','Valor restante'],['status','Situação']]"),'Situação não foi movida para a última coluna');
assert.ok(html.includes('campaignZeroImpressionDays'),'cálculo de dias consecutivos sem impressões ausente');
assert.ok(html.includes('function campaignNumberReuse(c)'),'detecção de numeração de campanha reutilizada ausente');
assert.ok(html.includes('numbering-warning-row'),'destaque vermelho para campanha que precisa ser renumerada ausente');
assert.ok(html.includes('venda manual provisória'),'identificação explícita de venda manual provisória ausente');
assert.ok(html.includes('function campaignStatusObservation(field)'),'normalização do status da MCC ausente');
assert.ok(html.includes("disqualified=search.includes('nao qualificad')"),'variação masculina de “Não qualificado” não é reconhecida');
assert.ok(html.includes('/nao qualificad|reprovad/'),'reprovação masculina não é detectada na Visão Geral');
assert.ok(html.includes('function campaignStatusCandidates(c)'),'Visão Geral não consulta todas as fontes disponíveis de status');
assert.ok(html.includes("m?.status_qualificacao,m?.estado_campanha,m?.raw?.status"),'Visão Geral não usa os campos alternativos de status do manifesto');
assert.ok(html.includes('fields.push(row.celulas?.Q)'),'Visão Geral não usa o status já salvo no diário como contingência');
assert.ok(html.includes("new BroadcastChannel('painel-campanhas')"),'Visão Geral não escuta atualizações feitas pelo Preparador MCC');
assert.ok(html.includes('preparador-MCC/?v=20260919-cpa'),'link do Preparador não invalida versões antigas em cache');
assert.ok(html.includes('Q:{value:campaignStatusObservation(m.status_campanha)}'),'status da MCC não é gravado nas observações diárias');
assert.ok(html.includes("rejected?'Ativa · Reprovada'"),'campanha reprovada não é sinalizada como ativa na Visão Geral');
assert.ok(html.includes("rejected?'rejected-row'"),'destaque visual da campanha reprovada ausente');
assert.ok(html.includes('function campaignIdentity(value)'),'prefixo de data não é separado do nome da campanha');
assert.ok(html.includes('date:r=>r.identity.dateSort'),'coluna Data não possui ordenação cronológica');
assert.ok(html.includes('function campaignAccount(c)'),'extração do sufixo da conta ausente');
assert.ok(html.includes('.topbar{align-items:center;gap:16px;margin-bottom:12px}'),'cabeçalho compacto ausente');
assert.ok(html.includes('#totalsView .table-wrap{max-height:calc(100vh - 275px)}'),'altura compacta da tabela da Visão Geral ausente');
assert.ok(html.includes('totalsConsolidated'),'seletor consolidado ausente');
assert.ok(html.includes('id="totalsD1"'),'seletor D menos um ausente');
assert.ok(html.includes('id="totalsD1" type="button">D−1</button>'),'rótulo compacto D−1 ausente');
assert.ok(!html.includes('D menos um'),'a Visão Geral ainda exibe D menos um por extenso');
assert.ok(html.indexOf('id="totalsConsolidated"')<html.indexOf('id="totalsD1"')&&html.indexOf('id="totalsD1"')<html.indexOf('id="totalsD0"'),'D menos um não está entre Consolidado e D zero');
assert.ok(html.includes("state.totalsMode==='d1'?manifestDates().d1"),'vendas provisórias de D menos um não usam a data correta');
assert.ok(html.includes('function d1Totals(c,history)'),'totais específicos de D menos um ausentes');
assert.ok(html.includes('totalsD0'),'seletor D zero ausente');
assert.ok(html.includes("finally{input.value=''}"),'seletor de arquivo não permite recarregar o mesmo manifesto');
assert.ok(html.includes('Manifesto atualizado:'),'confirmação da atualização do D zero ausente');
assert.ok(html.includes("c.metricas_D_zero,'d0'"),'linha diária completa de D zero ausente');
assert.ok(html.includes('Remover da lista'),'ação reversível de remoção ausente');
assert.ok(html.includes('Editar nome'),'edição de nome de produto ausente');
assert.ok(html.includes('Excluir ocultos permanentemente'),'exclusão permanente ausente');
assert.ok(html.includes('datas_inicio'),'datas oficiais do catálogo ausentes');
assert.ok(html.includes('catalogo_produtos_v1'),'catálogo separado ausente');
assert.ok(!html.includes('__DATABASE_MODULE__'),'módulo não incorporado');
assert.ok(!html.includes('__PRODUCT_CATALOG_MODULE__'),'catálogo não incorporado');
assert.ok(!html.includes('__VIEW_REGISTRY_MODULE__'),'registro de telas não incorporado');
assert.ok(!html.includes('__EMBEDDED_MANIFEST__'),'manifesto não incorporado');
assert.ok(databaseModule.includes("window.CampaignDatabase"),'módulo compartilhado do banco ausente');
assert.ok(databaseModule.includes('addProvisionalSale'),'persistência de venda provisória ausente');
assert.ok(databaseModule.includes('salesAdjustmentMap'),'conciliação de venda provisória ausente');
assert.ok(databaseModule.includes('reconcileProvisionalSales'),'persistência da conciliação oficial da venda manual ausente');
assert.ok(!html.includes('MedicGLP 4'),'a distribuição limpa contém dados reais');
assert.ok(copyFichaView.includes('id="copyReset"')&&copyFichaView.includes('localStorage.removeItem(STORAGE_KEY)')&&copyFichaView.includes('Limpar todos os campos, pacotes e resultados desta coleta?'),'controle de nova coleta não limpa o rascunho com confirmação');
assert.ok(copyFichaView.includes('<option value="">Selecionar</option><option value="en-US">')&&copyFichaView.includes('<option value="">Selecionar</option><option value="USD">'),'nova coleta não permite deixar idioma e moeda pendentes para outra DTC');
for(const match of html.matchAll(/<script>([\s\S]*?)<\/script>/g))new vm.Script(match[1]);
console.log('clean build ok');
