import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';

const page = await readFile(new URL('../src/curadoria/clickbank-top-offers/index.html', import.meta.url), 'utf8');
const view = await readFile(new URL('../src/curadoria/clickbank-top-offers/clickbank-top-offers-view.mjs', import.meta.url), 'utf8');
const controller = await readFile(new URL('../src/curadoria/clickbank-top-offers/clickbank-top-offers-page.mjs', import.meta.url), 'utf8');
const css = await readFile(new URL('../src/curadoria/clickbank-top-offers/clickbank-top-offers.css', import.meta.url), 'utf8');
const publishedCss = await readFile(new URL('../dist/curadoria/clickbank-top-offers/clickbank-top-offers.css', import.meta.url), 'utf8');
const publishedPage = await readFile(new URL('../dist/curadoria/clickbank-top-offers/index.html', import.meta.url), 'utf8');
const sharedCss = await readFile(new URL('../src/curadoria/trends-sheet.css', import.meta.url), 'utf8');

assert.match(css, /#clickbankTopOffersRoot #captureSelect,#clickbankTopOffersRoot #search\{border:0\}/, 'somente os controles de captura e busca indicados ficam sem borda');
assert.match(css, /#clickbankTopOffersRoot #captureSelect\{font-size:\.78rem;line-height:1\.2\}/, 'o seletor de captura mantém tipografia compacta no padrão da Visão Geral');
assert.match(css, /#clickbankTopOffersRoot #captureSelect:focus-visible,#clickbankTopOffersRoot #search:focus-visible\{outline:2px solid var\(--cb-blue\);outline-offset:2px\}/, 'os dois controles preservam foco de teclado visível');
assert.match(page, /clickbank-top-offers\.css\?v=14/, 'a folha alterada invalida o cache');
assert.match(css, /\.import-dialog \.btn\{[^}]*min-height:36px;padding:8px 11px;border:0;border-radius:10px;background:var\(--hub-button-bg,#101e32\);[^}]*font-size:\.78rem;font-weight:400;box-shadow:0 4px 9px rgba\(0,0,0,\.55\)/, 'os quatro botões do modal compartilham dimensão, fundo, remoção de borda e sombra');
assert.match(css, /\.import-dialog \.btn\.primary\{background:var\(--curation-header-action-accent,#38bdf8\);color:var\(--curation-header-action-accent-text,#052037\)\}/, 'Salvar captura usa o azul primário global');
assert.match(css, /\.import-dialog \.btn:hover:not\(:disabled\)\{box-shadow:0 5px 12px rgba\(0,0,0,\.65\)\}/, 'a sombra escurece discretamente no hover');
assert.equal((page.match(/data-close-dialog="importDialog"/g)||[]).length,2,'Fechar e Cancelar continuam presentes no diálogo');
assert.equal(publishedCss,css,'a folha publicada corresponde à fonte canônica');
assert.ok(publishedPage.includes('clickbank-top-offers.css?v=14'),'a página publicada carrega a versão atualizada da folha');
assert.match(css, /\.tablewrap \[data-column="rank"\]\{text-align:center!important\}/, 'cabeçalho e conteúdo da coluna Posição ficam centralizados sem depender da ordem visual das colunas');

for (const id of ['clickbankTopOffersRoot','openImport','captureSelect','captureInfo','search','rows','importDialog','pasteArea','validateImport','confirmImport','exportBackup','restoreBackup','offerSheet','trendCountries','dtcCountrySource','openClickBankOffer','clickBankOfferUnavailable','trendCandidate','trendResults','imageCountries','glimpseFrame']) {
  assert.ok(page.includes(`id="${id}"`), `elemento ${id} ausente da página`);
}
assert.ok(page.includes('data-hub-sidebar-active="clickbank-top-offers"'));
assert.ok(page.includes('Curadoria · ClickBank') && page.includes('Top Offers CB'));
const summaryRowIndex=page.indexOf('class="capture-summary-row"'),captureInfoIndex=page.indexOf('id="captureInfo"'),toolbarIndex=page.indexOf('class="capture-toolbar"'),searchIndex=page.indexOf('id="search"'),selectionIndex=page.indexOf('class="capture-selection"'),captureSelectIndex=page.indexOf('id="captureSelect"');
assert.ok(summaryRowIndex<captureInfoIndex&&captureInfoIndex<toolbarIndex&&toolbarIndex<searchIndex&&searchIndex<selectionIndex&&selectionIndex<captureSelectIndex,'informação da captura e Colunas dividem a mesma faixa compacta antes da busca e tabela');
assert.match(css,/\.capture-summary-row\{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:9px\}/,'metadados e ação dividem a faixa para remover o espaço vertical extra');
assert.match(css,/\.capture-summary-row\{align-items:flex-start\}/,'a faixa preserva alinhamento legível em telas estreitas');
assert.match(page, /\.\/clickbank-top-offers-page\.mjs\?v=\d+/);
assert.match(controller,/finishLabel:'Salvar',showSavedFeedback:true/,'Glimpse oferece Salvar e uma confirmação após persistência');
assert.match(controller,/glimpse-embed-controls\.mjs\?v=2/,'o helper de cabeçalho atualizado invalida o cache');
assert.match(controller, /\.\/clickbank-top-offers-view\.mjs\?v=\d+/);
assert.ok(controller.includes('./clickbank-top-offers-domain.mjs?v=2'));
assert.ok(view.includes('./clickbank-top-offers-domain.mjs?v=2'));
assert.ok(controller.includes("mountCurationListFocus('clickbank-top-offers'")&&controller.includes("blockingSelector:'#offerSheet:not(.hidden), #sharedDecisionDialog[open]'")&&controller.includes('highlightOnCapture:false,restoreOnWindowReturn:false,suppressPulseOnPageHide:true'),'Top Offers CB pisca ao fechar a ficha/modal, não apenas ao trocar de janela');
assert.ok(controller.includes('list-focus.mjs?v=3'),'Top Offers CB carrega a versão atualizada do helper compartilhado');
assert.ok(controller.includes('restoreListFocus:()=>listFocus.restore()')&&view.includes("function closeSheet() { sheet.classList.add('hidden');activeOfferKey='';actions.restoreListFocus?.(); }"),'Voltar à lista restaura e pisca depois de ocultar a ficha');
assert.match(controller,/clickbank-top-offers-view\.mjs\?v=14/,'a view alterada invalida o cache');
assert.match(view, /const \$ = \(selector,\s*root\) => root\.querySelector\(selector\);/, 'a busca singular recebe o seletor antes da raiz, como fazem os consumidores da view');
const rootStart = page.indexOf('<main id="clickbankTopOffersRoot">'), rootEnd = page.indexOf('</main>');
assert.ok(rootStart < page.indexOf('id="offerSheet"') && page.indexOf('id="offerSheet"') < rootEnd, 'a ficha fica sob a raiz da view');
assert.ok(rootStart < page.indexOf('id="importDialog"') && page.indexOf('id="importDialog"') < rootEnd, 'o diálogo e o campo de colagem ficam acessíveis ao adaptador');
assert.match(page, /<section class="sheet product-sheet hidden" id="offerSheet"/, 'a ficha usa o shell compartilhado de tela cheia, não fica abaixo da tabela');
assert.match(sharedCss, /\.product-sheet\{[^}]*position:fixed;inset:0;z-index:40;[^}]*overflow:auto/, 'o shell cobre a viewport com rolagem própria');
assert.match(sharedCss, /\.product-sheet\.hidden\{display:none\}/, 'fechar a ficha restaura a listagem sem remover dados');
assert.match(view, /if\(item\)openSheet\(item,button\.dataset\.action\)/, 'cada atalho abre diretamente sua aba na ficha');
assert.ok(view.includes('replace(/[&<>"\']/g'), 'texto importado deve ser escapado antes de gerar HTML');
assert.ok(view.includes('compareCapturedOffers') && view.includes('selected.page.total'));
assert.ok(!view.includes('Recorte parcial: itens fora deste recorte não são considerados saídas.'), 'a descrição da captura não mostra mais o aviso removido');
assert.ok(view.includes('selected.page.completeUniverse') && view.includes('Lista completa.'), 'a descrição mantém a indicação positiva de lista completa');
assert.ok(controller.includes('captureId:`clickbank-${crypto.randomUUID()}`'));
assert.ok(controller.includes('await Storage.saveCapture(capture)'));
assert.ok(controller.includes('Storage.mergeBackup(payload)'));
for (const label of ['Google Trends','Glimpse','Imagens']) assert.ok(page.includes(`>${label}<`), `aba ${label} ausente`);
for (const key of ['trends','glimpse','images']) assert.ok(view.includes(`data-action="${key}"`), `coluna/ação ${key} ausente`);
assert.ok(page.includes('<th>Decisão</th>') && view.includes('DecisionUI.buttonHtml'), 'a tabela tem uma coluna de decisão');
assert.ok(view.includes('DecisionUI.openDecisionPicker') && controller.includes('Storage.putDecision(stored)'), 'a decisão é escolhida e salva exclusivamente em Top Offers CB');
assert.match(view, /<tr data-offer="\$\{escape\(item\.offerKey\)\}"/,'cada linha expõe sua identidade estável para restaurar rolagem e destaque');
for(const [kind,badge] of [['trends','trendBadge'],['glimpse','glimpseBadge'],['images','imageBadge']]) assert.match(view,new RegExp(`function ${badge}[\\s\\S]*?data-curation-focus="${kind}"`),`${kind} registra o controle acionado para piscar no retorno`);
assert.ok(controller.includes('Decisão salva somente em Top Offers CB'), 'a interface deixa claro o escopo da decisão');
assert.ok(view.includes('renderResultButtons') && view.includes('renderProductAgeButtons') && view.includes('renderImageResultButtons'), 'reutiliza os componentes compartilhados de Trends e Imagens');
assert.ok(view.includes('showRemoveForSaved:true'), 'candidatas negativas mantêm o X visível depois de reabrir a ficha');
assert.ok(controller.includes("origin:'clickbank-top-offers'"), 'eventos de análise são atribuídos à nova origem');
assert.ok(page.includes('A ClickBank não informa GEO') && page.includes('Países Comuns') && view.includes('manualCountries'), 'não inventa GEO e permite lista manual ou captura DTC, sem alterar a captura de origem');
assert.ok(view.includes('Lista capturada da DTC') && view.includes("dtcCountries.has(code)?'DTC':'manual'"), 'a ficha indica origem DTC e identifica os países correspondentes');
assert.ok(page.indexOf('id="trendCountries"') < page.indexOf('id="openClickBankOffer"'), 'o atalho ClickBank aparece abaixo dos países na aba Google Trends');
assert.ok(view.includes('clickbank-rank-link') && view.includes('>#${escape(item.rank)}</a>'), 'a posição com # vira link quando a captura traz Offer ID');
assert.ok(view.includes(': `#${escape(item.rank)}`'), 'capturas antigas mantêm a posição com #, sem um link fabricado');
assert.match(page, /id="openClickBankOffer"[^>]*target="_blank" rel="noopener noreferrer"/, 'o link abre em nova aba com proteção de origem');
assert.ok(css.includes('.top h1{') && css.includes('overflow-x') || css.includes('.tablewrap{overflow:auto'), 'layout mantém a tabela responsiva');
assert.ok(page.includes(' nada é salvo antes de você confirmar') || page.includes('Nada é salvo antes de você confirmar'));

console.log('clickbank top offers ui ok');

assert.match(page, /data-panel="glimpse"><iframe id="glimpseFrame"/, 'Glimpse acompanha GM sem cartão externo redundante');
assert.match(controller, /event.origin!==location.origin\|\|event.source!==frame.contentWindow/, 'resize/retorno do iframe têm origem e janela validadas');
assert.match(sharedCss, /curation-focus-row-pulse/,'a linha usa a animação compartilhada em azul-claro');
assert.match(controller, /hub-glimpse-resize[\s\S]*Math.max\(320,Math.ceil\(height\)\)/, 'altura incorpora conteúdo completo sem scroll interno');
assert.match(page, /id="finishImages" class="btn image-search-button"/, 'concluir usa o CTA azul compartilhado, sem primary verde concorrente');
assert.match(view, /\$\('#finishImages',root\)\.onclick=closeSheet/, 'concluir apenas fecha, sem salvar novamente');
assert.match(view, /Images.progress\(record.assessments\|\|\[\],countries\)/, 'progresso considera os países manuais sem presumir GEO');
assert.match(css, /#offerSheet \.card\{background:var\(--panel\);border-radius:16px/, 'o host fornece superfícies equivalentes à GM');
assert.match(css, /#offerSheet \.field-label\{display:block/, 'rótulo não fica junto ao input numa linha');
assert.match(css, /#offerSheet \.trends-search-row \.control\{width:100%\}/, 'termo utiliza toda a largura disponível');
assert.match(view, /\['message','sheetMessage'\]/, 'avisos não ficam escondidos atrás da ficha');
for(const id of ['trendsHistory','imagesHistory','allTrendsHistory','allImagesHistory']) assert.equal(page.split(`id="${id}"`).length-1,1, `histórico ${id} preserva um ID único`);
