import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';

const page = await readFile(new URL('../src/curadoria/clickbank-top-offers/index.html', import.meta.url), 'utf8');
const view = await readFile(new URL('../src/curadoria/clickbank-top-offers/clickbank-top-offers-view.mjs', import.meta.url), 'utf8');
const controller = await readFile(new URL('../src/curadoria/clickbank-top-offers/clickbank-top-offers-page.mjs', import.meta.url), 'utf8');
const css = await readFile(new URL('../src/curadoria/clickbank-top-offers/clickbank-top-offers.css', import.meta.url), 'utf8');
const curationColumns = await readFile(new URL('../src/curadoria/curation-columns.mjs', import.meta.url), 'utf8');
const publishedCss = await readFile(new URL('../dist/curadoria/clickbank-top-offers/clickbank-top-offers.css', import.meta.url), 'utf8');
const publishedPage = await readFile(new URL('../dist/curadoria/clickbank-top-offers/index.html', import.meta.url), 'utf8');
const sharedCss = await readFile(new URL('../src/curadoria/trends-sheet.css', import.meta.url), 'utf8');
const filterCss = await readFile(new URL('../src/curadoria/curation-table-filters.css', import.meta.url), 'utf8');

assert.match(css, /#clickbankTopOffersRoot #captureSelect,#clickbankTopOffersRoot #search\{border:0\}/, 'somente os controles de captura e busca indicados ficam sem borda');
assert.match(css, /#clickbankTopOffersRoot #captureSelect\{line-height:1\.2\}/, 'o seletor de captura herda a tipografia do padrão compacto compartilhado');
assert.match(css, /\.capture-selection\{display:grid;grid-template-columns:auto minmax\(0,1fr\);[^}]*min-width:min\(100%,360px\);max-width:520px\}/, 'o seletor reserva espaço para rótulo e campo e mantém largura máxima compacta');
assert.match(css, /\.capture-selection select\{width:100%;min-width:0\}/, 'o campo se ajusta à largura efetiva do contêiner');
assert.match(css, /\.capture-results-count\{flex:0 0 auto;/, 'o total não encolhe nem invade o seletor');
assert.match(filterCss, /\.hub-curation-table-filters :is\(input, select\)\.control\s*\{[^}]*height:\s*32px;[^}]*padding:\s*7px;[^}]*font-size:\s*\.74rem;[^}]*line-height:\s*1\.2;/, 'inputs e seletores das barras de tabela compartilham altura, espaçamento e tipografia compactos');
assert.match(page, /class="filter-grid hub-curation-table-filters"[\s\S]*?id="captureSelect"/, 'o seletor de captura participa do padrão compartilhado de filtros');
assert.match(page, /<select class="control" id="captureSelect"/, 'o seletor usa a superfície compartilhada de controles');
assert.match(css, /#clickbankTopOffersRoot #captureSelect:focus-visible,#clickbankTopOffersRoot #search:focus-visible\{outline:2px solid var\(--cb-blue\);outline-offset:2px\}/, 'os dois controles preservam foco de teclado visível');
assert.match(page, /trends-sheet\.css\?v=20261006-curation-decision-column/, 'a página carrega a versão atual do CSS compartilhado da ficha ClickBank');
assert.match(page, /clickbank-top-offers\.css\?v=24/, 'a folha alterada invalida o cache');
assert.match(css, /@media\(min-width:681px\)\{#clickbankTopOffersRoot \.capture-toolbar\{transform:translateY\(-8px\)\}\}/, 'Colunas fica mais perto da borda superior sem mover os filtros');
assert.match(css, /\.import-dialog \.btn\{[^}]*min-height:36px;padding:8px 11px;border:0;border-radius:10px;background:var\(--hub-button-bg,#101e32\);[^}]*font-size:\.78rem;font-weight:400;box-shadow:0 4px 9px rgba\(0,0,0,\.55\)/, 'os quatro botões do modal compartilham dimensão, fundo, remoção de borda e sombra');
assert.match(css, /\.import-dialog \.btn\.primary\{background:var\(--curation-header-action-accent,#38bdf8\);color:var\(--curation-header-action-accent-text,#052037\)\}/, 'Salvar captura usa o azul primário global');
assert.match(css, /\.import-dialog \.btn:hover:not\(:disabled\)\{box-shadow:0 5px 12px rgba\(0,0,0,\.65\)\}/, 'a sombra escurece discretamente no hover');
assert.equal((page.match(/data-close-dialog="importDialog"/g)||[]).length,2,'Fechar e Cancelar continuam presentes no diálogo');
assert.equal(publishedCss,css,'a folha publicada corresponde à fonte canônica');
assert.ok(publishedPage.includes('clickbank-top-offers.css?v=24'),'a página publicada carrega a versão atualizada da folha');
assert.match(css, /\.tablewrap \[data-column="rank"\]\{text-align:center!important\}/, 'cabeçalho e conteúdo da coluna Posição ficam centralizados sem depender da ordem visual das colunas');

for (const id of ['clickbankTopOffersRoot','openImport','captureSelect','captureResultCount','search','rows','importDialog','pasteArea','validateImport','confirmImport','exportBackup','restoreBackup','offerSheet','trendCountries','openClickBankOffer','clickBankOfferUnavailable','trendCandidate','trendResults','saveSheetButton','closeSheet','imageCountries','salesPageTypeActions','glimpseFrame']) {
  assert.ok(page.includes(`id="${id}"`), `elemento ${id} ausente da página`);
}
assert.ok(page.includes('data-hub-sidebar-active="clickbank-top-offers"'));
assert.ok(page.includes('Curadoria · ClickBank') && page.includes('Top Offers CB'));
const filterGridIndex=page.indexOf('class="filter-grid hub-curation-table-filters"'),searchIndex=page.indexOf('id="search"'),selectionIndex=page.indexOf('class="capture-selection"'),captureSelectIndex=page.indexOf('id="captureSelect"'),resultCountIndex=page.indexOf('id="captureResultCount"'),toolbarIndex=page.indexOf('class="capture-toolbar"'),tableIndex=page.indexOf('class="tablewrap"');
assert.ok(filterGridIndex<searchIndex&&searchIndex<selectionIndex&&selectionIndex<captureSelectIndex&&captureSelectIndex<resultCountIndex&&resultCountIndex<toolbarIndex&&toolbarIndex<tableIndex,'busca, seletor, total e Colunas dividem uma única faixa acima da tabela');
assert.doesNotMatch(page,/capture-summary-row|id="captureInfo"/,'a linha descritiva da captura foi removida para compactar a tabela');
assert.match(css,/\.capture-toolbar\{[^}]*margin-left:auto\}/,'Colunas permanece alinhado à direita na faixa dos filtros');
assert.match(css,/\.capture-results-count\{flex:0 0 auto;color:var\(--cb-muted\);font-size:\.74rem;line-height:1\.2;white-space:nowrap\}/,'a contagem mantém sua largura e não invade o seletor');
assert.match(css,/@media\(max-width:680px\)[\s\S]*?\.capture-selection\{display:flex;align-items:stretch;flex:0 1 auto;flex-direction:column;min-width:0\}/,'em telas estreitas, o rótulo e o seletor empilham sem forçar largura horizontal');
assert.match(page, /\.\/clickbank-top-offers-page\.mjs\?v=\d+/);
assert.match(controller,/finishLabel:'Salvar',showSavedFeedback:true/,'Glimpse oferece Salvar e uma confirmação após persistência');
assert.match(controller,/glimpse-embed-controls\.mjs\?v=4/,'o helper compartilhado invalida o cache');
assert.match(controller,/actionButton:root\.querySelector\('#saveSheetButton'\)/,'Glimpse usa o botão único da barra em vez de criar outro botão no cabeçalho');
assert.match(controller, /\.\/clickbank-top-offers-view\.mjs\?v=\d+/);
assert.ok(controller.includes('./clickbank-top-offers-domain.mjs?v=2'));
assert.ok(view.includes('./clickbank-top-offers-domain.mjs?v=2'));
assert.ok(controller.includes("mountCurationListFocus('clickbank-top-offers'")&&controller.includes("blockingSelector:'#offerSheet:not(.hidden), #sharedDecisionDialog[open]'")&&controller.includes('highlightOnCapture:false,restoreOnWindowReturn:false,suppressPulseOnPageHide:true'),'Top Offers CB pisca ao fechar a ficha/modal, não apenas ao trocar de janela');
assert.ok(controller.includes('list-focus.mjs?v=3'),'Top Offers CB carrega a versão atualizada do helper compartilhado');
assert.ok(controller.includes('restoreListFocus:()=>listFocus.restore()')&&view.includes("function closeSheet() { sheet.classList.add('hidden');activeOfferKey='';actions.restoreListFocus?.(); }"),'Voltar à lista restaura e pisca depois de ocultar a ficha');
assert.match(controller,/clickbank-top-offers-view\.mjs\?v=22/,'a view alterada invalida o cache');
assert.match(page,/<button class="btn primary" id="saveSheetButton" type="button">Salvar<\/button>/,'a barra mantém um único botão Salvar compartilhado por todas as abas');
assert.match(view, /const \$ = \(selector,\s*root\) => root\.querySelector\(selector\);/, 'a busca singular recebe o seletor antes da raiz, como fazem os consumidores da view');
const rootStart = page.indexOf('<main id="clickbankTopOffersRoot">'), rootEnd = page.indexOf('</main>');
assert.ok(rootStart < page.indexOf('id="offerSheet"') && page.indexOf('id="offerSheet"') < rootEnd, 'a ficha fica sob a raiz da view');
assert.ok(rootStart < page.indexOf('id="importDialog"') && page.indexOf('id="importDialog"') < rootEnd, 'o diálogo e o campo de colagem ficam acessíveis ao adaptador');
assert.match(page, /<section class="sheet product-sheet hidden" id="offerSheet"/, 'a ficha usa o shell compartilhado de tela cheia, não fica abaixo da tabela');
assert.match(sharedCss, /\.product-sheet\{[^}]*position:fixed;inset:0;z-index:40;[^}]*overflow:auto/, 'o shell cobre a viewport com rolagem própria');
assert.match(sharedCss, /\.product-sheet\.hidden\{display:none\}/, 'fechar a ficha restaura a listagem sem remover dados');
assert.match(page, /<div class="sheet-tab-bar">[\s\S]*?class="tabs" role="tablist"[\s\S]*?id="saveSheetButton"[\s\S]*?id="closeSheet"/, 'a barra fixa reúne abas, Salvar e Voltar à lista em todos os painéis');
const offerSheetStart=page.indexOf('id="offerSheet"'),sheetBarIndex=page.indexOf('<div class="sheet-tab-bar">',offerSheetStart),sheetTitleIndex=page.indexOf('<header class="sheet-top">',offerSheetStart);
assert.ok(sheetBarIndex>offerSheetStart&&sheetBarIndex<sheetTitleIndex,'a barra abre no topo da ficha, antes do título da oferta');
assert.match(css, /#offerSheet \.sheet-tab-bar\{position:sticky;top:0;[^}]*width:100%;margin:0 0 14px;[^}]*border:0/, 'a barra nasce no topo e acompanha a rolagem, sem contorno externo');
assert.match(view, /Resultado selecionado\. Clique em Salvar para registrar\./, 'a escolha do resultado fica pendente e instrui a confirmar');
assert.match(view, /const saved=await actions\.saveTrend\(/, 'a gravação de Trends ocorre pelo botão Salvar');
assert.match(page, /clickbank-top-offers-page\.mjs\?v=26/, 'a página alterada invalida o cache');
assert.match(controller, /hub-glimpse-save-result'\)\{if\(event\.data\.saved===true\)void refreshAfterGlimpseSave\(\);return;\}/, 'o salvamento confirmado atualiza a lista sem fechar a ficha');
assert.match(controller, /async function refreshAfterGlimpseSave\(\)[\s\S]*?await refresh\(\)/, 'o host recarrega o snapshot Glimpse persistido');
assert.match(page, /clickbank-top-offers\.css\?v=24/, 'a barra sticky invalida o cache do CSS desta tela sem mudar outras fichas');
assert.match(view, /if\(item\)openSheet\(item,button\.dataset\.action\)/, 'cada atalho abre diretamente sua aba na ficha');
assert.ok(view.includes('replace(/[&<>"\']/g'), 'texto importado deve ser escapado antes de gerar HTML');
assert.ok(view.includes('compareCapturedOffers') && view.includes('selected.page.total'));
assert.ok(view.includes('new Intl.NumberFormat(\'pt-BR\').format(Number(selected.page.total))') && view.includes('selected.page.completeUniverse'), 'total de resultados e captura completa são reapresentados juntos aos filtros');
assert.ok(controller.includes('captureId:`clickbank-${crypto.randomUUID()}`'));
assert.ok(controller.includes('await Storage.saveCapture(capture)'));
assert.ok(controller.includes('Storage.mergeBackup(payload)'));
for (const label of ['Google Trends','Glimpse','Imagens']) assert.ok(page.includes(`>${label}<`), `aba ${label} ausente`);
for (const key of ['trends','glimpse','images']) assert.ok(view.includes(`data-action="${key}"`), `coluna/ação ${key} ausente`);
assert.ok(page.includes('<th>Decisão</th>') && view.includes('DecisionUI.buttonHtml'), 'a tabela tem uma coluna de decisão');
assert.ok(view.includes('DecisionUI.openDecisionPicker') && controller.includes('Storage.putDecision(stored)'), 'a decisão é escolhida e salva exclusivamente em Top Offers CB');
assert.match(view, /<tr data-offer="\$\{escape\(item\.offerKey\)\}"/,'cada linha expõe sua identidade estável para restaurar rolagem e destaque');
for(const [kind,badge] of [['trends','trendBadge'],['glimpse','glimpseBadge'],['images','imageBadge']]) assert.match(view,new RegExp(`function ${badge}[\\s\\S]*?data-curation-focus="${kind}"`),`${kind} registra o controle acionado para piscar no retorno`);
assert.ok(controller.includes('Decisão salva somente em Top Offers CB'), 'a interface deixa claro o escopo da decisão');
assert.ok(view.includes('renderResultButtons') && view.includes('renderProductAgeButtons') && view.includes('renderImageResultButtons'), 'reutiliza os componentes compartilhados de Trends e Imagens');
assert.ok(page.includes('class="trends-analysis-meta"') && page.includes('Momento do produto') && page.includes('Tipo de página de venda'), 'o tipo da página divide a faixa marcada com o momento do produto');
assert.ok(page.includes('Classificação manual do tipo de página de venda') && page.includes('Classificação manual desta oferta.'), 'o controle informa que a classificação é manual e por oferta');
assert.ok(view.includes('SALES_PAGE_TYPES') && view.includes('data-sales-page-type') && view.includes('actions.saveSalesPageType(item.offerKey'), 'DTC/VSL/TSL/Quiz e limpeza salvam a escolha para a oferta ativa');
assert.ok(controller.includes('async function saveSalesPageType(offerKey,value)') && controller.includes('Storage.STORES.offerMetadata'), 'a classificação fica na store de metadados, separada da captura original');
assert.match(page, /data-sort="future" type="button">PAG\.<\/button>/, 'a coluna que ocupava Future $ é identificada como PAG.');
assert.doesNotMatch(page, />Future \$</, 'Future $ deixa de aparecer como coluna na tabela');
assert.ok(view.includes('salesPageTypeLabel(metadataFor(item).salesPageType)') && view.includes('class="page-type-cell"'), 'a coluna apresenta a classificação manual da oferta');
assert.ok(view.includes("sortKey==='future'?pageTypeText(item).toLocaleLowerCase()") && !view.includes('metricText(item.future)'), 'a coluna mantém ordenação pela classificação sem exibir a métrica capturada');
assert.ok(curationColumns.includes("['future','PAG.']"), 'o seletor de colunas também identifica a coluna como PAG.');
assert.ok(css.includes('.tablewrap [data-column="future"]{text-align:center}'), 'DTC/VSL/TSL/Quiz e o travessão ficam centralizados');
assert.ok(view.includes('showRemoveForSaved:true'), 'candidatas negativas mantêm o X visível depois de reabrir a ficha');
assert.ok(controller.includes("origin:'clickbank-top-offers'"), 'eventos de análise são atribuídos à nova origem');
assert.ok(page.includes('A ClickBank não informa GEO') && page.includes('Países Comuns') && view.includes('manualCountries'), 'não inventa GEO e permite lista manual ou captura DTC, sem alterar a captura de origem');
assert.ok(!page.includes('dtcCountrySource') && !view.includes('Lista capturada da DTC'), 'a ficha não exibe a linha de origem/data da captura DTC');
assert.ok(view.includes('metadata.dtcCountryCapture?.countries') && view.includes("dtcCountries.has(code)?'DTC':'manual'"), 'países capturados da DTC continuam identificados nos badges');
assert.ok(page.indexOf('id="trendCountries"') < page.indexOf('id="openClickBankOffer"'), 'o atalho ClickBank aparece abaixo dos países na aba Google Trends');
assert.ok(view.includes('clickbank-rank-link') && view.includes('>#${escape(item.rank)}</a>'), 'a posição com # vira link quando a captura traz Offer ID');
assert.ok(view.includes(': `#${escape(item.rank)}`'), 'capturas antigas mantêm a posição com #, sem um link fabricado');
assert.match(page, /id="openClickBankOffer"[^>]*target="_blank" rel="noopener noreferrer"/, 'o link abre em nova aba com proteção de origem');
assert.ok(css.includes('.top h1{') && css.includes('overflow-x') || css.includes('.tablewrap{overflow:auto'), 'layout mantém a tabela responsiva');
assert.ok(page.includes(' nada é salvo antes de você confirmar') || page.includes('Nada é salvo antes de você confirmar'));

console.log('clickbank top offers ui ok');

assert.match(page, /data-panel="glimpse"><iframe id="glimpseFrame"/, 'Glimpse acompanha GM sem cartão externo redundante');
assert.match(controller, /event.origin!==location.origin\|\|event.source!==frame.contentWindow/, 'resize/retorno do iframe têm origem e janela validadas');
assert.match(sharedCss, /curation-focus-row-pulse/,'a linha usa a animação compartilhada em azul-claro');
assert.match(controller, /hub-glimpse-resize[\s\S]*Math.max\(320,Math.ceil\(height\)\)/, 'altura incorpora conteúdo completo sem scroll interno');
assert.doesNotMatch(page, /id="finishImages"/, 'o retorno de Imagens não é duplicado fora da barra comum');
assert.match(sharedCss, /#offerSheet #imageCountries button\.image-search-button\{[^}]*min-height:0;[^}]*width:auto;[^}]*border:0;[^}]*background:transparent;[^}]*box-shadow:none;[^}]*text-decoration:underline/, 'as buscas de imagem da ficha ClickBank têm aparência de link compacto sem borda, fundo ou sombra');
assert.match(sharedCss, /#offerSheet #imageCountries button\.image-search-button::after\{content:none\}/, 'as buscas em formato de link não exibem a seta decorativa de botão');
assert.match(sharedCss, /#offerSheet #imageCountries button\.image-search-button:focus-visible\{[^}]*outline:2px solid/, 'as buscas em formato de link preservam foco de teclado visível');
assert.match(view, /data-image-search="\$\{escape\(country\)\}"/, 'a busca normal por país continua acionando o mesmo botão');
assert.match(view, /onSearchAll:values=>actions\.openImagesExcluding\(\$\('#imagesTerm',root\)\.value\.trim\(\)\|\|item\.offerName,country,values\)/, 'a busca que exclui todas as candidatas continua preservando seu callback');
assert.match(view, /const reasons=\{[\s\S]*?images:\[[^\]]*salvas automaticamente[^\]]*\][\s\S]*?history:\[[^\]]*somente leitura[^\]]*\]/, 'Salvar explica por que Imagens e Histórico não recebem gravação manual');
assert.match(view, /Images.progress\(record.assessments\|\|\[\],countries\)/, 'progresso considera os países manuais sem presumir GEO');
assert.match(css, /#offerSheet \.card\{background:var\(--panel\);border-radius:16px/, 'o host fornece superfícies equivalentes à GM');
assert.match(css, /#offerSheet \.field-label\{display:block/, 'rótulo não fica junto ao input numa linha');
assert.match(css, /#offerSheet \.trends-search-row \.control\{width:100%\}/, 'termo utiliza toda a largura disponível');
assert.match(view, /\['message','sheetMessage'\]/, 'avisos não ficam escondidos atrás da ficha');
for(const id of ['trendsHistory','imagesHistory','allTrendsHistory','allImagesHistory']) assert.equal(page.split(`id="${id}"`).length-1,1, `histórico ${id} preserva um ID único`);
