import assert from'node:assert/strict';
import{mountCurationListFocus}from'../src/curadoria/list-focus.mjs';

const stored=new Map(),listeners=[],rowClasses=new Set(),controlClasses=new Set();
const control={dataset:{curationFocus:'glimpse'},offsetWidth:100,classList:{add:value=>controlClasses.add(value),remove:value=>controlClasses.delete(value)}};
const row={dataset:{product:'normalized-product'},offsetWidth:800,classList:{add:value=>rowClasses.add(value),remove:value=>rowClasses.delete(value)},hasAttribute:name=>name==='data-product',getAttribute:name=>name==='data-product'?'normalized-product':null,querySelectorAll:selector=>selector.includes('data-curation-focus')?[control]:[]};
control.closest=selector=>selector==='[data-product],[data-offer]'?row:null;
let scrollPosition=[0,0],listScrollPosition=[0,0],offerSheetOpen=false;
const listScroll={dataset:{},scrollLeft:154,scrollTop:386};
const decisionDialog={id:'sharedDecisionDialog',open:false};
globalThis.sessionStorage={getItem:key=>stored.get(key)||null,setItem:(key,value)=>stored.set(key,value),removeItem:key=>stored.delete(key)};
globalThis.document={visibilityState:'visible',addEventListener:(name,handler,capture)=>listeners.push({name,handler,capture}),querySelector:selector=>selector==='.tablewrap'||selector==='[data-curation-list-scroll]'?listScroll:selector.includes('#offerSheet')&&offerSheetOpen?{}:selector.includes('#sharedDecisionDialog[open]')&&decisionDialog.open?decisionDialog:null,querySelectorAll:()=>[row]};
globalThis.window={scrollX:31,scrollY:742,scrollTo:(x,y)=>{scrollPosition=[x,y]},addEventListener:(name,handler)=>listeners.push({name,handler})};

const focus=mountCurationListFocus('manager',{blockingSelector:'#productSheet:not(.hidden)'});
listeners.find(item=>item.name==='click'&&item.capture===true).handler({target:{closest:()=>control}});
assert.ok(rowClasses.has('curation-focus-pulse'),'a linha recebe destaque imediato no acionamento');
assert.ok(controlClasses.has('curation-focus-pulse'),'o controle acionado recebe destaque imediato');
assert.ok('curationListScroll'in listScroll.dataset,'o contêiner da tabela fica marcado para preservar sua rolagem');
const saved=JSON.parse(stored.get('curadoria-list-focus:v1:manager'));
assert.deepEqual(saved,{rowAttribute:'data-product',rowKey:'normalized-product',control:'glimpse',scrollX:31,scrollY:742,listScroll:{left:154,top:386},capturedAt:saved.capturedAt});
scrollPosition=[0,0];
listScrollPosition=[listScroll.scrollLeft,listScroll.scrollTop];
listScroll.scrollLeft=0;listScroll.scrollTop=0;
rowClasses.clear();controlClasses.clear();
globalThis.document.querySelectorAll=()=>[];
assert.equal(focus.restore(),false,'a posição aguarda a listagem recriar a linha capturada');
assert.deepEqual(scrollPosition,[0,0],'não tenta restaurar antes de a linha existir na página');
assert.equal(stored.has('curadoria-list-focus:v1:manager'),true,'mantém o estado salvo até a linha reaparecer');
globalThis.document.querySelectorAll=()=>[row];
assert.equal(focus.restore(),true,'o estado capturado pode ser restaurado depois da volta');
assert.deepEqual(scrollPosition,[31,742],'a posição vertical e horizontal da página é restaurada');
assert.deepEqual([listScroll.scrollLeft,listScroll.scrollTop],listScrollPosition,'a rolagem interna e horizontal da tabela também é restaurada');
assert.ok(rowClasses.has('curation-focus-pulse'),'a linha é destacada novamente no retorno');
assert.ok(controlClasses.has('curation-focus-pulse'),'o mesmo controle é destacado no retorno');
assert.equal(stored.has('curadoria-list-focus:v1:manager'),false,'o estado é consumido após restauração');

rowClasses.clear();controlClasses.clear();
const ecommerceFocus=mountCurationListFocus('top-performance',{blockingSelector:'#offerSheet:not(.hidden)',highlightOnCapture:false});
const ecommerceCapture=listeners.filter(item=>item.name==='click'&&item.capture===true).at(-2);
ecommerceCapture.handler({target:{closest:()=>control}});
assert.equal(rowClasses.has('curation-focus-pulse'),false,'E-commerce GM não anima a linha ao abrir a ficha/pop-up');
assert.equal(controlClasses.has('curation-focus-pulse'),false,'E-commerce GM não anima o botão ao abrir a ficha/pop-up');
assert.equal(ecommerceFocus.restore(),true,'E-commerce GM restaura e anima somente ao voltar à listagem');
assert.ok(rowClasses.has('curation-focus-pulse'),'a linha é animada depois do retorno à lista');
assert.ok(controlClasses.has('curation-focus-pulse'),'o controle de imagens/trends é animado depois do retorno à lista');

rowClasses.clear();controlClasses.clear();control.dataset.curationFocus='decision';
const decisionFocus=mountCurationListFocus('clickbank-top-offers',{blockingSelector:'#offerSheet:not(.hidden), #sharedDecisionDialog[open]',highlightOnCapture:false});
listeners.filter(item=>item.name==='click'&&item.capture===true).at(-2).handler({target:{closest:()=>control}});
decisionDialog.open=true;
assert.equal(decisionFocus.restore(),false,'o retorno aguarda o fechamento do seletor de decisão');
assert.equal(stored.has('curadoria-list-focus:v1:clickbank-top-offers'),true,'a decisão mantém o foco pendente enquanto o seletor está aberto');
decisionDialog.open=false;
listeners.filter(item=>item.name==='close'&&item.capture===true).at(-1).handler({target:decisionDialog});
await new Promise(resolve=>setTimeout(resolve,0));
assert.ok(rowClasses.has('curation-focus-pulse'),'a linha pisca após fechar a decisão');
assert.ok(controlClasses.has('curation-focus-pulse'),'o badge de decisão pisca após fechar o seletor');
assert.equal(stored.has('curadoria-list-focus:v1:clickbank-top-offers'),false,'a restauração consome o foco depois do fechamento da decisão');

rowClasses.clear();controlClasses.clear();control.dataset.curationFocus='images';
const imagesFocus=mountCurationListFocus('clickbank-images',{blockingSelector:'#offerSheet:not(.hidden)',highlightOnCapture:false});
listeners.filter(item=>item.name==='click'&&item.capture===true).at(-2).handler({target:{closest:()=>control}});
const finishImagesButton={closest:selector=>selector.includes('#finishImages')?{}:null};
listeners.filter(item=>item.name==='click'&&item.capture===true).at(-1).handler({target:finishImagesButton});
await new Promise(resolve=>setTimeout(resolve,0));
assert.ok(rowClasses.has('curation-focus-pulse'),'Concluir e voltar restaura o destaque da linha');
assert.ok(controlClasses.has('curation-focus-pulse'),'Concluir e voltar restaura o destaque do botão Imagens');
assert.equal(stored.has('curadoria-list-focus:v1:clickbank-images'),false,'Concluir e voltar consome o foco da linha');

rowClasses.clear();controlClasses.clear();control.dataset.curationFocus='trends';
const returnFocus=mountCurationListFocus('external-popup',{blockingSelector:'#offerSheet:not(.hidden)',highlightOnCapture:false});
listeners.filter(item=>item.name==='click'&&item.capture===true).at(-2).handler({target:{closest:()=>control}});
offerSheetOpen=true;
listeners.filter(item=>item.name==='focus').at(-1).handler();
assert.equal(rowClasses.has('curation-focus-pulse'),false,'voltar de uma aba externa não anima por trás da ficha aberta');
assert.equal(stored.has('curadoria-list-focus:v1:external-popup'),true,'o foco fica pendente enquanto a ficha continua aberta');
offerSheetOpen=false;
listeners.filter(item=>item.name==='focus').at(-1).handler();
assert.ok(rowClasses.has('curation-focus-pulse'),'o retorno de foco restaura e anima a linha depois que a ficha fecha');
assert.ok(controlClasses.has('curation-focus-pulse'),'o retorno de foco também anima o controle acionado');
assert.equal(stored.has('curadoria-list-focus:v1:external-popup'),false,'o retorno de foco consome a posição salva');

rowClasses.clear();controlClasses.clear();control.dataset.curationFocus='images';
const returnVisibility=mountCurationListFocus('external-visibility',{highlightOnCapture:false});
listeners.filter(item=>item.name==='click'&&item.capture===true).at(-2).handler({target:{closest:()=>control}});
document.visibilityState='hidden';
listeners.filter(item=>item.name==='visibilitychange').at(-1).handler();
assert.equal(rowClasses.has('curation-focus-pulse'),false,'a saída da aba não dispara destaque enquanto a página está oculta');
document.visibilityState='visible';
listeners.filter(item=>item.name==='visibilitychange').at(-1).handler();
assert.ok(rowClasses.has('curation-focus-pulse'),'a visibilidade restaurada aplica o destaque pendente');
assert.ok(controlClasses.has('curation-focus-pulse'),'a visibilidade restaurada anima o controle acionado');
assert.equal(stored.has('curadoria-list-focus:v1:external-visibility'),false,'a restauração por visibilidade consome o foco');

rowClasses.clear();controlClasses.clear();control.dataset.curationFocus='trends';
const focusCount=listeners.filter(item=>item.name==='focus').length,visibilityCount=listeners.filter(item=>item.name==='visibilitychange').length;
const clickbankRoute=mountCurationListFocus('clickbank-route',{blockingSelector:'#offerSheet:not(.hidden), #sharedDecisionDialog[open]',highlightOnCapture:false,restoreOnWindowReturn:false,suppressPulseOnPageHide:true});
assert.equal(listeners.filter(item=>item.name==='focus').length,focusCount,'Top Offers CB não restaura nem pisca por foco genérico da janela');
assert.equal(listeners.filter(item=>item.name==='visibilitychange').length,visibilityCount,'Top Offers CB não restaura nem pisca por simples troca de aba');
listeners.filter(item=>item.name==='click'&&item.capture===true).at(-2).handler({target:{closest:()=>control}});
listeners.filter(item=>item.name==='pagehide').at(-1).handler();
assert.equal(JSON.parse(stored.get('curadoria-list-focus:v1:clickbank-route')).pulseOnRestore,false,'sair para outra tela mantém a posição, mas marca o retorno sem animação');
listeners.filter(item=>item.name==='pageshow').at(-1).handler();
assert.deepEqual(scrollPosition,[31,742],'o retorno de navegação ainda restaura a posição');
assert.equal(rowClasses.has('curation-focus-pulse'),false,'voltar de outra tela não pisca a linha');
assert.equal(controlClasses.has('curation-focus-pulse'),false,'voltar de outra tela não pisca o controle');
assert.equal(stored.has('curadoria-list-focus:v1:clickbank-route'),false,'a posição restaurada é consumida');

rowClasses.clear();controlClasses.clear();offerSheetOpen=true;
const clickbankClose=mountCurationListFocus('clickbank-close',{blockingSelector:'#offerSheet:not(.hidden), #sharedDecisionDialog[open]',highlightOnCapture:false,restoreOnWindowReturn:false,suppressPulseOnPageHide:true});
listeners.filter(item=>item.name==='click'&&item.capture===true).at(-2).handler({target:{closest:()=>control}});
assert.equal(clickbankClose.restore(),false,'a ficha aberta bloqueia o pulso');
listeners.filter(item=>item.name==='click'&&item.capture===true).at(-1).handler({target:{closest:selector=>selector.includes('#closeSheet')?{}:null}});
offerSheetOpen=false;
assert.equal(clickbankClose.restore(),true,'a ação explícita de retorno restaura o foco depois de esconder a ficha');
await new Promise(resolve=>setTimeout(resolve,0));
assert.ok(rowClasses.has('curation-focus-pulse'),'fechar explicitamente a ficha pisca a linha relacionada');
assert.ok(controlClasses.has('curation-focus-pulse'),'fechar explicitamente a ficha destaca o atalho usado');
assert.equal(stored.has('curadoria-list-focus:v1:clickbank-close'),false,'o foco é consumido ao fechar a ficha');
console.log('curation list focus ok');
