import assert from'node:assert/strict';
import{readFile}from'node:fs/promises';

const html=await readFile(new URL('../dist/curadoria/gerentes/index.html',import.meta.url),'utf8');
assert.ok(!html.includes('Como funciona a triagem automática'),'quadro da triagem automática ainda aparece');
assert.ok(!html.includes('data-col="signal"'),'coluna Sinal automático ainda aparece');
assert.ok(!html.includes('id="signalFilter"'),'filtro do sinal automático ficou órfão');
assert.ok(!html.includes('data-copy='),'ícone de copiar nome ainda aparece');
assert.ok(html.includes('id="visibilityFilter"'),'filtro de itens visíveis e ocultos ausente');
assert.ok(html.includes('data-toggle-product-visibility'),'ação de ocultar ou reexibir produto ausente');
assert.ok(html.includes("const HIDDEN_PRODUCTS_PREFS='radar-gerentes-itens-ocultos-v1'"),'preferência de itens ocultos não é persistida');
assert.ok(html.includes("visibility==='all'||(visibility==='hidden'?hidden:!hidden)"),'filtro de visibilidade não cobre visíveis, ocultos e todos');
assert.ok(html.includes('class="product-cell-layout"'),'ação de ocultar não está centralizada verticalmente na célula do produto');
assert.ok(html.includes("import * as TrendsUI from '../trends-ui.mjs'"),'Lista de Gerente não reutiliza o módulo visual de Trends');
assert.ok(html.includes('id="managerProductAgeActions"')&&html.includes('id="managerTrendsResults"'),'controles compartilhados de Trends ausentes na Lista de Gerente');
assert.ok(html.includes("sortKey='payout',sortDirection='desc'"),'Pagamento não inicia ordenado do maior para o menor');
assert.ok(html.includes("import * as DecisionUI from '../decision-ui.mjs'"),'Lista de Gerente não reutiliza o seletor compartilhado de decisão');
assert.ok(html.includes('data-open-manager-decision')&&html.includes('openManagerDecision'),'decisão manual não abre o seletor pela coluna');
assert.ok(html.includes('DecisionUI.buttonHtml')&&html.includes('DecisionUI.rowClass'),'badge e destaque da decisão não usam o componente compartilhado');
assert.ok(html.includes('trends-sheet.css?v=20260923-curation-list-typography'),'Lista de Gerente não carrega os estilos compartilhados atualizados');
const sharedStyles=await readFile(new URL('../dist/curadoria/trends-sheet.css',import.meta.url),'utf8');
assert.ok(sharedStyles.includes('nav[data-hub-sidebar-active="manager"]')&&sharedStyles.includes('#rows td *{font-weight:400!important}'),'valores das colunas da Lista de Gerente não estão em peso normal');
assert.ok(html.includes("import * as ListFocus from '../list-focus.mjs?v=1'")&&html.includes("mountCurationListFocus('manager'"),'Lista de Gerente não instala a preservação compartilhada de posição e linha');
assert.ok(html.includes('list-focus.mjs'),'helper de foco e rolagem não foi incluído no build');
assert.ok(html.includes('listFocus.restore()'),'Lista de Gerente não tenta restaurar o foco após atualizar a listagem');
const focusStyles=await readFile(new URL('../dist/curadoria/trends-sheet.css',import.meta.url),'utf8');
assert.ok(focusStyles.includes('curation-focus-row-pulse')&&focusStyles.includes('curation-focus-control-pulse'),'animação leve da linha e do controle ausente');
assert.ok(focusStyles.includes('.tablewrap td[data-col="countries"]{white-space:nowrap}'),'países da Lista de Gerente devem permanecer em uma linha');
console.log('manager list ui ok');
