import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import * as Images from '../dist/curadoria/image-search-domain.mjs';

const html=await readFile(new URL('../dist/curadoria/gerentes/index.html',import.meta.url),'utf8');
const css=await readFile(new URL('../dist/curadoria/trends-sheet.css',import.meta.url),'utf8');
const imagesUi=await readFile(new URL('../dist/curadoria/image-search-ui.mjs',import.meta.url),'utf8');
assert.equal(Images.imageSearchUrl('PodBloom','US'),'https://www.google.com/search?q=PodBloom&udm=2&gl=us&hl=en');
assert.equal(Images.imageSearchUrl('Produto teste','DE'),'https://www.google.com/search?q=Produto+teste&udm=2&gl=de&hl=de');
assert.equal(Images.imageSearchUrlExcluding('BareEarth Grounding Bed Sheets','US','weighted'),'https://www.google.com/search?q=BareEarth+Grounding+Bed+Sheets+-weighted&udm=2&gl=us&hl=en');
assert.equal(Images.imageSearchUrlExcluding('Produto teste','DE','produto concorrente'),'https://www.google.com/search?q=Produto+teste+-%22produto+concorrente%22&udm=2&gl=de&hl=de');
assert.equal(Images.imageSearchUrlExcluding('Produto teste','DE',['organic','produto concorrente','mat']),'https://www.google.com/search?q=Produto+teste+-organic+-%22produto+concorrente%22+-mat&udm=2&gl=de&hl=de');
assert.equal(Images.resultLabel('dominant'),'Dominante');
assert.equal(Images.progress([{country:'DE',status:'mixed',capturedAt:'2026-09-14T10:00:00Z'}],['DE','AT']).done,1);
assert.ok(html.includes('data-sort="images"'),'coluna Imagens ausente');
assert.ok(html.includes('id="imagesFilter"'),'filtro de imagens ausente');
assert.ok(html.includes('id="columnsPicker"'),'controle de colunas ausente');
assert.ok(html.includes("localStorage.setItem(COLUMN_PREFS"),'preferência de colunas não é persistida');
assert.ok(html.includes('.hidden-column{display:none!important}'),'ocultação de colunas ausente');
assert.ok(html.includes('Google Imagens'),'aba de validação visual ausente');
assert.ok(html.includes("import * as ImagesDomain from '../image-search-domain.mjs?v=3'"),'Lista de Gerente não invalida o cache da lógica de busca negativa');
assert.ok(html.includes('id="managerFinishImages"')&&html.includes('data-manager-image-search'),'ações de Google Imagens ausentes');
assert.ok(html.includes("import * as ImagesUI from '../image-search-ui.mjs'"),'Lista de Gerente não reutiliza os controles compartilhados de Imagens');
assert.ok(imagesUi.includes("'dominant'")&&imagesUi.includes("'mixed'"),'resultados Dominante e Mista ausentes do componente compartilhado');
assert.ok(imagesUi.includes("selectedValue === value ? 'selected' : ''"),'último resultado visual não volta destacado');
assert.ok(html.includes('candidatas a palavras-chave negativas'),'orientação de negativas ausente');
assert.ok(html.includes('data-manager-image-candidate-input'),'entrada de outros produtos ausente');
assert.ok(html.includes('negativeKeywordCandidates'),'candidatos a negativas não são persistidos');
assert.ok(html.includes('image-candidate-summary'),'resumo persistente das candidatas ausente');
assert.ok(html.includes("import * as KeywordCandidatesUI from '../keyword-candidates-ui.mjs?v=4'")&&html.includes('KeywordCandidatesUI.renderKeywordCandidates'),'Lista de Gerente não usa o componente compartilhado de candidatas');
assert.ok(html.includes("keywordCandidateMarkerHtml(hasCandidates?1:0,'negative')"),'Lista de Gerente não sinaliza candidatas negativas na lista de imagens');
assert.ok(html.includes('ImagesDomain.imageSearchUrlExcluding(term,country,candidate)'),'pesquisa da candidata negativa não usa o termo do produto com exclusão e país do cartão');
assert.ok(html.includes('data-manager-image-candidates'),'recipiente compartilhado das candidatas negativas ausente');
assert.ok(html.includes('data-manager-image-edit-candidates')&&html.includes('data-manager-image-save-candidates'),'edição de candidatas negativas não está disponível para qualquer sinal visual');
assert.ok(html.includes('negativeKeywordCandidates:imageCandidates({negativeKeywordCandidates})'),'candidatas devem ser salvas mesmo com resultado Dominante');
assert.ok(html.includes("if(current?.status!=='mixed')await saveManagerImageResult(selectedCountry,status,candidates)")&&html.includes('const productKey=activeKey,product=productIndex.get(productKey)'),'selecionar Mista precisa persistir a avaliação sem candidatas antes de abrir o editor opcional, usando a chave capturada antes do write');
assert.ok(css.includes('.image-candidate.saved'),'destaque das candidatas salvas ausente');
assert.ok(css.includes('#productSheet #managerImagesPanel button')&&css.includes('#productSheet #managerImagesTab{font-weight:400}'),'botões azuis da aba Google Imagens ainda estão em negrito');
assert.ok(css.includes('#offerSheet:has([data-panel="images"]:not(.hidden)) button,#productSheet:has(#managerImagesPanel:not(.hidden)) button{font-weight:400}'),'os demais botões da tela de Imagens devem usar peso normal');
assert.ok(css.includes('.image-candidate-list.image-candidate-collection{display:flex;align-items:center;gap:8px}')&&css.includes('.image-candidate-search-all{flex:0 0 auto;margin-left:auto;white-space:nowrap;font-weight:400}'),'busca coletiva das negativas deve ficar separada das palavras e alinhada à direita');
assert.ok(css.includes('.image-candidate{font-size:.9rem;font-weight:750}')&&css.includes('.image-candidate.saved{font-size:.9rem}'),'fonte ampliada das candidatas negativas ausente');
assert.ok(css.includes('.image-result-actions{display:grid;grid-template-columns:repeat(6,minmax(0,1fr))'),'resultados visuais não estão em uma linha');
assert.ok(css.includes('button.image-search-button,#managerFinishImages,#topFinishImages{display:inline-flex')&&css.includes('button.image-search-button[data-manager-image-search],button.image-search-button[data-top-image-search],.image-country-card button.image-search-button,#managerFinishImages,#topFinishImages{min-height:29px;padding:4px 12px;gap:6px;font-size:.9rem;line-height:1.2;')&&css.includes('button.image-search-button::after,#managerFinishImages::after,#topFinishImages::after{content:"→";font-weight:800}')&&css.includes('border-radius:10px'),'CTA azul arredondado, compartilhado e compacto de Google Imagens ausente');
assert.ok(css.includes('button.btn.image-result-action{min-height:34px;padding:5px 6px;font-size:.74rem;line-height:1.4}')&&css.includes('.image-candidate-summary-head b,.image-mixed-copy b{font-weight:400}'),'compactação dos resultados ou título normal das candidatas está ausente');
assert.ok(css.includes('overflow-x:auto'),'proteção responsiva contra sobreposição ausente');
assert.ok(html.includes("window.open(ImagesDomain.imageSearchUrl"),'atalho localizado do Google Imagens ausente');
assert.ok(html.includes("putAll('images'"),'histórico visual não é persistido');
console.log('manager images ui ok');
