import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';

const source=await readFile(new URL('../src/overview-domain.js',import.meta.url),'utf8');
const window={};
vm.runInNewContext(source,{window});
const derive=window.OverviewDomain.deriveTestBudget;
const sumObserved=window.OverviewDomain.sumObservedMetric;
const sumObservedProfit=window.OverviewDomain.sumObservedProfit;
const resolveD0=window.OverviewDomain.resolveD0Totals;
const resolveD1=window.OverviewDomain.resolveD1Totals;
const profitForTotals=window.OverviewDomain.profitForTotals;
const previousIsoDate=window.OverviewDomain.previousIsoDate;
const totalsColumns=window.OverviewDomain.totalsColumns;
const parseMinimumRoi=window.OverviewDomain.parseMinimumRoi;

assert.deepEqual(JSON.parse(JSON.stringify(derive({commission:75,commissionCurrency:'USD',exchangeRate:5.1,conversions:0,sales:0,investment:210}))),{limit:382.5,remaining:172.5,minimumRoi:0,salesCount:0});
assert.deepEqual(JSON.parse(JSON.stringify(derive({commission:60,commissionCurrency:'BRL',exchangeRate:5.1,conversions:0,sales:0,investment:0}))),{limit:60,remaining:60,minimumRoi:0,salesCount:0});
assert.deepEqual(JSON.parse(JSON.stringify(derive({commission:45.25,commissionCurrency:'USD',exchangeRate:5.1,conversions:0,sales:0,investment:250}))),{limit:230.78,remaining:-19.22,minimumRoi:0,salesCount:0});
assert.deepEqual(JSON.parse(JSON.stringify(derive({commission:75,commissionCurrency:'USD',exchangeRate:5.1,conversions:0,sales:0,investment:null}))),{limit:382.5,remaining:null,minimumRoi:0,salesCount:0});
assert.deepEqual(JSON.parse(JSON.stringify(derive({commission:75,commissionCurrency:'USD',exchangeRate:5.1,conversions:1,sales:0,investment:210}))),{limit:347.73,remaining:137.73,minimumRoi:10,salesCount:1},'uma venda aplica ROI mínimo de 10% e usa o valor por venda');
assert.deepEqual(JSON.parse(JSON.stringify(derive({commission:75,commissionCurrency:'USD',exchangeRate:5.1,conversions:0,sales:1,investment:400}))),{limit:347.73,remaining:-52.27,minimumRoi:10,salesCount:1},'venda provisória também ajusta o limite e mostra o excedente negativo');
assert.deepEqual(JSON.parse(JSON.stringify(derive({commission:75,commissionCurrency:'USD',exchangeRate:5.1,conversions:2,sales:0,investment:500}))),{limit:637.5,remaining:137.5,minimumRoi:20,salesCount:2},'duas vendas aplicam ROI mínimo de 20%');
assert.deepEqual(JSON.parse(JSON.stringify(derive({commission:75,commissionCurrency:'USD',exchangeRate:5.1,conversions:3,sales:0,investment:500}))),{limit:882.69,remaining:382.69,minimumRoi:30,salesCount:3},'três vendas aplicam ROI mínimo de 30%');
assert.deepEqual(JSON.parse(JSON.stringify(derive({commission:75,commissionCurrency:'USD',exchangeRate:5.1,conversions:5,sales:0,investment:500}))),{limit:1471.15,remaining:971.15,minimumRoi:30,salesCount:5},'três vendas ou mais mantêm o ROI mínimo de 30%');
assert.deepEqual(JSON.parse(JSON.stringify(derive({commission:75,commissionCurrency:'USD',exchangeRate:5.1,conversions:3,sales:0,revenue:300,investment:100,minimumRoiOverride:15}))),{limit:260.87,remaining:160.87,minimumRoi:15,salesCount:3},'percentual de ROI informado substitui o padrão por campanha');
assert.equal(parseMinimumRoi('12,5'),12.5,'entrada aceita decimal com vírgula sem exigir símbolo de porcentagem');
assert.equal(parseMinimumRoi('30'),30);
assert.throws(()=>parseMinimumRoi('30%'),/somente um número/,'entrada não deve conter símbolo de porcentagem');
assert.throws(()=>parseMinimumRoi('-1'),/somente um número/,'entrada negativa não é aceita');
assert.deepEqual(JSON.parse(JSON.stringify(derive({commission:75,commissionCurrency:'USD',exchangeRate:5.1,conversions:1,sales:1,revenue:436.75,investment:300}))),{limit:397.05,remaining:97.05,minimumRoi:10,salesCount:1},'usa a comissão real registrada em vez de estimar o faturamento pelo payout do título');
assert.deepEqual(JSON.parse(JSON.stringify(derive({commission:null,commissionCurrency:'EUR',exchangeRate:5.1,conversions:1,sales:0,revenue:120,investment:100}))),{limit:109.09,remaining:9.09,minimumRoi:10,salesCount:1},'receita efetiva em BRL permite calcular o limite mesmo sem payout conversível no título');
assert.deepEqual(JSON.parse(JSON.stringify(derive({commission:75,commissionCurrency:'USD',exchangeRate:5.1,conversions:null,sales:1,revenue:100,investment:50}))),{limit:90.91,remaining:40.91,minimumRoi:10,salesCount:1},'venda manual identificada permite calcular mesmo quando conversões MCC estão ausentes');
assert.equal(derive({commission:75,commissionCurrency:'USD',exchangeRate:5.1,conversions:null,sales:0,investment:210}),null,'ausência de informação não deve ser tratada como zero');
assert.equal(derive({commission:null,commissionCurrency:'USD',exchangeRate:5.1,conversions:0,sales:0,investment:210}),null,'sem comissão identificável deve permanecer o fallback atual');
assert.equal(derive({commission:75,commissionCurrency:'EUR',exchangeRate:5.1,conversions:0,sales:0,investment:210}),null,'moeda não suportada não deve ser convertida por suposição');
assert.equal(derive({commission:null,commissionCurrency:'USD',exchangeRate:5.1,conversions:1,sales:0,investment:210}),null,'sem receita observada ou payout conversível não se inventa limite');
assert.deepEqual(JSON.parse(JSON.stringify(sumObserved([{investment:125.5},{investment:0},{investment:null},{}],'investment'))),{value:125.5,observedCount:2,totalCount:4},'soma D0 mantém zero confirmado e não trata ausência como zero');
assert.deepEqual(JSON.parse(JSON.stringify(sumObserved([],'clicks'))),{value:null,observedCount:0,totalCount:0},'sem campanhas não deve exibir total D0 igual a zero');
assert.deepEqual(JSON.parse(JSON.stringify(sumObservedProfit([{investment:125.25,commission:100},{investment:20,commission:50},{investment:10,commission:null}]))),{value:4.75,observedCount:2,totalCount:3},'lucro do dia soma apenas campanhas com investimento e comissão observados');
assert.deepEqual(JSON.parse(JSON.stringify(sumObservedProfit([{investment:125.25,commission:100}]))),{value:-25.25,observedCount:1,totalCount:1},'lucro diário negativo permanece negativo');
assert.deepEqual(JSON.parse(JSON.stringify(sumObservedProfit([{investment:0,commission:0}]))),{value:0,observedCount:1,totalCount:1},'valores observados iguais a zero produzem lucro zero');
assert.deepEqual(JSON.parse(JSON.stringify(sumObservedProfit([]))),{value:null,observedCount:0,totalCount:0},'sem dados não inventar lucro diário igual a zero');
const pausedToday={data:'2026-09-28',celulas:{B:{value:39},C:{value:2},F:{value:0},O:{value:30.804},P:{value:0}}};
assert.deepEqual(JSON.parse(JSON.stringify(resolveD0({investment:null,impressions:null,clicks:null,conversions:null,commission:null},pausedToday,'2026-09-28'))),{investment:30.804,impressions:39,clicks:2,conversions:0,commission:0,date:'2026-09-28'},'campanha pausada hoje deve manter o D0 registrado no Diário');
assert.deepEqual(JSON.parse(JSON.stringify(resolveD0({investment:50,impressions:45,clicks:3,conversions:0,commission:0},pausedToday,'2026-09-28'))),{investment:50,impressions:45,clicks:3,conversions:0,commission:0,date:'2026-09-28'},'retrato direto mais recente prevalece sobre fallback diário');
assert.deepEqual(JSON.parse(JSON.stringify(resolveD0({investment:null,impressions:null,clicks:null},pausedToday,'2026-09-29'))),{investment:null,impressions:null,clicks:null,date:'2026-09-29'},'não reutilizar métricas de outra data como D0');
assert.deepEqual(JSON.parse(JSON.stringify(resolveD1({investment:42,impressions:120,clicks:12,conversions:1,commission:60,date:'2026-09-24'},{investment:30,impressions:100,clicks:10,conversions:0,commission:0}))),{investment:42,impressions:120,clicks:12,conversions:1,commission:60,date:'2026-09-24'},'dados diretos do retrato D−1 prevalecem sobre o diário');
assert.deepEqual(JSON.parse(JSON.stringify(resolveD1({investment:null,impressions:null,clicks:null,conversions:null,date:'2026-09-24'},{investment:30,impressions:100,clicks:10,conversions:0,commission:0}))),{investment:30,impressions:100,clicks:10,conversions:0,commission:0,date:'2026-09-24'},'valores D−1 ausentes podem ser completados pelo diário da mesma data');
assert.equal(previousIsoDate('2026-09-29'),'2026-09-28','quando D−1 não vier no manifesto, calcular o dia fechado anterior a D0');
assert.equal(previousIsoDate('2026-03-01'),'2026-02-28','cálculo de D−1 respeita virada de mês');
assert.equal(previousIsoDate('2026-02-29'),'','não normalizar silenciosamente uma data inválida');
assert.equal(profitForTotals({investment:125.25,commission:100}),-25.25,'lucro abaixo de zero deve ser preservado em reais');
assert.equal(profitForTotals({investment:100,commission:135.678}),35.68,'lucro positivo deve ser arredondado para centavos');
assert.equal(profitForTotals({investment:0,commission:0}),0,'zero confirmado continua sendo lucro zero');
assert.equal(profitForTotals({investment:null,commission:15}),null,'sem investimento observado não inventar lucro');
assert.equal(profitForTotals({investment:15,commission:null}),null,'sem comissão observada não inventar lucro');
const expectedD1=previousIsoDate('2026-09-29'),historyByDate={'2026-09-27':{investment:70,impressions:90,clicks:9,conversions:2,commission:100},[expectedD1]:{investment:45,impressions:120,clicks:8,conversions:1,commission:60}};
assert.deepEqual(JSON.parse(JSON.stringify(resolveD1({investment:null,impressions:null,clicks:null,conversions:null,date:expectedD1},historyByDate[expectedD1]))),{investment:45,impressions:120,clicks:8,conversions:1,commission:60,date:expectedD1},'D−1 sem retrato no manifesto recupera somente o dia anterior correspondente, sem usar datas mais antigas');
const d1Columns=totalsColumns('d1','D−1'),d0Columns=totalsColumns('d0','D zero');
assert.deepEqual(JSON.parse(JSON.stringify(d1Columns.map(([key])=>key))),JSON.parse(JSON.stringify(d0Columns.map(([key])=>key))),'D−1 e D0 preservam o mesmo formato e a mesma ordem de colunas');
assert.deepEqual(JSON.parse(JSON.stringify(d1Columns)),[['date','Data'],['campaign','Campanha'],['zeroDays','Dias sem impressões'],['current','Investimento D−1'],['imp','Impressões D−1'],['clicks','Cliques D−1'],['conv','Conversões D−1'],['roi','ROI atual'],['profit','Lucro D−1 (R$)'],['account','Conta'],['limit','Limite de teste'],['remaining','Valor restante'],['status','Situação']],'D−1 mantém a coluna de lucro após ROI e o mesmo contexto do formato D0');

console.log('overview-domain.test.mjs: limite de teste, somas D0, retrato D−1 e colunas por período validados');
