import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';

const source=await readFile(new URL('../src/overview-domain.js',import.meta.url),'utf8');
const window={};
vm.runInNewContext(source,{window});
const derive=window.OverviewDomain.deriveTestBudget;
const sumObserved=window.OverviewDomain.sumObservedMetric;
const sumObservedProfit=window.OverviewDomain.sumObservedProfit;
const resolveD0=window.OverviewDomain.resolveD0Totals;
const resolveD1=window.OverviewDomain.resolveD1Totals;
const profitForTotals=window.OverviewDomain.profitForTotals;
const previousIsoDate=window.OverviewDomain.previousIsoDate;
const authoritativeMccSnapshots=window.OverviewDomain.authoritativeMccSnapshots;
const pausedCampaignNamesOnDate=window.OverviewDomain.pausedCampaignNamesOnDate;
const replaceAuthoritativeDates=window.OverviewDomain.replaceAuthoritativeDates;
const totalsColumns=window.OverviewDomain.totalsColumns;
const parseMinimumRoi=window.OverviewDomain.parseMinimumRoi;
const parseTestLimit=window.OverviewDomain.parseTestLimit;
const testLimitForRoi=window.OverviewDomain.testLimitForRoi;
const roiForTestLimit=window.OverviewDomain.roiForTestLimit;

assert.deepEqual(JSON.parse(JSON.stringify(derive({commission:75,commissionCurrency:'USD',exchangeRate:5.1,conversions:0,sales:0,investment:210}))),{limit:382.5,remaining:172.5,minimumRoi:0,salesCount:0,revenue:382.5});
assert.deepEqual(JSON.parse(JSON.stringify(derive({commission:60,commissionCurrency:'BRL',exchangeRate:5.1,conversions:0,sales:0,investment:0}))),{limit:60,remaining:60,minimumRoi:0,salesCount:0,revenue:60});
assert.deepEqual(JSON.parse(JSON.stringify(derive({commission:45.25,commissionCurrency:'USD',exchangeRate:5.1,conversions:0,sales:0,investment:250}))),{limit:230.78,remaining:-19.22,minimumRoi:0,salesCount:0,revenue:230.77499999999998});
assert.deepEqual(JSON.parse(JSON.stringify(derive({commission:75,commissionCurrency:'USD',exchangeRate:5.1,conversions:0,sales:0,investment:null}))),{limit:382.5,remaining:null,minimumRoi:0,salesCount:0,revenue:382.5});
assert.deepEqual(JSON.parse(JSON.stringify(derive({commission:75,commissionCurrency:'USD',exchangeRate:5.1,conversions:1,sales:0,investment:210}))),{limit:347.73,remaining:137.73,minimumRoi:10,salesCount:1,revenue:382.5},'uma venda aplica ROI mínimo de 10% e usa o valor por venda');
assert.deepEqual(JSON.parse(JSON.stringify(derive({commission:75,commissionCurrency:'USD',exchangeRate:5.1,conversions:0,sales:1,investment:400}))),{limit:347.73,remaining:-52.27,minimumRoi:10,salesCount:1,revenue:382.5},'venda provisória também ajusta o limite e mostra o excedente negativo');
assert.deepEqual(JSON.parse(JSON.stringify(derive({commission:75,commissionCurrency:'USD',exchangeRate:5.1,conversions:2,sales:0,investment:500}))),{limit:637.5,remaining:137.5,minimumRoi:20,salesCount:2,revenue:765});
assert.deepEqual(JSON.parse(JSON.stringify(derive({commission:75,commissionCurrency:'USD',exchangeRate:5.1,conversions:3,sales:0,investment:500}))),{limit:882.69,remaining:382.69,minimumRoi:30,salesCount:3,revenue:1147.5},'três vendas aplicam ROI mínimo de 30%');
assert.deepEqual(JSON.parse(JSON.stringify(derive({commission:75,commissionCurrency:'USD',exchangeRate:5.1,conversions:5,sales:0,investment:500}))),{limit:1471.15,remaining:971.15,minimumRoi:30,salesCount:5,revenue:1912.5},'três vendas ou mais mantêm o ROI mínimo de 30%');
assert.deepEqual(JSON.parse(JSON.stringify(derive({commission:75,commissionCurrency:'USD',exchangeRate:5.1,conversions:3,sales:0,revenue:300,investment:100,minimumRoiOverride:15}))),{limit:260.87,remaining:160.87,minimumRoi:15,salesCount:3,revenue:300},'percentual de ROI informado substitui o padrão por campanha');
assert.deepEqual(JSON.parse(JSON.stringify(derive({commission:100,commissionCurrency:'BRL',conversions:1,revenue:100,investment:100,minimumRoiOverride:-3}))),{limit:103.09,remaining:3.09,minimumRoi:-3,salesCount:1,revenue:100},'ROI mínimo negativo permanece personalizado e aumenta o limite permitido');
assert.equal(parseMinimumRoi('12,5'),12.5,'entrada aceita decimal com vírgula sem exigir símbolo de porcentagem');
assert.equal(parseMinimumRoi('30'),30);
assert.equal(parseMinimumRoi('-3'),-3,'ROI negativo é permitido');
assert.equal(parseMinimumRoi('-99,5'),-99.5,'ROI negativo decimal com vírgula é permitido');
assert.throws(()=>parseMinimumRoi('30%'),/somente um número/,'entrada não deve conter símbolo de porcentagem');
assert.throws(()=>parseMinimumRoi('-100'),/maior que -100/,'-100% não pode ser usado pois impediria o cálculo do limite');
assert.throws(()=>parseMinimumRoi('-101'),/maior que -100/,'ROI abaixo de -100% é matematicamente inválido');
assert.equal(parseTestLimit('R$ 1.530,00'),1530,'limite aceita formatação monetária pt-BR');
assert.equal(parseTestLimit('1530.00'),1530,'limite também aceita decimal com ponto');
assert.equal(testLimitForRoi(1485.9,-3),1531.86,'ROI negativo maior que -100% aumenta o limite permitido');
assert.equal(roiForTestLimit(1485.9,'1.531,86'),-3,'editar o limite calcula o ROI correspondente');
assert.throws(()=>roiForTestLimit(0,100),/receita positiva/,'limite não pode inferir ROI sem receita positiva');
assert.throws(()=>parseTestLimit('0'),/maior que zero/,'limite editável precisa ser positivo');
assert.deepEqual(JSON.parse(JSON.stringify(derive({commission:75,commissionCurrency:'USD',exchangeRate:5.1,conversions:1,sales:1,revenue:436.75,investment:300}))),{limit:397.05,remaining:97.05,minimumRoi:10,salesCount:1,revenue:436.75},'usa a comissão real registrada em vez de estimar o faturamento pelo payout do título');
assert.deepEqual(JSON.parse(JSON.stringify(derive({commission:null,commissionCurrency:'EUR',exchangeRate:5.1,conversions:1,sales:0,revenue:120,investment:100}))),{limit:109.09,remaining:9.09,minimumRoi:10,salesCount:1,revenue:120},'receita efetiva em BRL permite calcular o limite mesmo sem payout conversível no título');
assert.deepEqual(JSON.parse(JSON.stringify(derive({commission:75,commissionCurrency:'USD',exchangeRate:5.1,conversions:null,sales:1,revenue:100,investment:50}))),{limit:90.91,remaining:40.91,minimumRoi:10,salesCount:1,revenue:100},'venda manual identificada permite calcular mesmo quando conversões MCC estão ausentes');
assert.equal(derive({commission:75,commissionCurrency:'USD',exchangeRate:5.1,conversions:null,sales:0,investment:210}),null,'ausência de informação não deve ser tratada como zero');
assert.equal(derive({commission:null,commissionCurrency:'USD',exchangeRate:5.1,conversions:0,sales:0,investment:210}),null,'sem comissão identificável deve permanecer o fallback atual');
assert.equal(derive({commission:75,commissionCurrency:'EUR',exchangeRate:5.1,conversions:0,sales:0,investment:210}),null,'moeda não suportada não deve ser convertida por suposição');
assert.equal(derive({commission:null,commissionCurrency:'USD',exchangeRate:5.1,conversions:1,sales:0,investment:210}),null,'sem receita observada ou payout conversível não se inventa limite');
assert.deepEqual(JSON.parse(JSON.stringify(sumObserved([{investment:125.5},{investment:0},{investment:null},{}],'investment'))),{value:125.5,observedCount:2,totalCount:4},'soma D0 mantém zero confirmado e não trata ausência como zero');
assert.deepEqual(JSON.parse(JSON.stringify(sumObserved([],'clicks'))),{value:null,observedCount:0,totalCount:0},'sem campanhas não deve exibir total D0 igual a zero');
assert.deepEqual(JSON.parse(JSON.stringify(sumObservedProfit([{investment:125.25,commission:100},{investment:20,commission:50},{investment:10,commission:null}]))),{value:4.75,observedCount:2,totalCount:3},'lucro do dia soma apenas campanhas com investimento e comissão observados');
assert.deepEqual(JSON.parse(JSON.stringify(sumObservedProfit([{investment:125.25,commission:100}]))),{value:-25.25,observedCount:1,totalCount:1},'lucro diário negativo permanece negativo');
assert.deepEqual(JSON.parse(JSON.stringify(sumObservedProfit([{investment:0,commission:0}]))),{value:0,observedCount:1,totalCount:1},'valores observados iguais a zero produzem lucro zero');
assert.deepEqual(JSON.parse(JSON.stringify(sumObservedProfit([]))),{value:null,observedCount:0,totalCount:0},'sem dados não inventar lucro diário igual a zero');
const pausedToday={data:'2026-09-28',celulas:{B:{value:39},C:{value:2},F:{value:0},O:{value:30.804},P:{value:0}}};
assert.deepEqual(JSON.parse(JSON.stringify(resolveD0({investment:null,impressions:null,clicks:null,conversions:null,commission:null},pausedToday,'2026-09-28'))),{investment:30.804,impressions:39,clicks:2,conversions:0,commission:0,date:'2026-09-28'},'campanha pausada hoje deve manter o D0 registrado no Diário');
assert.deepEqual(JSON.parse(JSON.stringify(resolveD0({investment:50,impressions:45,clicks:3,conversions:0,commission:0},pausedToday,'2026-09-28'))),{investment:50,impressions:45,clicks:3,conversions:0,commission:0,date:'2026-09-28'},'retrato direto mais recente prevalece sobre fallback diário');
assert.deepEqual(JSON.parse(JSON.stringify(resolveD0({investment:25,impressions:12,clicks:1,conversions:0,commission:0},pausedToday,'2026-09-28'))),{investment:25,impressions:12,clicks:1,conversions:0,commission:0,date:'2026-09-28'},'retrato MCC mais recente prevalece sobre diário mesmo quando seus números são menores');
assert.deepEqual(JSON.parse(JSON.stringify(resolveD0({present:false,investment:113,impressions:113,clicks:10,conversions:1,commission:85},pausedToday,'2026-09-28'))),{investment:null,impressions:null,clicks:null,conversions:null,commission:null,date:'2026-09-28'},'campanha ausente na captura D0 não pode ressuscitar métricas antigas do Diário');
const authoritative=authoritativeMccSnapshots({separacao_temporal:{D_menos_1:{datas_detectadas:['01/10/2026']},D_zero:{datas_detectadas:['02/10/2026']}},campanhas:[{nome_campanha_exato:'Captured',metricas_D_menos_1:{presente:true,moeda:{valor:'USD'},custo_total:{valor:8},impressoes:{valor:80},cliques_google:{valor:8},conversoes:{valor:2},valor_conversao:{valor:20}},metricas_D_zero:{presente:true,moeda:{valor:'BRL'},custo_total:{valor:25},impressoes:{valor:50},cliques_google:{valor:5},conversoes:{valor:1},valor_conversao:{valor:30}},custo_D_zero:{presente:true,moeda:{valor:'BRL'},custo_total_destino_totais_coluna_M:{valor:20}}},{nome_campanha_exato:'Missing',metricas_D_zero:{presente:false,data:{valor:'2026-10-02'}}}]},{exchangeRate:5});
assert.deepEqual(Array.from(authoritative.dates),['2026-10-01','2026-10-02']);
assert.deepEqual(JSON.parse(JSON.stringify(authoritative.rows.map(({campaignName,period,date,present,investment,clicks,commission})=>({campaignName,period,date,present,investment,clicks,commission})))),[
  {campaignName:'Captured',period:'d1',date:'2026-10-01',present:true,investment:40,clicks:8,commission:100},
  {campaignName:'Captured',period:'d0',date:'2026-10-02',present:true,investment:20,clicks:5,commission:30},
  {campaignName:'Missing',period:'d0',date:'2026-10-02',present:false,investment:null,clicks:null,commission:null},
],'normaliza as duas capturas em BRL, usa o custo dedicado D0 e preserva uma marca explícita de ausência');
const retainedD0=authoritativeMccSnapshots({separacao_temporal:{D_zero:{datas_detectadas:['2026-10-02']}},campanhas:[{nome_campanha_exato:'Retained',captura_D_zero_escopo:'active_only',captura_D_zero_completa:true,metricas_D_zero:{presente:false,retida_no_dia:true,data:{valor:'2026-10-02'},moeda:{valor:'BRL'},custo_total:{valor:12},impressoes:{valor:80},cliques_google:{valor:8},valor_conversao:{valor:24}}}]});
assert.deepEqual(JSON.parse(JSON.stringify(retainedD0.rows[0])),{campaignName:'Retained',period:'d0',date:'2026-10-02',present:true,observed:false,retained:true,captureScope:'active_only',captureComplete:true,investment:12,impressions:80,clicks:8,conversions:null,commission:24},'retained D0 remains eligible for daily totals while its latest capture still marks it absent');
const rebased=replaceAuthoritativeDates({investment:300,impressions:400,clicks:40,conversions:4,commission:400,observed:{investment:2,impressions:2,clicks:2,conversions:2,commission:2},byDate:{'2026-10-01':{investment:100,impressions:100,clicks:10,conversions:1,commission:100},'2026-10-02':{investment:200,impressions:300,clicks:30,conversions:3,commission:300}}},authoritative.rows.filter(row=>row.campaignName==='Captured'),authoritative.dates);
assert.deepEqual(JSON.parse(JSON.stringify(rebased)),{investment:60,impressions:130,clicks:13,conversions:3,commission:130,observed:{investment:2,impressions:2,clicks:2,conversions:2,commission:2}},'consolidado substitui D0/D−1 antigos mesmo se atuais forem menores; dias fora do recorte ficam intactos');
const excluded=replaceAuthoritativeDates({investment:30,impressions:30,clicks:3,conversions:1,commission:10,observed:{investment:1,impressions:1,clicks:1,conversions:1,commission:1},byDate:{'2026-10-02':{investment:30,impressions:30,clicks:3,conversions:1,commission:10}}},[],['2026-10-02']);
assert.deepEqual(JSON.parse(JSON.stringify(excluded)),{investment:null,impressions:null,clicks:null,conversions:null,commission:null,observed:{investment:0,impressions:0,clicks:0,conversions:0,commission:0}},'campanha ausente na captura elimina apenas a contribuição obsoleta da data capturada');
assert.deepEqual(JSON.parse(JSON.stringify(resolveD0({investment:null,impressions:null,clicks:null},pausedToday,'2026-09-29'))),{investment:null,impressions:null,clicks:null,date:'2026-09-29'},'não reutilizar métricas de outra data como D0');
assert.deepEqual(JSON.parse(JSON.stringify(resolveD1({investment:42,impressions:120,clicks:12,conversions:1,commission:60,date:'2026-09-24'},{investment:30,impressions:100,clicks:10,conversions:0,commission:0}))),{investment:42,impressions:120,clicks:12,conversions:1,commission:60,date:'2026-09-24'},'dados diretos do retrato D−1 prevalecem sobre o diário');
assert.deepEqual(JSON.parse(JSON.stringify(resolveD1({investment:20,impressions:40,clicks:4,conversions:0,commission:0,date:'2026-09-24'},{investment:30,impressions:100,clicks:10,conversions:0,commission:0}))),{investment:20,impressions:40,clicks:4,conversions:0,commission:0,date:'2026-09-24'},'retrato MCC D−1 prevalece sobre diário mesmo quando os números são menores');
assert.deepEqual(JSON.parse(JSON.stringify(resolveD1({investment:null,impressions:null,clicks:null,conversions:null,date:'2026-09-24'},{investment:30,impressions:100,clicks:10,conversions:0,commission:0}))),{investment:30,impressions:100,clicks:10,conversions:0,commission:0,date:'2026-09-24'},'valores D−1 ausentes podem ser completados pelo diário da mesma data');
assert.equal(previousIsoDate('2026-09-29'),'2026-09-28','quando D−1 não vier no manifesto, calcular o dia fechado anterior a D0');
assert.equal(previousIsoDate('2026-03-01'),'2026-02-28','cálculo de D−1 respeita virada de mês');
assert.equal(previousIsoDate('2026-02-29'),'','não normalizar silenciosamente uma data inválida');
assert.equal(profitForTotals({investment:125.25,commission:100}),-25.25,'lucro abaixo de zero deve ser preservado em reais');
assert.equal(profitForTotals({investment:100,commission:135.678}),35.68,'lucro positivo deve ser arredondado para centavos');
assert.equal(profitForTotals({investment:0,commission:0}),0,'zero confirmado continua sendo lucro zero');
assert.equal(profitForTotals({investment:null,commission:15}),null,'sem investimento observado não inventar lucro');
assert.equal(profitForTotals({investment:15,commission:null}),null,'sem comissão observada não inventar lucro');
const expectedD1=previousIsoDate('2026-09-29'),historyByDate={'2026-09-27':{investment:70,impressions:90,clicks:9,conversions:2,commission:100},[expectedD1]:{investment:45,impressions:120,clicks:8,conversions:1,commission:60}};
assert.deepEqual(JSON.parse(JSON.stringify(resolveD1({investment:null,impressions:null,clicks:null,conversions:null,date:expectedD1},historyByDate[expectedD1]))),{investment:45,impressions:120,clicks:8,conversions:1,commission:60,date:expectedD1},'D−1 sem retrato no manifesto recupera somente o dia anterior correspondente, sem usar datas mais antigas');
const d1Columns=totalsColumns('d1','D−1'),d0Columns=totalsColumns('d0','D zero');
assert.deepEqual(JSON.parse(JSON.stringify(d1Columns.map(([key])=>key))),JSON.parse(JSON.stringify(d0Columns.map(([key])=>key))),'D−1 e D0 preservam o mesmo formato e a mesma ordem de colunas');
assert.deepEqual(JSON.parse(JSON.stringify(d1Columns)),[['date','Data'],['campaign','Campanha'],['zeroDays','Dias sem impressões'],['current','Investimento D−1'],['imp','Impressões D−1'],['clicks','Cliques D−1'],['conv','Conversões D−1'],['roi','ROI atual'],['saleRoiFirst','ROI 1ª venda'],['saleRoiSecond','ROI 2ª venda'],['profit','Lucro D−1 (R$)'],['account','Conta'],['limit','Limite de teste'],['remaining','Valor restante'],['status','Situação']],'D−1 mantém ROIs históricos de venda e lucro, com o mesmo formato de D0');

assert.deepEqual(Array.from(pausedCampaignNamesOnDate([{status:'pausada',pausada_em:'2026-10-06',nome_mcc:'Zulu'},{status:'pausada',pausada_em:'2026-10-05',nome_mcc:'Ontem'},{status:'ativa',pausada_em:'2026-10-06',nome_mcc:'Ativa'},{status:'pausada',pausada_em:'2026-10-06',nome_mcc:'Akemi'}],'2026-10-06')),['Akemi','Zulu'],'somente pausadas hoje, ordenadas pelo nome');
assert.deepEqual(Array.from(pausedCampaignNamesOnDate([{status:'pausada',pausada_em:'2026-10-06',nome_mcc:'Hoje'}],'invalid')),[],'data inválida não corresponde a pausas');
console.log('overview-domain.test.mjs: limite de teste, somas D0, retrato D−1 e colunas por período validados');
