import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const source = await readFile(new URL('../src/product-diary/domain.js', import.meta.url), 'utf8') + '\n' + await readFile(new URL('../src/product-diary/view.js', import.meta.url), 'utf8');
const diaryStyles = await readFile(new URL('../src/product-diary/product-diary.css', import.meta.url), 'utf8');
const panelSource = await readFile(new URL('../src/index.template.html', import.meta.url), 'utf8');
const dateFunction = source.match(/^\s*function productDiaryRowDate\(row\)\{[^\r\n]+\}/m)?.[0];
const salesFunction = source.match(/^\s*function productDiaryHasSales\(row,provisionalSaleDates\)\{[^\r\n]+\}/m)?.[0];
const countFunction = source.match(/^\s*function productDiaryManualSaleCount\(row,manualSalesByDate\)\{[^\r\n]+\}/m)?.[0];
const rowsFunction = source.match(/^\s*function productDiaryRowsWithManualSales\(rows,manualSalesByDate\)\{[^\r\n]+\}/m)?.[0];
const cutoffFunction = source.match(/^\s*function productDiaryRowsThroughDate\(rows,cutoff\)\{[^\r\n]+\}/m)?.[0];
const cellFunction = source.match(/^\s*function formatProductDiaryCell\(col,row,manualSalesByDate(?:,pauseConfirmedAt)?\)\{[^\r\n]+\}/m)?.[0];
assert.ok(dateFunction && salesFunction && countFunction && rowsFunction && cutoffFunction && cellFunction, 'helpers de data/venda do Diário de campanha ausentes');

const { productDiaryRowDate, productDiaryHasSales, productDiaryManualSaleCount, productDiaryRowsWithManualSales, productDiaryRowsThroughDate, formatProductDiaryCell } = new Function('excelDate','formatProductCell', `${dateFunction}\n${salesFunction}\n${countFunction}\n${rowsFunction}\n${cutoffFunction}\n${cellFunction}\nreturn {productDiaryRowDate,productDiaryHasSales,productDiaryManualSaleCount,productDiaryRowsWithManualSales,productDiaryRowsThroughDate,formatProductDiaryCell};`)(serial => new Date(Math.round((Number(serial) - 25569) * 86400000)), (_col,cell) => cell?.value == null ? '—' : String(cell.value));
const serialFor = iso => Date.parse(`${iso}T00:00:00Z`) / 86400000 + 25569;

assert.equal(productDiaryHasSales({ cells: { F: { value: 2 } } }, new Set()), true, 'conversões oficiais positivas devem destacar o dia');
assert.equal(productDiaryHasSales({ cells: { F: { value: 0 }, A: { value: serialFor('2026-09-24') } } }, new Set(['2026-09-24'])), true, 'venda manual pendente deve destacar a data correspondente');
assert.equal(productDiaryHasSales({ cells: { F: { value: 0 }, A: { value: serialFor('2026-09-24') } } }, new Set()), false, 'zero de conversões sem venda pendente não deve destacar a linha');
assert.equal(productDiaryHasSales({ date: '2026-09-24', cells: { F: { value: null } } }, new Set(['2026-09-23'])), false, 'venda pendente de outra data não deve destacar a linha');
const manualSalesByDate = new Map([['2026-09-24', { pendingConversions:1 }]]);
const diaryRows = productDiaryRowsWithManualSales([{ cells:{A:{value:serialFor('2026-09-23')},F:{value:0}} }], manualSalesByDate);
assert.equal(diaryRows.length, 2, 'data com venda manual sem linha MCC deve ganhar uma linha virtual no Diário');
assert.equal(diaryRows[1].date, '2026-09-24');
assert.equal(diaryRows[1].cells.A.text, '24/09/2026');
assert.equal(diaryRows[1].cells.F, undefined, 'linha virtual não inventa conversão oficial');
assert.equal(productDiaryManualSaleCount(diaryRows[1], manualSalesByDate), 1, 'venda manual pendente deve ser identificada separadamente da conversão MCC');
assert.equal(formatProductDiaryCell('F',{date:'2026-09-24',cells:{F:{value:0}}},manualSalesByDate), '<span>0</span><small class="product-manual-sale-note">+1 manual · provisória</small>', 'venda manual aparece separada sem somar conversões à métrica MCC');
assert.equal(formatProductDiaryCell('Q',{date:'2026-09-24',cells:{Q:{value:'Pausada'}}},new Map(),'2026-09-24'), '<span>Pausada</span><small class="product-pause-note">Campanha pausada na data 24/09/2026</small>', 'a confirmação fica visível em Observações na data correspondente');
assert.deepEqual(productDiaryRowsThroughDate([{date:'2026-09-24'},{date:'2026-09-25'}],'2026-09-24').map(productDiaryRowDate),['2026-09-24'],'o corte do Diário inclui o dia da confirmação');
assert.equal(productDiaryManualSaleCount(diaryRows[0], manualSalesByDate), 0, 'venda manual não deve aparecer em outra data');
assert.equal(productDiaryRowsWithManualSales(diaryRows, manualSalesByDate).length, 2, 'a mesma data manual não deve duplicar linha já existente');

assert.match(panelSource, /product:\{[^\n]*bodyClass:'product-diary-mode'/, 'o modo do Diário deve ser ativado somente pela navegação para a tela');
assert.match(diaryStyles, /#productView \.product-table th,#productView \.product-table td:not\(\.empty\)\{padding-block:6px\}/, 'somente a tabela diária usa linhas cerca de 20% mais compactas, sem reduzir a fonte nem o estado vazio');
assert.match(diaryStyles, /#productView \.product-table td\.num\{text-align:center;vertical-align:middle\}/, 'dados de Data até Comissão ficam centralizados em todos os diários, sem depender da campanha');
assert.ok(source.includes("col==='Q'?'hub-edit-host product-observation-cell':'num'"), 'centralização alcança as 16 colunas de dados, deixando Observações no componente próprio');
assert.match(diaryStyles, /\.product-table th\{[^}]*text-align:center/, 'cabeçalhos das colunas de dados permanecem centralizados');
assert.match(diaryStyles, /\.product-table th:last-child\{[^}]*text-align:left/, 'Observações conserva cabeçalho à esquerda');
assert.match(panelSource, /product-diary\/product-diary\.css\?v=13/, 'a nova versão do CSS deve invalidar o cache dos diários');
assert.match(panelSource, /product-diary\/view\.js\?v=10/, 'o renderizador compartilhado atualizado deve invalidar o cache');
assert.ok(diaryStyles.includes('#productView .product-table td.product-zero-value{color:color-mix(in srgb,var(--hub-primary-text) 50%,var(--hub-table-row-bg))}'), 'zeros observados usam 50% da cor padrão misturada ao fundo base, sem alterar a opacidade de notas');
assert.match(diaryStyles, /body\.product-diary-mode\{overflow-y:auto\}/, 'a página deve rolar para alcançar o quadro de ROI abaixo do Diário');
assert.match(diaryStyles, /body\.product-diary-mode \.main\{[^}]*min-height:100dvh;overflow:visible/, 'no desktop, o conteúdo do Diário pode crescer além do viewport');
assert.match(diaryStyles, /body\.product-diary-mode #productTableWrap\{[^}]*max-height:var\(--product-diary-table-max-height,[^}]*overflow:auto/, 'a tabela diária tem limite responsivo e rolagem interna nos dois eixos');
assert.doesNotMatch(diaryStyles, /#productTableWrap\{[^}]*max-height:none|#productTableWrap\{[^}]*overflow-y:hidden/, 'o desktop não pode desativar o limite nem a rolagem interna');
const template=await readFile(new URL('../src/product-diary/template.html',import.meta.url),'utf8');
assert.match(template,/id="productTableWrap"[^>]*tabindex="0"[^>]*role="region"[^>]*aria-labelledby="productPanelTitle"/, 'a região rolável deve ser acessível por teclado e ter nome');
console.log('product diary sales highlight ok');
