import assert from'node:assert/strict';
import{readFile}from'node:fs/promises';

const html=await readFile(new URL('../dist/index.html',import.meta.url),'utf8');
assert.ok(html.includes('id="testedActiveProductsCount"'),'indicador de produtos com campanhas ativas ausente');
assert.ok(html.includes('products.filter(product=>product.active).length'),'indicador não conta produtos ativos consolidados');
assert.ok(html.includes('id="testedColumnsPicker"')&&html.includes('id="testedColumnsMenu"'),'seletor de colunas de Produtos Testados ausente');
assert.ok(html.includes("TESTED_COLUMNS_PREF='painel-produtos-testados-colunas-v1'"),'preferência de colunas não possui chave persistente');
assert.ok(html.includes('localStorage.setItem(TESTED_COLUMNS_PREF'),'preferência de colunas não é salva');
assert.ok(html.includes('data-tested-col="related"')&&html.includes('data-tested-col="actions"'),'colunas da tabela não estão identificadas para ocultação');
assert.ok(html.includes('data-tested-col="revenue"')&&html.includes('data-tested-sort="revenue"'),'coluna Total faturado ausente ou não ordenável');
assert.ok(html.includes('.catalog-table th:not(:first-child),.catalog-table td:not(:first-child){text-align:center}')&&html.includes('.catalog-table th:not(:first-child) .sort-btn{text-align:center}'),'alinhamento centralizado das demais colunas de Produtos Testados ausente');
assert.ok(html.includes('class="tag tested-status ${p.active?\'active\':\'historical\'}"'),'estado ativo/histórico da tabela não recebe classe visual específica');
assert.ok(html.includes('.catalog-table .tested-status.active{align-items:center;')&&html.includes('.catalog-table .tested-status.active::before')&&html.includes('background:var(--green)'),'indicador de produto ativo não está verde e alinhado verticalmente');
assert.ok(html.includes("['revenue','Total faturado']"),'coluna Total faturado não está disponível no seletor de colunas');
assert.ok(html.includes("const rawBilled=row.celulas?.P?.value,billed=Number(rawBilled)")&&html.includes('group.totalBilled+=billed;group.billedObserved=true'),'valor de conversão da coluna P não é agregado por produto preservando ausência versus zero');
assert.ok(html.includes('group.totalBilled+=adjustment.commissionAdjustment;group.billedObserved=true'),'vendas provisórias pendentes não são incluídas no total faturado');
assert.ok(html.includes('totalBilled:x.billedObserved?x.totalBilled:null'),'produto sem faturamento registrado não é distinguido de faturamento zero');
assert.ok(html.includes('fmtMoney(p.totalBilled)'),'total faturado não é exibido como moeda');
assert.ok(html.includes("key==='revenue'?product.totalBilled"),'ordenação numérica por Total faturado ausente');
assert.ok(html.includes("classList.toggle('hidden-column',hiddenTestedColumns.has(cell.dataset.testedCol))"),'visibilidade das colunas não é reaplicada');
assert.ok(html.includes('numericFamilies')&&html.includes('variants.add(name.toLocaleLowerCase'),'famílias de variantes numéricas não são identificadas');
assert.ok(html.includes("?.size||0)>1?baseName:originalName"),'produto isolado com número final pode ser alterado indevidamente');
assert.ok(html.includes('data-tested-sort="product"')&&html.includes('data-tested-sort="campaigns"'),'cabeçalhos ordenáveis ausentes');
assert.ok(html.includes("testedSortKey='status',testedSortDir='desc'"),'ordenação padrão por situação ativa primeiro ausente');
assert.ok(html.includes("key==='status'?(product.active?1:0)"),'ordenação de situação não prioriza produtos ativos');
assert.ok(html.includes('function sortTestedProducts(products)')&&html.includes('function bindTestedSorting()'),'comportamento de ordenação de Produtos Testados ausente');
assert.ok(html.includes('campaignDates[0]||normalizeTestedDate(catalog.datas_inicio[x.key])||first'),'data do produto não prioriza a primeira campanha agrupada');
assert.ok(html.includes("return date>reference?`2025-${match[2]}-${match[3]}`:date"),'datas futuras da listagem não são corrigidas para 2025');
console.log('tested products ui ok');
