import assert from'node:assert/strict';
import{readFile}from'node:fs/promises';

const html=await readFile(new URL('../dist/index.html',import.meta.url),'utf8')+await readFile(new URL('../dist/tested-products/view.js',import.meta.url),'utf8')+await readFile(new URL('../dist/tested-products/domain.js',import.meta.url),'utf8')+await readFile(new URL('../dist/tested-products/tested-products.css',import.meta.url),'utf8');
assert.equal((html.match(/id="downloadCatalog"/g)||[]).length,0,'exportação independente do catálogo não deve mais ser apresentada');
assert.ok(html.includes('Baixar backup completo JSON'),'o botão único de backup completo está ausente');
assert.ok(html.includes('payload.catalogo_produtos=ProductCatalog.normalize(state.productCatalog)'),'backup completo não inclui os ajustes do catálogo');
assert.ok(html.includes('tested-products/view.js?v=8')&&html.includes('tested-products/domain.js?v=8'),'módulos de Produtos Testados não invalidam o cache das correções');
assert.ok(html.includes('tested-products/tested-products.css?v=5')&&html.includes('.catalog-edit,.catalog-remove{border:1px solid var(--line);border-radius:8px;padding:7px 10px;font-weight:500}')&&html.includes('.catalog-table tbody td{padding-block:5px}'),'ações devem usar peso normal e as linhas devem ficar cerca de 20% mais compactas');
assert.ok(html.includes('id="testedEditDialog"')&&html.includes('id="testedEditForm"')&&html.includes('Restaurar todos os calculados'),'formulário do sistema e restauração de valores ausentes');
assert.ok(html.includes('ProductCatalog.setTestedAdjustments')&&html.includes('await persistProductCatalog(next)'),'edição manual não está restrita ao catálogo');
assert.ok(html.includes('ajustes_testados')&&html.includes('Ajuste manual nesta lista'),'ajustes manuais precisam de persistência e indicação visível');
assert.ok(html.includes('id="testedActiveProductsCount"'),'indicador de produtos com campanhas ativas ausente');
assert.ok(html.includes('id="testedSearch" class="search hub-search-filter" type="search" placeholder="Buscar produto ou campanha"'),'busca compartilhada de produto/campanha ausente em Produtos Testados');
assert.ok(!html.includes('O backup completo JSON no topo reúne campanhas'),'texto explicativo sinalizado ainda aparece em Produtos Testados');
assert.ok(html.includes('products.filter(product=>product.active).length'),'indicador não conta produtos ativos consolidados');
assert.ok(html.includes('id="testedColumnsPicker"')&&html.includes('id="testedColumnsMenu"'),'seletor de colunas de Produtos Testados ausente');
assert.ok(html.includes('class="catalog-actions hub-table-toolbar-actions"')&&html.includes('id="testedColumnsPicker" class="tested-columns-picker"><summary class="btn">Colunas</summary>')&&html.includes('id="catalogInput"')&&html.includes('id="purgeProducts" class="btn danger hidden"')&&html.includes('id="restoreProducts" class="btn hidden"'),'ações do canto do painel Produtos Testados optam pelo padrão global de botões de tabela');
assert.ok(html.includes("TESTED_COLUMNS_PREF='painel-produtos-testados-colunas-v1'"),'preferência de colunas não possui chave persistente');
assert.ok(html.includes('preferences.setItem(TESTED_COLUMNS_PREF'),'preferência de colunas não é salva');
assert.ok(html.includes('data-tested-col="related"')&&html.includes('data-tested-col="actions"'),'colunas da tabela não estão identificadas para ocultação');
assert.ok(html.includes('data-tested-col="revenue"')&&html.includes('data-tested-sort="revenue"'),'coluna Total faturado ausente ou não ordenável');
assert.ok(html.includes('data-tested-col="profit"')&&html.includes('data-tested-sort="profit"'),'coluna Lucro total ausente ou não ordenável');
assert.ok(html.includes("Number.isFinite(p.totalProfit)&&p.totalProfit<0?' negative':''")&&html.includes('.negative{color:var(--red)}'),'lucro total negativo deve ficar vermelho apenas quando estiver abaixo de zero');
assert.ok(html.includes('data-tested-col="sales"')&&html.includes('data-tested-sort="sales"')&&html.includes('>Vendas<span'),'coluna Vendas ausente ou não ordenável');
assert.ok(html.includes('.catalog-table th:not(:first-child),.catalog-table td:not(:first-child){text-align:center}')&&html.includes('.catalog-table th:not(:first-child) .sort-btn{text-align:center}'),'alinhamento centralizado das demais colunas de Produtos Testados ausente');
assert.ok(html.includes('class="tag tested-status ${p.active?\'active\':\'historical\'}"'),'estado ativo/histórico da tabela não recebe classe visual específica');
assert.ok(html.includes('.catalog-table .tested-status.active{align-items:center;')&&html.includes('.catalog-table .tested-status.active::before')&&html.includes('background:var(--green)'),'indicador de produto ativo não está verde e alinhado verticalmente');
assert.ok(html.includes("['revenue','Total faturado']"),'coluna Total faturado não está disponível no seletor de colunas');
assert.ok(html.includes("['profit','Lucro total']")&&html.includes("key==='profit'?product.totalProfit"),'coluna Lucro total não está disponível no seletor ou na ordenação');
assert.ok(html.includes("['sales','Vendas']")&&html.includes("key==='sales'?product.salesCount"),'coluna Vendas não está disponível no seletor ou na ordenação');
assert.ok(html.includes("legacyMetric?.state==='observed'")&&html.includes("metrics?.commission_brl")&&html.includes('addBilled(group,legacyCommission,campaignProfitEvidence)'),'comissão observada do resumo histórico não entra no total faturado');
assert.ok(html.includes('date>legacyEndDate')&&html.includes("String(row.data||'')>legacyEndDate")&&html.includes('if(afterLegacy&&!isAuthoritative)addBilled(group,rawBilled,campaignProfitEvidence)'),'diário e ajustes não são limitados ao período posterior ao resumo histórico');
assert.ok(html.includes('else addBilled(group,adjustment?.commissionAdjustment,campaignProfitEvidence)'),'vendas provisórias sem resumo histórico não são incluídas no total faturado');
assert.ok(html.includes("title=\"Usa a comissão observada na planilha histórica por campanha; acrescenta somente os dados diários e vendas provisórias posteriores à data final desse resumo."),'a regra de consolidação não está explicada no cabeçalho');
assert.ok(html.includes('totalBilled=x.billedObserved?x.totalBilled:null'),'produto sem faturamento registrado não é distinguido de faturamento zero');
assert.ok(html.includes('totalInvestment=x.investmentObserved?x.totalInvestment:null')&&html.includes('totalProfit:!x.profitComplete||totalBilled==null||totalInvestment==null?null:totalBilled-totalInvestment'),'lucro não preserva ausência de dados ou não é derivado dos totais agregados');
assert.ok(html.includes('fmtMoney(p.totalBilled)'),'total faturado não é exibido como moeda');
assert.ok(html.includes('fmtMoney(p.totalProfit)'),'lucro total não é exibido como moeda');
assert.ok(html.includes('metricSnapshots:context.latestSnapshots.rows')&&html.includes('authoritativeDates:context.latestSnapshots.dates')&&html.includes('OverviewDomain.authoritativeMccSnapshots(manifest,{exchangeRate:state.rate})'),'adaptador deve fornecer a captura atual compartilhada em BRL, sem duplicar datas do Diário');
assert.ok(html.includes('fmtNum(p.salesCount,Number.isInteger(p.salesCount)?0:2)'),'quantidade de vendas não é exibida com precisão apropriada');
assert.ok(html.includes("key==='revenue'?product.totalBilled"),'ordenação numérica por Total faturado ausente');
assert.ok(html.includes("key==='profit'?product.totalProfit"),'ordenação numérica por Lucro total ausente');
assert.ok(html.includes("classList.toggle('hidden-column',hiddenTestedColumns.has(cell.dataset.testedCol))"),'visibilidade das colunas não é reaplicada');
assert.ok(html.includes('numericFamilies')&&html.includes('variants.add(family.variant)'),'famílias de variantes de campanha não são identificadas pelo número da iteração');
assert.ok(html.includes('(?:\\s*[ºª°])?(?:\\s*\\[[^\\]]+\\])?'),'variações ordinais com sufixo entre colchetes não são reconhecidas em Produtos Testados');
assert.ok(html.includes("?.size||0)>1?baseName:originalName"),'produto isolado com número final pode ser alterado indevidamente');
assert.ok(html.includes('data-tested-sort="product"')&&html.includes('data-tested-sort="campaigns"'),'cabeçalhos ordenáveis ausentes');
assert.ok(html.includes("testedSortKey='status',testedSortDir='desc'"),'ordenação padrão por situação ativa primeiro ausente');
assert.ok(html.includes("key==='status'?(product.active?1:0)"),'ordenação de situação não prioriza produtos ativos');
assert.ok(html.includes('domain.sortProducts(products,testedSortKey,testedSortDir)')&&html.includes('function bindTestedSorting()'),'comportamento de ordenação de Produtos Testados ausente');
assert.ok(html.includes('campaignDates[0]||normalizeTestedDate(catalog.datas_inicio[x.key])||first'),'data do produto não prioriza a primeira campanha agrupada');
assert.ok(html.includes("return date>reference?`2025-${match[2]}-${match[3]}`:date"),'datas futuras da listagem não são corrigidas para 2025');
console.log('tested products ui ok');
