import assert from'node:assert/strict';
import{readFile}from'node:fs/promises';
import vm from'node:vm';

const html=await readFile(new URL('../dist/curadoria/top-performance/index.html',import.meta.url),'utf8'),storage=await readFile(new URL('../dist/curadoria/top-performance/top-performance-storage.mjs',import.meta.url),'utf8');
assert.ok(html.includes('E-commerce GM'));
assert.ok(html.includes('./top-performance-storage.mjs'));
assert.ok(storage.includes("DB_NAME='radar-top-performance'"));
assert.ok(storage.includes("snapshots:'collection_offer_snapshots'"));
assert.ok(html.includes('id="pasteArea"')&&html.includes('id="confirmImport"'));
assert.ok(html.includes('id="movementFilter"'));
assert.ok(html.includes('<option value="best">Best</option>')&&html.includes('badge-best'),'badges Best e Top não estão separados na interface');
assert.ok(html.includes('data-panel="trends"')&&html.includes('data-panel="images"')&&html.includes('data-panel="history"'));
assert.ok(html.includes('id="columnMenu"'));
assert.ok(!html.includes('data-col="image"'));
assert.ok(html.includes('data-col="trends"')&&html.includes('data-col="images"'));
assert.ok(html.includes('data-open-top-trends')&&html.includes('data-open-top-images'));
assert.ok(html.includes("columns=['id','product','trends','images'"));
assert.ok(html.includes('id="visibilityFilter"')&&html.includes('data-toggle-offer-visibility'));
assert.ok(html.includes("const HIDDEN_OFFERS_PREFS='top-performance-itens-ocultos-v1'"));
assert.ok(html.includes("visibility==='all'||(visibility==='hidden'?hidden:!hidden)"));
assert.equal((html.match(/class="sort-btn"/g)||[]).length,13);
assert.ok(html.includes('automaticSignalBadge')&&html.includes('data-sort="automaticSignal"'),'coluna de sinal automático não é montada ou ordenável');
assert.ok(html.includes('data-sort="trends"')&&html.includes('data-sort="images"')&&html.includes('data-sort="lastSeen"'));
assert.ok(html.includes("import * as TrendsUI from '../trends-ui.mjs'"));
assert.ok(html.includes('id="topProductAgeActions"')&&html.includes('id="topTrendsResults"'));
assert.ok(html.includes('Candidatas à palavra-chave'));
assert.ok(html.includes('id="topTrendsKeywordInput"')&&html.includes('Digite uma ideia e pressione Enter'));
assert.ok(html.includes("if(event.key==='Enter'){event.preventDefault();addTopTrendKeywordCandidate(item)}"));
assert.ok(html.includes('keywordCandidates:candidates')&&html.includes('Storage.put(Storage.STORES.trends,stored)'));
assert.ok(html.includes("import * as KeywordCandidatesUI from '../keyword-candidates-ui.mjs?v=4'")&&html.includes('KeywordCandidatesUI.renderKeywordCandidates'),'E-commerce GM não reutiliza o componente compartilhado de candidatas');
assert.ok(html.includes("keywordCandidateMarkerHtml(count,'positive')")&&html.includes("keywordCandidateMarkerHtml(hasCandidates?1:0,'negative')"),'E-commerce GM não sinaliza candidatas de Trends e negativas de Imagens');
assert.ok(html.includes("onSearch:term=>{const tab=window.open(Trends.exploreUrl(term),'google-trends-top-performance')"),'a pesquisa da candidata não usa seu próprio termo no Trends');
assert.ok(html.includes('Trends.exploreUrl(term),\'google-trends-top-performance\''),'pesquisa de candidata na E-commerce GM não reutiliza o padrão de URL do Trends');
assert.ok(html.includes('loadTrends(item,{preserveDraft:true})'));
assert.ok(html.includes('id="topManualCountryCode"')&&html.includes('Adicionar país pelo código (ex.: BR)'),'E-commerce GM não oferece inclusão manual do país pelo Google Trends');
assert.ok(html.includes('Domain.offerCountryCodes(item)')&&html.includes('baseLoadTrendsWithManualCountries({...item,countriesVisible:codes},options)'),'países manuais não são combinados com os explícitos no Google Trends');
assert.ok(html.includes('Storage.put(Storage.STORES.offers,updated)')&&html.includes('baseRenderImagesWithManualCountries({...item,countriesVisible:Domain.offerCountryCodes(item)})'),'país manual salvo não cria seção própria no Google Imagens');
assert.ok(html.includes('imagesBadge=function(item){return baseImagesBadgeWithManualCountries({...item,countriesVisible:Domain.offerCountryCodes(item)})}')&&html.includes('imagesRank=function(item){return baseImagesRankWithManualCountries({...item,countriesVisible:Domain.offerCountryCodes(item)})}'),'países manuais não entram no total/progresso nem na ordenação do badge de Imagens');
assert.ok(html.includes('className=\'manual-country-label\''),'origem manual do país não fica identificável na seção do Google Imagens');
assert.ok(html.includes('closeOffer({restoreFocus:false});await refresh();listFocus.restore()'));
assert.ok(html.includes("import * as ImagesUI from '../image-search-ui.mjs'"));
assert.ok(html.includes('id="topFinishImages"')&&html.includes('id="topImagesMessage"'));
assert.ok(html.includes('data-top-image-search'),'ação de pesquisa de Google Imagens ausente');
assert.ok(html.includes("import * as Images from '../image-search-domain.mjs?v=3'"),'E-commerce GM não invalida o cache da lógica de busca negativa');
assert.ok(html.includes('ImagesUI.renderImageResultButtons'));
assert.ok(html.includes('image-candidate-summary')&&html.includes('data-top-image-candidate-input'));
assert.ok(html.includes('data-top-image-candidates')&&html.includes('Images.imageSearchUrlExcluding(term,country,candidate)'),'candidatas a negativas não usam o termo do produto com exclusão nem preservam o país');
assert.ok(html.includes('data-top-image-edit-candidates')&&html.includes('data-top-image-save-candidates'),'edição de candidatas negativas não está disponível para qualquer sinal visual');
assert.ok(html.includes('negativeKeywordCandidates:imageCandidates({negativeKeywordCandidates:candidates})'),'candidatas devem ser salvas mesmo com resultado Dominante');
assert.ok(html.includes("const term=$('#imagesTerm').value.trim()||item.productName,tab=window.open(Images.imageSearchUrlExcluding(term,country,candidate)"),'busca de negativa da E-commerce GM não parte do termo da oferta');
assert.ok(html.includes('badge-summary')&&html.includes("labels.join(' · ')")&&html.includes("tone=b.new?'new':b.top?'top':b.brandOk?'brand':''"),'badges não foram consolidados em uma pílula compacta');
assert.ok(html.includes("sortKey='payout',sortDirection='desc'"),'Payout não inicia ordenado do maior para o menor');
assert.ok(html.includes("sortKey='payout';sortDirection='desc';render()"),'Limpar filtros não restaura a ordenação padrão por Payout');
assert.ok(html.includes("import * as DecisionUI from '../decision-ui.mjs'"),'E-commerce GM não reutiliza o seletor compartilhado de decisão');
assert.ok(html.includes('data-open-top-decision')&&html.includes('openTopDecision'),'decisão da E-commerce GM não abre o seletor pela coluna');
assert.ok(html.includes('DecisionUI.buttonHtml')&&html.includes('DecisionUI.rowClass'),'badge e destaque da decisão não usam o componente compartilhado');
assert.ok(html.includes('trends-sheet.css?v=20260923-curation-list-typography'),'E-commerce GM não carrega os estilos compartilhados atualizados');
assert.ok(html.includes("import * as ListFocus from '../list-focus.mjs?v=1'")&&html.includes("mountCurationListFocus('top-performance'"),'E-commerce GM não instala a preservação compartilhada de posição e linha');
assert.ok(html.includes("highlightOnCapture:false")&&html.includes("function closeOffer({restoreFocus=true}={}){$('#offerSheet').classList.add('hidden');document.body.style.overflow='';if(restoreFocus)listFocus.restore()}"),'E-commerce GM deve animar apenas após fechar a ficha e retornar à lista');
assert.match(html,/async function saveTrend\(status\)\{[\s\S]*?closeOffer\(\{restoreFocus:false\}\);await refresh\(\);listFocus\.restore\(\);toast\(/,'salvar Trends precisa restaurar a linha depois que refresh recriar as linhas da lista');
assert.ok(html.includes('renderWithGlimpse=render;render=function(){renderWithGlimpse();listFocus.restore()}'),'E-commerce GM não restaura o foco após renderizar a lista carregada');
const focusModule=await readFile(new URL('../dist/curadoria/list-focus.mjs',import.meta.url),'utf8'),focusStyles=await readFile(new URL('../dist/curadoria/trends-sheet.css',import.meta.url),'utf8');
assert.ok(focusModule.includes('pageshow')&&focusModule.includes('window.scrollTo'),'E-commerce GM não restaura a rolagem ao retornar da tela Glimpse');
assert.ok(focusStyles.includes('curation-focus-row-pulse')&&focusStyles.includes('curation-focus-control-pulse'),'animação leve da linha e do controle ausente');
assert.ok(focusStyles.includes('.trends-keyword-candidate')&&focusStyles.includes('background:#102d24')&&focusStyles.includes('color:#83e5bb'),'destaque verde para candidatas do Google Trends ausente');
assert.ok(focusStyles.includes('.trends-keyword-candidate{font-size:.9rem}')&&focusStyles.includes('.image-candidate{font-size:.9rem;font-weight:750}')&&focusStyles.includes('.image-candidate.saved{font-size:.9rem}'),'fonte ampliada das candidatas às palavras-chave ausente');
assert.ok(focusStyles.includes('.keyword-candidate-marker-dot{color:inherit}')&&focusStyles.includes('.keyword-candidate-marker.positive .keyword-candidate-marker-exclamation{color:#34d399}')&&focusStyles.includes('.keyword-candidate-marker.negative .keyword-candidate-marker-exclamation{color:#fb7185}'),'ponto deve herdar a cor do texto e a exclamação deve manter a cor da polaridade');
assert.ok(focusStyles.includes('.keyword-candidate-marker{display:inline-flex;gap:.16em;margin-left:.3em;font-weight:400'),'marcador não tem espaçamento entre o texto e o ponto ou mantém negrito');
assert.ok(focusStyles.includes('nav[data-hub-sidebar-active="manager"]')&&focusStyles.includes('nav[data-hub-sidebar-active="ecommerce"]')&&focusStyles.includes('#rows td *{font-weight:400!important}'),'texto de todas as colunas das duas listagens deve usar peso normal');
assert.ok(focusStyles.includes('button.image-search-button,#managerFinishImages,#topFinishImages{display:inline-flex')&&focusStyles.includes('button.image-search-button[data-manager-image-search],button.image-search-button[data-top-image-search],.image-country-card button.image-search-button,#managerFinishImages,#topFinishImages{min-height:29px;padding:4px 12px;gap:6px;font-size:.9rem;line-height:1.2;')&&focusStyles.includes('button.image-search-button::after,#managerFinishImages::after,#topFinishImages::after{content:"→";font-weight:800}')&&focusStyles.includes('border-radius:10px'),'CTA azul arredondado, compartilhado e compacto de Google Imagens ausente');
assert.ok(focusStyles.includes('button.btn.image-result-action{min-height:34px;padding:5px 6px;font-size:.74rem;line-height:1.4}')&&focusStyles.includes('.image-candidate-summary-head b,.image-mixed-copy b{font-weight:400}'),'compactação dos resultados ou título normal das candidatas está ausente');
assert.ok(focusStyles.includes('#offerSheet [data-panel="images"] button')&&focusStyles.includes('#offerSheet .tabs button[data-tab="images"]'),'botões da aba Google Imagens ainda estão em negrito');
assert.ok(focusStyles.includes('#offerSheet:has([data-panel="images"]:not(.hidden)) button,#productSheet:has(#managerImagesPanel:not(.hidden)) button{font-weight:400}'),'os demais botões da tela de Imagens devem usar peso normal');
assert.ok(focusStyles.includes('.tablewrap td[data-col="countries"]{white-space:nowrap}'),'países do E-commerce GM devem permanecer em uma linha');
assert.ok(focusStyles.includes('.tablewrap tbody tr.offer-row td[data-col="id"]')&&focusStyles.includes('.tablewrap tbody tr.offer-row td[data-col="product"] b{font-weight:400}'),'valores de ID e Produto do E-commerce GM devem usar peso normal');
assert.ok(focusStyles.includes('.manual-country-entry')&&focusStyles.includes('.manual-country-label')&&focusStyles.includes('.trends-country-action.manual:not(.selected)'),'layout responsivo e identificação visual dos países manuais ausentes');
assert.ok(html.includes('gurumedia-offer-links-ui.mjs?view=top'),'atalho para a oferta GuruMedia não está incluído no E-commerce GM');
for(const match of html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g))if(match[1].trim()&&!match[0].includes('type="module"'))new vm.Script(match[1]);
console.log('top performance ui ok');
