import assert from'node:assert/strict';
import{readFile}from'node:fs/promises';
import vm from'node:vm';

const html=await readFile(new URL('../dist/curadoria/top-performance/index.html',import.meta.url),'utf8'),storage=await readFile(new URL('../dist/curadoria/top-performance/top-performance-storage.mjs',import.meta.url),'utf8');
assert.ok(html.includes('Top Performance'));
assert.ok(html.includes('./top-performance-storage.mjs'));
assert.ok(storage.includes("DB_NAME='radar-top-performance'"));
assert.ok(storage.includes("snapshots:'collection_offer_snapshots'"));
assert.ok(html.includes('id="pasteArea"')&&html.includes('id="confirmImport"'));
assert.ok(html.includes('id="movementFilter"'));
assert.ok(html.includes('data-panel="trends"')&&html.includes('data-panel="images"')&&html.includes('data-panel="history"'));
assert.ok(html.includes('id="columnMenu"'));
assert.ok(!html.includes('data-col="image"'));
assert.ok(html.includes('data-col="trends"')&&html.includes('data-col="images"'));
assert.ok(html.includes('data-open-top-trends')&&html.includes('data-open-top-images'));
assert.ok(html.includes("columns=['id','product','trends','images'"));
assert.ok(html.includes('id="visibilityFilter"')&&html.includes('data-toggle-offer-visibility'));
assert.ok(html.includes("const HIDDEN_OFFERS_PREFS='top-performance-itens-ocultos-v1'"));
assert.ok(html.includes("visibility==='all'||(visibility==='hidden'?hidden:!hidden)"));
assert.equal((html.match(/class="sort-btn"/g)||[]).length,12);
assert.ok(html.includes('data-sort="trends"')&&html.includes('data-sort="images"')&&html.includes('data-sort="lastSeen"'));
assert.ok(html.includes("import * as TrendsUI from '../trends-ui.mjs'"));
assert.ok(html.includes('id="topProductAgeActions"')&&html.includes('id="topTrendsResults"'));
assert.ok(html.includes('loadTrends(item,{preserveDraft:true})'));
assert.ok(html.includes('closeOffer();await refresh()'));
assert.ok(html.includes("import * as ImagesUI from '../image-search-ui.mjs'"));
assert.ok(html.includes('id="topFinishImages"')&&html.includes('id="topImagesMessage"'));
assert.ok(html.includes('ImagesUI.renderImageResultButtons'));
assert.ok(html.includes('image-candidate-summary')&&html.includes('data-top-image-candidate-input'));
assert.ok(html.includes('badge-summary')&&html.includes("labels.join(' · ')")&&html.includes("tone=b.new?'new':b.top?'top':b.brandOk?'brand':''"),'badges não foram consolidados em uma pílula compacta');
assert.ok(html.includes("sortKey='payout',sortDirection='desc'"),'Payout não inicia ordenado do maior para o menor');
assert.ok(html.includes("sortKey='payout';sortDirection='desc';render()"),'Limpar filtros não restaura a ordenação padrão por Payout');
for(const match of html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g))if(match[1].trim()&&!match[0].includes('type="module"'))new vm.Script(match[1]);
console.log('top performance ui ok');
