import * as Domain from '../glimpse-domain.mjs';
import * as Storage from '../glimpse-storage.mjs';
import * as CurationObservability from '../curation-observability.mjs?v=2';

const $=selector=>document.querySelector(selector),safe=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const params=new URLSearchParams(location.search),context={productKey:params.get('productKey')||'',productName:params.get('product')||'',offerIds:(params.get('offerIds')||'').split(',').filter(Boolean),scope:params.get('scope')||'',offerKey:params.get('offerKey')||''},requestedOrigin=params.get('origin'),origin=['top','hot-offers-ms','clickbank-top-offers','smartadv-offers'].includes(requestedOrigin)?requestedOrigin:'manager',embedded=params.get('embedded')==='1';
if(embedded){document.documentElement.classList.add('embedded');document.querySelector('.hero')?.classList.add('hidden')}
const returnUrl=origin==='top'?'../top-performance/':origin==='hot-offers-ms'?'../hot-offers-ms/':origin==='clickbank-top-offers'?'../clickbank-top-offers/':origin==='smartadv-offers'?'../smartadv-offers/':'../gerentes/';let draft=null,history=[];
const pendingSaves=new Map();
let lastReportedHeight=0;
function reportEmbeddedHeight(){if(!embedded||window.parent===window)return;const height=Math.ceil(document.documentElement.scrollHeight);if(height>0&&height!==lastReportedHeight){lastReportedHeight=height;window.parent.postMessage({type:'hub-glimpse-resize',height},location.origin)}}
function scheduleEmbeddedHeight(){requestAnimationFrame(reportEmbeddedHeight)}
if(embedded){const page=document.querySelector('.page');if(page&&'ResizeObserver'in window){const observer=new ResizeObserver(scheduleEmbeddedHeight);observer.observe(page)}window.addEventListener('load',scheduleEmbeddedHeight,{once:true});window.addEventListener('resize',scheduleEmbeddedHeight)}
function dateTime(value){const date=new Date(value);return Number.isNaN(date.getTime())?'—':new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(date)}
function relevanceLabel(value){return{high:'Alta',medium:'Média',low:'Baixa',unclear:'Indefinida'}[value]||'Indefinida'}
function percent(value){return value===null||value===undefined?'—':`${Math.round(value*100)}%`}
async function goBack(){if(draft&&pendingSaves.has(draft.analysisId)){const saved=await pendingSaves.get(draft.analysisId);if(!saved)return}if(embedded&&window.parent!==window){window.parent.postMessage({type:'hub-glimpse-close'},location.origin);return}location.href=returnUrl}
async function finishAnalysis(){if(draft&&!await saveAnalysis(draft))return;await goBack()}
function indicatorRows(analysis){const p=analysis.parsed,i=analysis.indicators,c=analysis.classified,legacyCommercial=[...c.peopleAlsoSearch,...c.relatedQueries].filter(item=>['BOFU / Reviews','Compra / Preço','Confiança / Objeção'].includes(item.category)).length,commercial=i.intent?.commercialCount??legacyCommercial,uniqueTerms=i.intent?.uniqueTermCount;return[
  ['Volume mensal',p.volume.display||'Não detectado',p.volume.operator==='<'?'Limite superior informado; não é exatamente 500.':'Estimativa informada pelo Glimpse.'],
  ['Movimento recente',p.movement.percent===null?'Não detectado':Domain.movementValueLabel(p.movement.percent),p.movement.periodLabel||p.movement.period||'Janela não detectada'],
  ['Intenção comercial',commercial,commercial?`${uniqueTerms??'—'} termos únicos avaliados; duplicatas entre fontes não aumentam a contagem.`:'Nenhum termo comercial foi classificado nas fontes capturadas.'],
  ['Contaminação semântica',Domain.contaminationLabel(i.contamination.level),i.contamination.ratio===null?'Sem material suficiente':`${percent(i.contamination.ratio)} dos itens sem relação clara`],
  ['Cobertura dos dados',Domain.coverageLabel(i.coverage.level),`${i.coverage.availableSources} de ${i.coverage.totalSources} fontes disponíveis`],
  ['Países/regiões',p.regions.reportedTotal??p.regions.capturedCount,`${p.regions.capturedCount} capturada(s); índice relativo, não volume`],
  ['Concentração geográfica',i.geography.level==='concentrated'?'Concentrada':i.geography.level==='distributed'?'Distribuída':i.geography.level==='limited'?'Limitada':'Não detectada','A região 100 não é automaticamente o melhor mercado comercial.'],
  ['People Also Search',p.peopleAlsoSearch.capturedCount,p.peopleAlsoSearch.pagination?`Página ${p.peopleAlsoSearch.pagination.currentPage} de ${p.peopleAlsoSearch.pagination.totalPages}; somente itens visíveis foram capturados.`:Domain.stateLabel(p.peopleAlsoSearch.state)],
  ['Related Trends',p.relatedTrends.capturedCount,p.relatedTrends.reportedTotalMin?`${p.relatedTrends.reportedTotalMin}${p.relatedTrends.reportedTotalIsApproximate?'+':''} informadas; ${p.relatedTrends.capturedCount} capturadas.`:Domain.stateLabel(p.relatedTrends.state)],
  ['Queries emergentes',p.relatedQueries.capturedCount,Domain.stateLabel(p.relatedQueries.state)],['Tópicos emergentes',p.relatedTopics.capturedCount,Domain.stateLabel(p.relatedTopics.state)],
  ['Sazonalidade',Domain.stateLabel(p.seasonality.state),'Ausência de dados não é sinal negativo.'],['Channel Breakdown',Domain.stateLabel(p.channel.state),'Disponibilidade declarada pela interface.']
].map(row=>`<tr><td><b>${safe(row[0])}</b></td><td>${safe(row[1])}</td><td>${safe(row[2])}</td></tr>`).join('')}
function renderClassifications(analysis){const entries=Object.entries(analysis.indicators.categoryCounts),total=entries.reduce((sum,[,count])=>sum+count,0);$('#intentions').innerHTML=entries.length?entries.sort((a,b)=>b[1]-a[1]).map(([label,count])=>`<div class="stack-row"><div><b>${safe(label)}</b><div class="bar"><i style="width:${total?count/total*100:0}%"></i></div></div><span>${count} · ${total?Math.round(count/total*100):0}%</span></div>`).join(''):'<p class="muted">Nenhuma query capturada.</p>'}
function renderPeopleAlsoSearch(section){const panel=$('#peopleAlsoSearchPanel'),items=Array.isArray(section?.items)?section.items:[],detected=Boolean(section&&section.state!=='not_detected');panel.classList.toggle('hidden',!detected);if(!detected)return;$('#peopleAlsoSearchCount').textContent=items.length?`${items.length} ${items.length===1?'termo':'termos'}`:'Sem termos';$('#peopleAlsoSearchItems').innerHTML=items.length?items.map(item=>`<span class="people-also-search-item">${safe(item)}</span>`).join(''):`<p class="people-also-search-empty">${safe(section?.state==='available'?'A seção foi encontrada, mas nenhum termo estava visível na colagem.':Domain.stateLabel(section?.state))}</p>`}
function renderV2Details(analysis){const panel=$('#v2Details'),isV2=analysis.analyzerVersion===Domain.ANALYZER_VERSION;if(!isV2){panel.classList.add('hidden');return}panel.classList.remove('hidden');$('#confidenceValue').textContent=Domain.confidenceLabel(analysis.confidence?.level);$('#confidenceReasons').textContent=(analysis.confidence?.reasons||[]).join(' ');$('#alertRows').innerHTML=analysis.alerts?.length?analysis.alerts.map(alert=>`<li class="alert-${safe(alert.severity)}"><b>${safe(alert.message)}</b><small>${safe(alert.id)}</small></li>`).join(''):'<li class="no-alerts">Nenhum alerta relevante.</li>';const dimensions=analysis.dimensions||{};const rows=[['Demanda',Domain.dimensionLabel(dimensions.demand?.level),dimensions.demand?.display||'Volume observado por mês'],['Movimento',Domain.dimensionLabel(dimensions.movement?.direction),dimensions.movement?.value===null||dimensions.movement?.value===undefined?'Sem variação associada a uma janela':`${Domain.movementValueLabel(dimensions.movement.value)} · ${dimensions.movement.periodLabel||Domain.dimensionLabel(dimensions.movement.period)}`],['Intenção',Domain.dimensionLabel(dimensions.intention?.level),`${dimensions.intention?.commercialCount||0} termos comerciais únicos de ${dimensions.intention?.uniqueTermCount||0}`],['Relevância',Domain.dimensionLabel(dimensions.relevance?.level),dimensions.relevance?.ratio===null?`${dimensions.relevance?.totalCount||0} itens avaliados`:`${Math.round(dimensions.relevance.ratio*100)}% de contaminação · ${dimensions.relevance?.contaminatedCount||0}/${dimensions.relevance?.totalCount||0}`],['Geografia',Domain.dimensionLabel(dimensions.geography?.level),`${dimensions.geography?.capturedCount||0} capturadas${dimensions.geography?.reportedCount!==null&&dimensions.geography?.reportedCount!==undefined?` de ${dimensions.geography.reportedCount} informadas`:''} · ${Domain.dimensionLabel(dimensions.geography?.coverage)}`]];$('#dimensionRows').innerHTML=rows.map(([name,value,note])=>`<tr><td><b>${safe(name)}</b></td><td>${safe(value)}</td><td>${safe(note)}</td></tr>`).join('')}
function emergingRows(items){return items.length?items.map(item=>`<div class="stack-row"><div><b>${safe(item.text)}</b><small>${safe(item.status||'Sem crescimento informado')}</small></div><span class="relevance-${safe(item.relevance)}">${safe(relevanceLabel(item.relevance))}</span></div>`).join(''):'<p class="muted">Nenhum item disponível.</p>'}
function render(analysis){
  draft=analysis;const p=analysis.parsed,i=analysis.indicators;$('#results').classList.remove('hidden');
  $('#volumeCard').textContent=p.volume.display||'—';const movementCard=$('#movementCard');movementCard.textContent=p.movement.percent===null?'—':Domain.movementValueLabel(p.movement.percent);movementCard.dataset.direction=p.movement.percent===null?'unknown':p.movement.percent>0?'positive':p.movement.percent<0?'negative':'neutral';$('#movementPeriod').textContent=p.movement.period||'período não detectado';
  $('#geographyCard').textContent=(p.regions.reportedTotal??p.regions.capturedCount)||'—';$('#geographyNote').textContent=p.regions.reportedTotal?`${p.regions.capturedCount} capturadas · ${p.regions.reportedTotal} informadas`:`${p.regions.capturedCount} capturadas`;$('#coverageCard').textContent=Domain.coverageLabel(i.coverage.level);
  $('#signalValue').textContent=Domain.signalLabel(analysis.signal.level);$('#signalValue').dataset.level=analysis.signal.level;$('#signalReasons').textContent=(analysis.signal.reasons||[]).join(' ');$('#signalReasons').classList.toggle('hidden',!analysis.signal.reasons?.length);$('#operationalReading').textContent=analysis.operationalReading;$('#indicatorRows').innerHTML=indicatorRows(analysis);renderPeopleAlsoSearch(p.peopleAlsoSearch);renderClassifications(analysis);renderV2Details(analysis);
  $('#regionRows').innerHTML=p.regions.items.length?p.regions.items.map(item=>`<tr><td>${item.rank}</td><td>${safe(item.region)}</td><td>${safe(`${item.interestOperator==='<'?'<':''}${item.interestIndex}`)}</td></tr>`).join(''):'<tr><td colspan="3">Nenhuma região capturada.</td></tr>';
  $('#regionsSummary').textContent=`${p.regions.capturedCount} regiões capturadas${p.regions.reportedTotal?` · ${p.regions.reportedTotal} informadas pela interface`:''}. Índice relativo de interesse — não representa buscas.`;$('#topicRows').innerHTML=emergingRows(analysis.classified.relatedTopics);$('#queryRows').innerHTML=emergingRows(analysis.classified.relatedQueries);
  $('#trendRows').innerHTML=analysis.classified.relatedTrends.length?analysis.classified.relatedTrends.map(item=>`<span class="tag ${item.relevance==='low'||item.relevance==='unclear'?'low':''}" title="Relevância ${safe(relevanceLabel(item.relevance))}">${safe(item.text)}</span>`).join(''):'<span class="muted">Nenhuma tendência capturada.</span>';
  $('#trendsSummary').textContent=`${p.relatedTrends.capturedCount} capturadas${p.relatedTrends.reportedTotalMin?` · ${p.relatedTrends.reportedTotalMin}${p.relatedTrends.reportedTotalIsApproximate?'+':''} informadas pela interface`:''}.`;
  const data=[['Termo',p.basic.searchTerm],['Região',p.basic.region],['Período',p.basic.period],['Categoria',p.basic.category],['Tipo de pesquisa',p.basic.searchType],['Coleta',dateTime(analysis.capturedAt)],['Parser',analysis.parserVersion],['Analisador',analysis.analyzerVersion],['Regra do sinal',analysis.signal?.rulesVersion||'V1 legado'],['Offer IDs',analysis.offerIds.join(', ')||'—']];$('#collectionData').innerHTML=data.map(([label,value])=>`<div><dt>${safe(label)}</dt><dd>${safe(value||'—')}</dd></div>`).join('');renderHistory();
}
function resizeRawInput(){const input=$('#rawInput');input.style.height='auto';const contentHeight=Math.max(input.scrollHeight,104);if(embedded){const maxHeight=180;input.style.height=`${Math.min(contentHeight,maxHeight)}px`;input.style.overflowY=contentHeight>maxHeight?'auto':'hidden'}else input.style.height=`${contentHeight}px`;scheduleEmbeddedHeight()}
function renderHistory(){$('#history').innerHTML=history.length?history.map(item=>`<div class="history-row"><span>${safe(dateTime(item.capturedAt))}</span><div><b>${safe(Domain.compactSummary(item))}</b><small class="history-version">${safe(item.analyzerVersion?`Analisador ${item.analyzerVersion}${item.signal?.rulesVersion?` · ${item.signal.rulesVersion}`:''}`:'Versão legada')}</small></div><button class="button subtle" data-history="${safe(item.analysisId)}" type="button">Abrir</button></div>`).join(''):'<p class="muted">Nenhuma coleta anterior.</p>';document.querySelectorAll('[data-history]').forEach(button=>button.onclick=()=>{const item=history.find(entry=>entry.analysisId===button.dataset.history);if(item){$('#rawInput').value=item.rawSanitized||'';resizeRawInput();render(item);scrollTo({top:0,behavior:'smooth'})}})}
async function load(){history=await Storage.getHistoryByProduct(Domain.normalize(context.productKey||context.productName));const latest=history[0];$('#productName').textContent=context.productName||latest?.productName||'Análise Glimpse';document.title=`Glimpse · ${$('#productName').textContent}`;$('#productMeta').textContent=[context.offerIds.length?`Offer ID: ${context.offerIds.join(', ')}`:'',`Origem: ${origin==='top'?'E-commerce GM':origin==='hot-offers-ms'?'Hot Offers MS':origin==='clickbank-top-offers'?'Top Offers CB':origin==='smartadv-offers'?'SmartAdv':'Lista de Gerente'}`].filter(Boolean).join(' · ');if(latest){$('#rawInput').value=latest.rawSanitized||'';render(latest)}else renderHistory();resizeRawInput();scheduleEmbeddedHeight()}
function observabilityPayload(analysis){const source=origin==='top'?'guru-media-ecommerce-gm':origin==='hot-offers-ms'?'hot-offers-ms':origin==='clickbank-top-offers'?'clickbank-top-offers':origin==='smartadv-offers'?'smartadv-offers':'guru-media-lista-gerente',subjectId=origin==='hot-offers-ms'?`hot-offers-ms:${context.scope||'unknown'}:${context.offerIds[0]||context.productKey||analysis.productKey}`:origin==='clickbank-top-offers'?`clickbank-top-offers:${context.offerKey||context.productKey||analysis.productKey}`:origin==='smartadv-offers'?`smartadv-offers:${context.offerIds[0]||analysis.productKey}`:`${origin}-product:${context.productKey||analysis.productKey}`,offerRefs=origin==='clickbank-top-offers'?[{origin:source,offerKey:context.offerKey||null}]:context.offerIds.map(offerId=>({origin:source,scope:context.scope||undefined,offerId}));return{origin:source,subjectId,productKey:context.productKey||analysis.productKey,productName:context.productName||analysis.productName,offerRefs,analysis}}
async function saveAnalysis(analysis,{automatic=false}={}){if(history.some(item=>item.analysisId===analysis.analysisId))return true;if(pendingSaves.has(analysis.analysisId))return pendingSaves.get(analysis.analysisId);const task=(async()=>{try{await Storage.saveAnalysis(analysis);history=[analysis,...history.filter(item=>item.analysisId!==analysis.analysisId)].sort((a,b)=>String(b.capturedAt).localeCompare(String(a.capturedAt)));renderHistory();if(draft?.analysisId===analysis.analysisId)$('#message').textContent=automatic?'Análise salva automaticamente.':'Análise salva.';scheduleEmbeddedHeight();void CurationObservability.recordGlimpse(observabilityPayload(analysis)).catch(error=>console.error('Falha ao registrar a análise Glimpse na observabilidade.',error));return true}catch(error){console.error('Falha ao salvar análise Glimpse.',error);if(draft?.analysisId===analysis.analysisId)$('#message').textContent=automatic?'A análise foi preparada, mas não pôde ser salva. Clique em Concluir para tentar novamente.':'Não foi possível salvar a análise. Tente novamente.';return false}finally{pendingSaves.delete(analysis.analysisId)}})();pendingSaves.set(analysis.analysisId,task);return task}
function analyzeInput(automatic=false){const raw=$('#rawInput').value.trim();if(!raw){if(!automatic)$('#message').textContent='Cole o conteúdo da página antes de analisar.';return}const analysis=Domain.createAnalysis(raw,context);$('#message').textContent=automatic?'Análise preparada automaticamente. Salvando...':'Análise preparada. Clique em Concluir para salvar.';render(analysis);if(automatic)void saveAnalysis(analysis,{automatic:true})}
$('#analyze').onclick=()=>analyzeInput();$('#rawInput').addEventListener('input',resizeRawInput);$('#rawInput').addEventListener('paste',()=>setTimeout(()=>{resizeRawInput();analyzeInput(true)},0));
$('#clearInput').onclick=()=>{$('#rawInput').value='';resizeRawInput();$('#message').textContent='Campo limpo. Nenhum dado salvo foi removido.';$('#rawInput').focus()};$('#newCollection').onclick=()=>{$('#rawInput').value='';resizeRawInput();draft=null;$('#results').classList.add('hidden');$('#message').textContent='Cole uma nova coleta para este produto.';$('#rawInput').focus()};$('#cancel').onclick=()=>void goBack();$('#cancelTop').onclick=()=>void goBack();$('#finish').onclick=()=>void finishAnalysis();window.addEventListener('message',event=>{if(!embedded||event.origin!==location.origin||event.source!==window.parent||event.data?.type!=='hub-glimpse-finish')return;void finishAnalysis()});Storage.openGlimpseDB().then(load).catch(error=>{console.error(error);$('#message').textContent='Não foi possível abrir o armazenamento local do Glimpse.'});
