import * as Domain from '../glimpse-domain.mjs';
import * as Storage from '../glimpse-storage.mjs';

const $=selector=>document.querySelector(selector),safe=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const params=new URLSearchParams(location.search),context={productKey:params.get('productKey')||'',productName:params.get('product')||'',offerIds:(params.get('offerIds')||'').split(',').filter(Boolean)},origin=params.get('origin')==='top'?'top':'manager';
const returnUrl=origin==='top'?'../top-performance/':'../gerentes/';let draft=null,history=[];
function dateTime(value){const date=new Date(value);return Number.isNaN(date.getTime())?'—':new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(date)}
function relevanceLabel(value){return{high:'Alta',medium:'Média',low:'Baixa',unclear:'Indefinida'}[value]||'Indefinida'}
function percent(value){return value===null||value===undefined?'—':`${Math.round(value*100)}%`}
function goBack(){location.href=returnUrl}
function indicatorRows(analysis){const p=analysis.parsed,i=analysis.indicators,c=analysis.classified,commercial=[...c.peopleAlsoSearch,...c.relatedQueries].filter(item=>['BOFU / Reviews','Compra / Preço','Confiança / Objeção'].includes(item.category)).length;return[
  ['Volume mensal',p.volume.display||'Não detectado',p.volume.operator==='<'?'Limite superior informado; não é exatamente 500.':'Estimativa informada pelo Glimpse.'],
  ['Movimento recente',p.movement.percent===null?'Não detectado':`${p.movement.percent>=0?'+':''}${p.movement.percent}%`,p.movement.period||'Período não detectado'],
  ['Intenção comercial',commercial,commercial?'Há sinais de avaliação, compra ou objeção.':'Nenhum sinal comercial foi capturado nesta colagem.'],
  ['Contaminação semântica',Domain.contaminationLabel(i.contamination.level),i.contamination.ratio===null?'Sem material suficiente':`${percent(i.contamination.ratio)} dos itens sem relação clara`],
  ['Cobertura dos dados',Domain.coverageLabel(i.coverage.level),`${i.coverage.availableSources} de ${i.coverage.totalSources} fontes disponíveis`],
  ['Países/regiões',p.regions.reportedTotal??p.regions.capturedCount,`${p.regions.capturedCount} capturada(s); índice relativo, não volume`],
  ['Concentração geográfica',i.geography.level==='concentrated'?'Concentrada':i.geography.level==='distributed'?'Distribuída':i.geography.level==='limited'?'Limitada':'Não detectada','A região 100 não é automaticamente o melhor mercado comercial.'],
  ['People Also Search',p.peopleAlsoSearch.capturedCount,p.peopleAlsoSearch.pagination?`Página ${p.peopleAlsoSearch.pagination.currentPage} de ${p.peopleAlsoSearch.pagination.totalPages}; somente itens visíveis foram capturados.`:Domain.stateLabel(p.peopleAlsoSearch.state)],
  ['Related Trends',p.relatedTrends.capturedCount,p.relatedTrends.reportedTotalMin?`${p.relatedTrends.reportedTotalMin}${p.relatedTrends.reportedTotalIsApproximate?'+':''} informadas; ${p.relatedTrends.capturedCount} capturadas.`:Domain.stateLabel(p.relatedTrends.state)],
  ['Queries emergentes',p.relatedQueries.capturedCount,Domain.stateLabel(p.relatedQueries.state)],['Tópicos emergentes',p.relatedTopics.capturedCount,Domain.stateLabel(p.relatedTopics.state)],
  ['Sazonalidade',Domain.stateLabel(p.seasonality.state),'Ausência de dados não é sinal negativo.'],['Channel Breakdown',Domain.stateLabel(p.channel.state),'Disponibilidade declarada pela interface.']
].map(row=>`<tr><td><b>${safe(row[0])}</b></td><td>${safe(row[1])}</td><td>${safe(row[2])}</td></tr>`).join('')}
function renderClassifications(analysis){const entries=Object.entries(analysis.indicators.categoryCounts),total=entries.reduce((sum,[,count])=>sum+count,0);$('#intentions').innerHTML=entries.length?entries.sort((a,b)=>b[1]-a[1]).map(([label,count])=>`<div class="stack-row"><div><b>${safe(label)}</b><div class="bar"><i style="width:${total?count/total*100:0}%"></i></div></div><span>${count} · ${total?Math.round(count/total*100):0}%</span></div>`).join(''):'<p class="muted">Nenhuma query capturada.</p>'}
function emergingRows(items){return items.length?items.map(item=>`<div class="stack-row"><div><b>${safe(item.text)}</b><small>${safe(item.status||'Sem crescimento informado')}</small></div><span class="relevance-${safe(item.relevance)}">${safe(relevanceLabel(item.relevance))}</span></div>`).join(''):'<p class="muted">Nenhum item disponível.</p>'}
function render(analysis){
  draft=analysis;const p=analysis.parsed,i=analysis.indicators;$('#results').classList.remove('hidden');
  $('#volumeCard').textContent=p.volume.display||'—';$('#movementCard').textContent=p.movement.percent===null?'—':`${p.movement.percent>=0?'+':''}${p.movement.percent}%`;$('#movementPeriod').textContent=p.movement.period||'período não detectado';
  $('#geographyCard').textContent=(p.regions.reportedTotal??p.regions.capturedCount)||'—';$('#geographyNote').textContent=p.regions.reportedTotal?`${p.regions.capturedCount} capturadas · ${p.regions.reportedTotal} informadas`:`${p.regions.capturedCount} capturadas`;$('#coverageCard').textContent=Domain.coverageLabel(i.coverage.level);
  $('#signalValue').textContent=Domain.signalLabel(analysis.signal.level);$('#operationalReading').textContent=analysis.operationalReading;$('#indicatorRows').innerHTML=indicatorRows(analysis);renderClassifications(analysis);
  $('#regionRows').innerHTML=p.regions.items.length?p.regions.items.map(item=>`<tr><td>${item.rank}</td><td>${safe(item.region)}</td><td>${safe(`${item.interestOperator==='<'?'<':''}${item.interestIndex}`)}</td></tr>`).join(''):'<tr><td colspan="3">Nenhuma região capturada.</td></tr>';
  $('#regionsSummary').textContent=`${p.regions.capturedCount} regiões capturadas${p.regions.reportedTotal?` · ${p.regions.reportedTotal} informadas pela interface`:''}. Índice relativo de interesse — não representa buscas.`;$('#topicRows').innerHTML=emergingRows(analysis.classified.relatedTopics);$('#queryRows').innerHTML=emergingRows(analysis.classified.relatedQueries);
  $('#trendRows').innerHTML=analysis.classified.relatedTrends.length?analysis.classified.relatedTrends.map(item=>`<span class="tag ${item.relevance==='low'||item.relevance==='unclear'?'low':''}" title="Relevância ${safe(relevanceLabel(item.relevance))}">${safe(item.text)}</span>`).join(''):'<span class="muted">Nenhuma tendência capturada.</span>';
  $('#trendsSummary').textContent=`${p.relatedTrends.capturedCount} capturadas${p.relatedTrends.reportedTotalMin?` · ${p.relatedTrends.reportedTotalMin}${p.relatedTrends.reportedTotalIsApproximate?'+':''} informadas pela interface`:''}.`;
  const data=[['Termo',p.basic.searchTerm],['Região',p.basic.region],['Período',p.basic.period],['Categoria',p.basic.category],['Tipo de pesquisa',p.basic.searchType],['Coleta',dateTime(analysis.capturedAt)],['Parser',analysis.parserVersion],['Analisador',analysis.analyzerVersion],['Offer IDs',analysis.offerIds.join(', ')||'—']];$('#collectionData').innerHTML=data.map(([label,value])=>`<div><dt>${safe(label)}</dt><dd>${safe(value||'—')}</dd></div>`).join('');renderHistory();
}
function renderHistory(){$('#history').innerHTML=history.length?history.map(item=>`<div class="history-row"><span>${safe(dateTime(item.capturedAt))}</span><b>${safe(Domain.compactSummary(item))}</b><button class="button subtle" data-history="${safe(item.analysisId)}" type="button">Abrir</button></div>`).join(''):'<p class="muted">Nenhuma coleta anterior.</p>';document.querySelectorAll('[data-history]').forEach(button=>button.onclick=()=>{const item=history.find(entry=>entry.analysisId===button.dataset.history);if(item){$('#rawInput').value=item.rawSanitized||'';render(item);scrollTo({top:0,behavior:'smooth'})}})}
async function load(){history=await Storage.getHistoryByProduct(Domain.normalize(context.productKey||context.productName));const latest=history[0];$('#productName').textContent=context.productName||latest?.productName||'Análise Glimpse';document.title=`Glimpse · ${$('#productName').textContent}`;$('#productMeta').textContent=[context.offerIds.length?`Offer ID: ${context.offerIds.join(', ')}`:'',`Origem: ${origin==='top'?'Top Performance':'Lista de Gerente'}`].filter(Boolean).join(' · ');if(latest){$('#rawInput').value=latest.rawSanitized||'';render(latest)}else renderHistory()}
$('#analyze').onclick=()=>{const raw=$('#rawInput').value.trim();if(!raw){$('#message').textContent='Cole o conteúdo da página antes de analisar.';return}const analysis=Domain.createAnalysis(raw,context);$('#message').textContent='Análise preparada. Clique em Concluir para salvar.';render(analysis)};
$('#clearInput').onclick=()=>{$('#rawInput').value='';$('#message').textContent='Campo limpo. Nenhum dado salvo foi removido.';$('#rawInput').focus()};$('#newCollection').onclick=()=>{$('#rawInput').value='';draft=null;$('#results').classList.add('hidden');$('#message').textContent='Cole uma nova coleta para este produto.';$('#rawInput').focus()};$('#cancel').onclick=goBack;$('#cancelTop').onclick=goBack;$('#finish').onclick=async()=>{if(draft&&!history.some(item=>item.analysisId===draft.analysisId)){await Storage.saveAnalysis(draft);$('#message').textContent='Análise salva.'}goBack()};Storage.openGlimpseDB().then(load).catch(error=>{console.error(error);$('#message').textContent='Não foi possível abrir o armazenamento local do Glimpse.'});
