export const PARSER_VERSION='1.0.0';
export const ANALYZER_VERSION='1.0.0';

const NOISE=/^(?:set alert|tracking|forecast|export data|file_download|code|share|more_vert|help_outline|previous|next|upgrade|compare|all searches|topic map|refreshes in|\d+\s*\/\s*\d+|searches left)$/i;
const HEADINGS=['People Also Search','Related Trends','Channel','Interesse por região','Related Topics','Related Queries','Assuntos relacionados','Pesquisas relacionadas'];
const CATEGORY_RULES=[
  ['BOFU / Reviews',/\b(review|reviews|avis|opini(?:a|ã)o|opiniões|omdöme|testimonials?|reclame aqui)\b/i],
  ['Compra / Preço',/\b(price|preço|preco|buy|comprar|purchase|coupon|cupom|discount|desconto|onde comprar|order|pedido)\b/i],
  ['Confiança / Objeção',/\b(scam|fraud|fraude|con\b|legit|legítim|confiável|confiavel|real\b|funciona|reliable|trust|seguro)\b/i],
  ['Produto / Características',/\b(app|box|manual|setup|channels?|canais|ingredients?|ingredientes?|dose|dosage|configura(?:ç|c)|features?|benefits?)\b/i],
  ['Técnico',/\b(config|configuration|documentation|github|xml|api|default|code|apk|stream)\b/i],
  ['Navegacional',/\b(facebook|instagram|site|official|oficial|login|youtube)\b/i],
  ['Problema / Benefício',/\b(weight loss|emagrec|sleep|sono|pain|dor|hearing|cabelo|hair|skin|pele)\b/i],
  ['Informacional',/\b(what|how|como|o que|qual|why|por que|para que)\b/i]
];

export function normalize(value=''){return String(value).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
export function sanitizeRaw(raw=''){
  return String(raw).replace(/https?:\/\/\S+/gi,url=>{try{const parsed=new URL(url);return `${parsed.origin}${parsed.pathname}`}catch{return '[URL removida]'}}).replace(/(token|auth|session|key|code)=\S+/gi,'$1=[removido]').replace(/\r/g,'').trim();
}
function linesFrom(raw=''){return sanitizeRaw(raw).split('\n').map(line=>line.replace(/&#x20;|&nbsp;/gi,' ').replace(/\\_/g,'_').trim()).filter(Boolean)}
function headingIndex(lines,name,start=0){const target=normalize(name);return lines.findIndex((line,index)=>index>=start&&normalize(line)===target)}
function nextHeadingIndex(lines,start,names=HEADINGS){const targets=new Set(names.map(normalize));for(let index=start;index<lines.length;index++)if(targets.has(normalize(lines[index])))return index;return lines.length}
function parseCompactNumber(text){const match=String(text).replace(/\s/g,'').match(/^(<|>|≤|≥)?([\d.,]+)([KMB])?$/i);if(!match)return null;let numeric=match[2].replace(',','.');const value=Number(numeric);if(!Number.isFinite(value))return null;const multiplier={K:1e3,M:1e6,B:1e9}[String(match[3]||'').toUpperCase()]||1;return {value:Math.round(value*multiplier),operator:match[1]||'=',display:`${match[1]||''}${match[2]}${match[3]||''}`}}
function parseReported(text,unit){const expression=new RegExp(`(?:Showing|Mostrando)\\s+(\\d+)\\s*(?:-|a)\\s*(\\d+)\\s+(?:of|de)\\s+(\\d+)\\s+${unit}`,'i'),match=String(text).match(expression);return match?{visibleStart:Number(match[1]),visibleEnd:Number(match[2]),reportedTotal:Number(match[3])}:null}
function cleanItems(lines){return lines.filter(line=>!NOISE.test(line)&&!/^See all /i.test(line)&&!/^Page \d+ of \d+/i.test(line)&&!/^Showing /i.test(line)&&!/^Include low /i.test(line)&&!/^Incluir regiões/i.test(line)&&!/^Data not available/i.test(line)&&!/^Não há dados/i.test(line))}
function sectionLines(lines,heading,endHeadings=HEADINGS){const start=headingIndex(lines,heading);if(start<0)return[];return lines.slice(start+1,nextHeadingIndex(lines,start+1,endHeadings))}
function stateFor(lines,section=''){const text=(sectionLines(lines,section).join(' ')||lines.join(' '));if(/unavailable for low volume|indisponível por baixo volume/i.test(text))return'unavailable_low_volume';if(/not enough data|não há dados de pesquisa suficientes/i.test(text))return'insufficient_data';if(/data not available|dados indisponíveis/i.test(text))return'not_available';return section&&headingIndex(lines,section)<0?'not_detected':'available'}
function parsePeopleAlsoSearch(lines){const raw=sectionLines(lines,'People Also Search',['Related Trends','Channel','Interesse por região','Related Topics','Related Queries']);const pageLine=raw.find(line=>/^Page \d+ of \d+/i.test(line));const page=pageLine?.match(/Page\s+(\d+)\s+of\s+(\d+)/i);const items=cleanItems(raw).filter(line=>!/^(?:Seasonality|Not enough data)/i.test(line));return {state:headingIndex(lines,'People Also Search')<0?'not_detected':items.length?'available':stateFor(lines,'People Also Search'),items:[...new Set(items)],capturedCount:new Set(items).size,pagination:page?{currentPage:Number(page[1]),totalPages:Number(page[2])}:null}}
function parseRelatedTrends(lines){const raw=sectionLines(lines,'Related Trends',['Channel','Interesse por região','Related Topics','Related Queries']);const totalLine=raw.find(line=>/^See all /i.test(line)),total=totalLine?.match(/See all\s+(\d+)\+?\s+Related Trends/i);const items=cleanItems(raw).filter(line=>!/^See all /i.test(line));return {state:headingIndex(lines,'Related Trends')<0?'not_detected':items.length?'available':stateFor(lines,'Related Trends'),items:[...new Set(items)],capturedCount:new Set(items).size,reportedTotalMin:total?Number(total[1]):null,reportedTotalIsApproximate:!!totalLine?.includes('+')}}
function parseRegions(lines){
  const indices=[];for(let i=0;i<lines.length;i++)if(normalize(lines[i])==='interesse por regiao')indices.push(i);const start=indices.at(-1);if(start===undefined)return{state:'not_detected',items:[],capturedCount:0,reportedTotal:null};
  const end=nextHeadingIndex(lines,start+1,['Related Topics','Related Queries','Assuntos relacionados','Pesquisas relacionadas','Topic Map']);const raw=lines.slice(start+1,end),items=[];
  for(let i=0;i<raw.length;i++){
    let rankMatch=raw[i].match(/^(\d+)\s+(.+?)\s*(<?\d+)$/);if(rankMatch){items.push({rank:Number(rankMatch[1]),region:rankMatch[2].trim(),interestIndex:Number(rankMatch[3].replace('<','')),interestOperator:rankMatch[3].startsWith('<')?'<':'='});continue}
    if(/^\d+$/.test(raw[i])&&raw[i+1]&&!NOISE.test(raw[i+1])){const value=raw[i+2]?.match(/^(<)?(\d+)$/);if(value){items.push({rank:Number(raw[i]),region:raw[i+1],interestIndex:Number(value[2]),interestOperator:value[1]||'='});i+=2}}
  }
  const reportLine=raw.find(line=>/^(?:Showing|Mostrando) /i.test(line)),report=parseReported(reportLine||'','(?:regions|regiões)');return {state:items.length?'available':stateFor(lines,'Interesse por região'),items,capturedCount:items.length,reportedTotal:report?.reportedTotal??null};
}
function parseEmerging(lines,heading,endHeadings){
  const headings=Array.isArray(heading)?heading:[heading],selected=headings.find(name=>headingIndex(lines,name)>=0)||headings[0],raw=sectionLines(lines,selected,endHeadings),items=[];
  for(let i=0;i<raw.length;i++){
    const rank=raw[i].match(/^(\d+)$/);if(!rank)continue;let text=raw[i+1];if(!text||NOISE.test(text))continue;let status='',growth=null,breakout=false;const inline=text.match(/^(.*?)(Aumento repentino|Breakout|Mais\s*\d+%|\+\d+%)$/i);if(inline){text=inline[1].trim();status=inline[2];breakout=/Aumento repentino|Breakout/i.test(status);growth=breakout?null:Number(status.match(/\d+/)?.[0]);i+=1}else{const candidate=raw[i+2]||'';if(/Aumento repentino|Breakout/i.test(candidate)){status=candidate;breakout=true;i+=2}else if(/(?:Mais\s*)?\d+%|\+\d+%/.test(candidate)){status=candidate;growth=Number(candidate.match(/\d+/)?.[0]);i+=2}else i+=1}items.push({rank:Number(rank[1]),text,status,growthPercent:growth,breakout});
  }
  const reportLine=raw.find(line=>/^(?:Showing|Mostrando) /i.test(line)),unit=/Topics|Assuntos/i.test(selected)?'(?:topics|assuntos)':'(?:topics|consultas)',report=parseReported(reportLine||'',unit);return {state:items.length?'available':stateFor(lines,selected),items,capturedCount:items.length,reportedTotal:report?.reportedTotal??null};
}
function detectBasic(lines){
  const termLabel=headingIndex(lines,'Termo de pesquisa'),term=termLabel>0?lines[termLabel-1]:'';const compare=headingIndex(lines,'Compare',Math.max(0,termLabel));const config=compare>=0?lines.slice(compare+1,compare+5):[];
  return {searchTerm:term,region:config[0]||null,period:config[1]||null,category:config[2]||null,searchType:config[3]||null};
}
function detectVolume(lines){for(let i=0;i<lines.length;i++){const match=lines[i].match(/^(<\s*)?[\d.,]+\s*[KMB]?\s+searches past month$/i);if(!match)continue;const display=lines[i].replace(/\s+searches past month/i,'').replace(/\s/g,''),parsed=parseCompactNumber(display);return parsed?{...parsed,period:'past_month',state:'available'}:null}return{value:null,operator:null,display:null,period:'past_month',state:'not_detected'}}
function detectMovement(lines){for(let i=0;i<lines.length;i++){const inline=lines[i].match(/([+-]?\d+(?:[.,]\d+)?)%\s*(past week|past month|última semana|último mês)?/i);if(inline)return{percent:Number(inline[1].replace(',','.')),period:inline[2]||lines[i+1]||null,state:'available'};if(/^[-+]?\d+(?:[.,]\d+)?%$/.test(lines[i])&&/past week|past month|semana|mês/i.test(lines[i+1]||''))return{percent:Number(lines[i].replace('%','').replace(',','.')),period:lines[i+1],state:'available'}}return{percent:null,period:null,state:'not_detected'}}

export function parseGlimpse(raw=''){
  const sanitizedRaw=sanitizeRaw(raw),lines=linesFrom(raw),basic=detectBasic(lines),volume=detectVolume(lines),movement=detectMovement(lines),seasonality={state:/not enough data|não há dados de pesquisa suficientes/i.test(lines.join(' '))?'insufficient_data':headingIndex(lines,'Seasonality')>=0?'available':'not_detected'},channel={state:/Channel breakdown is unavailable for low volume/i.test(lines.join(' '))?'unavailable_low_volume':headingIndex(lines,'Channel')>=0?'available':'not_detected'};
  return {parserVersion:PARSER_VERSION,sanitizedRaw,basic,volume,movement,seasonality,channel,peopleAlsoSearch:parsePeopleAlsoSearch(lines),relatedTrends:parseRelatedTrends(lines),regions:parseRegions(lines),relatedTopics:parseEmerging(lines,['Related Topics','Assuntos relacionados'],['Related Queries','Pesquisas relacionadas']),relatedQueries:parseEmerging(lines,['Related Queries','Pesquisas relacionadas'],[])};
}

function tokenOverlap(text,term){const words=new Set(normalize(term).split(' ').filter(word=>word.length>2)),candidate=normalize(text);return[...words].some(word=>candidate.includes(word))}
export function classifyQuery(text='',searchTerm=''){
  const normalized=normalize(text);let category='Outros',confidence=.58;for(const [label,rule]of CATEGORY_RULES)if(rule.test(normalized)){category=label;confidence=.88;break}
  const related=tokenOverlap(text,searchTerm),relevance=related?'high':category==='Técnico'||category==='Navegacional'?'medium':category==='Outros'?'unclear':'medium';return{text,category,confidence,relevance};
}
function coverage(parsed){const checks=[parsed.volume.state==='available',parsed.movement.state==='available',parsed.regions.items.length>0,parsed.peopleAlsoSearch.items.length>0,parsed.relatedTrends.items.length>0,parsed.relatedTopics.items.length>0,parsed.relatedQueries.items.length>0,parsed.seasonality.state==='available',parsed.channel.state==='available'],score=checks.filter(Boolean).length;return{level:score>=6?'high':score>=3?'medium':'low',score,availableSources:checks.filter(Boolean).length,totalSources:checks.length}}
function contamination(classified){if(!classified.length)return{level:'unclear',ratio:null};const low=classified.filter(item=>item.relevance==='low'||item.relevance==='unclear').length,ratio=low/classified.length;return{level:ratio>.45?'high':ratio>.2?'medium':'low',ratio}}
function signalFor(parsed,classified,cov,cont){let score=0;if(parsed.volume.state==='available')score+=parsed.volume.operator==='<'?6:parsed.volume.value>=100000?32:parsed.volume.value>=10000?24:parsed.volume.value>=1000?16:8;if(parsed.movement.percent>0)score+=Math.min(18,parsed.movement.percent/10);score+=classified.filter(item=>['BOFU / Reviews','Compra / Preço','Confiança / Objeção'].includes(item.category)).length*3;score+=cov.score*2;if(cont.level==='high')score-=12;const level=parsed.volume.operator==='<'&&cov.level==='low'?'limited':score>=50?'strong':score>=25?'medium':'limited';return{level,score:Math.round(score),rulesVersion:'glimpse-signal-v1'}}
function operationalReading(parsed,signal,cov,cont,classified){const volume=parsed.volume.display?`${parsed.volume.display} buscas/mês`:'volume não detectado',movement=parsed.movement.percent===null?'movimento não detectado':`${parsed.movement.percent>=0?'+':''}${parsed.movement.percent}% no período recente`,commercial=classified.filter(item=>['BOFU / Reviews','Compra / Preço','Confiança / Objeção'].includes(item.category)).length;return `${volume}; ${movement}. Foram encontrados ${commercial} sinais de intenção comercial. Cobertura ${coverageLabel(cov.level).toLowerCase()} e contaminação semântica ${contaminationLabel(cont.level).toLowerCase()}. ${parsed.regions.items.length<=1?'A leitura geográfica é limitada.':'A distribuição geográfica deve ser interpretada pelo índice relativo, não como volume de buscas.'}`}
export function analyzeGlimpse(parsed){
  const term=parsed.basic.searchTerm,people=parsed.peopleAlsoSearch.items.map(item=>classifyQuery(item,term)),trends=parsed.relatedTrends.items.map(item=>classifyQuery(item,term)),topics=parsed.relatedTopics.items.map(item=>({...item,...classifyQuery(item.text,term)})),queries=parsed.relatedQueries.items.map(item=>({...item,...classifyQuery(item.text,term)})),classified=[...people,...trends,...topics,...queries],cov=coverage(parsed),cont=contamination(classified),signal=signalFor(parsed,classified,cov,cont);
  const categoryCounts=classified.reduce((map,item)=>(map[item.category]=(map[item.category]||0)+1,map),{}),geo=parsed.regions.items.length>1?{level:parsed.regions.items[0].interestIndex>=parsed.regions.items[1].interestIndex*2?'concentrated':'distributed'}:{level:parsed.regions.items.length?'limited':'not_detected'};
  return {analyzerVersion:ANALYZER_VERSION,classified:{peopleAlsoSearch:people,relatedTrends:trends,relatedTopics:topics,relatedQueries:queries},indicators:{coverage:cov,contamination:cont,categoryCounts,geography:geo},signal,operationalReading:operationalReading(parsed,signal,cov,cont,classified)};
}
export function createAnalysis(raw,context={},capturedAt=new Date().toISOString()){const parsed=parseGlimpse(raw),derived=analyzeGlimpse(parsed);return{analysisId:crypto.randomUUID(),productKey:normalize(context.productKey||context.productName||parsed.basic.searchTerm),productName:context.productName||parsed.basic.searchTerm||'Produto sem nome',offerIds:[...new Set((context.offerIds||[]).map(String).filter(Boolean))],capturedAt,parserVersion:PARSER_VERSION,analyzerVersion:ANALYZER_VERSION,rawSanitized:parsed.sanitizedRaw,parsed:{...parsed,sanitizedRaw:undefined},classified:derived.classified,indicators:derived.indicators,signal:derived.signal,operationalReading:derived.operationalReading}}
export function signalLabel(value){return value==='strong'?'Forte':value==='medium'?'Médio':value==='limited'?'Dados limitados':'Sem análise'}
export function coverageLabel(value){return value==='high'?'Alta':value==='medium'?'Média':value==='low'?'Baixa':'Não detectada'}
export function contaminationLabel(value){return value==='high'?'Alta':value==='medium'?'Média':value==='low'?'Baixa':'Indefinida'}
export function stateLabel(value){return{available:'Disponível',insufficient_data:'Sem dados suficientes',unavailable_low_volume:'Indisponível por baixo volume',not_available:'Dados indisponíveis',not_detected:'Não detectado'}[value]||'Não detectado'}
export function compactSummary(analysis){if(!analysis)return'Pesquisar';const volume=analysis.parsed?.volume?.display||'Sem volume',label=analysis.parsed?.volume?.operator==='<'?'Limitado':signalLabel(analysis.signal?.level);return`${volume} · ${label}`}
export function analysisRank(analysis){if(!analysis)return 0;return({strong:3,medium:2,limited:1}[analysis.signal?.level]||0)*1e9+(analysis.parsed?.volume?.value||0)}
