(function(){
  // Presentation only. Catalog writes stay behind explicit Hub action callbacks.
  function mount({root,getSnapshot,domain,format,preferences,actions,dialogs,toast}){
    const $=selector=>root.querySelector(selector),$$=selector=>[...root.querySelectorAll(selector)];
    const {esc,num:fmtNum,money:fmtMoney,date:dateLabel}=format,{prompt,confirm}=dialogs;
    const TESTED_COLUMNS=[['date','Data'],['campaigns','Campanhas'],['sales','Vendas'],['revenue','Total faturado'],['profit','Lucro total'],['period','Período'],['status','Situação'],['related','Campanhas relacionadas'],['actions','Ação']],TESTED_COLUMNS_PREF='painel-produtos-testados-colunas-v1';let hiddenTestedColumns=new Set(),testedSortKey='status',testedSortDir='desc';try{hiddenTestedColumns=new Set(JSON.parse(preferences.getItem(TESTED_COLUMNS_PREF)||'[]').filter(column=>TESTED_COLUMNS.some(([id])=>id===column)))}catch{}
    const sortTestedProducts=products=>domain.sortProducts(products,testedSortKey,testedSortDir);
    function applyTestedColumnVisibility(){$$('[data-tested-col]').forEach(cell=>cell.classList.toggle('hidden-column',hiddenTestedColumns.has(cell.dataset.testedCol)))}
    function renderTestedColumnPicker(){$('#testedColumnsMenu').innerHTML='<strong>Exibir colunas</strong>'+TESTED_COLUMNS.map(([id,label])=>`<label><input type="checkbox" data-tested-column="${id}" ${hiddenTestedColumns.has(id)?'':'checked'}> ${label}</label>`).join('');$$('[data-tested-column]').forEach(input=>input.onchange=()=>{input.checked?hiddenTestedColumns.delete(input.dataset.testedColumn):hiddenTestedColumns.add(input.dataset.testedColumn);preferences.setItem(TESTED_COLUMNS_PREF,JSON.stringify([...hiddenTestedColumns]));applyTestedColumnVisibility()});applyTestedColumnVisibility()}
    function bindTestedSorting(){$$('[data-tested-sort]').forEach(button=>{const active=button.dataset.testedSort===testedSortKey;button.classList.toggle('active',active);button.querySelector('.sort-arrow').textContent=active?(testedSortDir==='asc'?'↑':'↓'):'';button.onclick=()=>{if(testedSortKey===button.dataset.testedSort)testedSortDir=testedSortDir==='asc'?'desc':'asc';else{testedSortKey=button.dataset.testedSort;testedSortDir='asc'}renderTestedProducts()}})}
    function renderTestedProducts(){const {products,removed}=getSnapshot(),sortedProducts=sortTestedProducts(products),activeProducts=products.filter(product=>product.active).length;$('#testedProductsCount').textContent=`${products.length} ${products.length===1?'produto':'produtos'}`;$('#testedActiveProductsCount').textContent=`${activeProducts} ${activeProducts===1?'com campanha ativa':'com campanhas ativas'}`;$('#restoreProducts').classList.toggle('hidden',!removed);$('#purgeProducts').classList.toggle('hidden',!removed);$('#testedProductsBody').innerHTML=sortedProducts.length?sortedProducts.map(p=>`<tr><td data-tested-col="product" class="name">${esc(p.label)}</td><td data-tested-col="date">${p.startDate?dateLabel(p.startDate):'—'}</td><td data-tested-col="campaigns" class="num">${p.campaigns.length}</td><td data-tested-col="sales" class="num">${fmtNum(p.salesCount,Number.isInteger(p.salesCount)?0:2)}</td><td data-tested-col="revenue" class="num">${fmtMoney(p.totalBilled)}</td><td data-tested-col="profit" class="num">${fmtMoney(p.totalProfit)}</td><td data-tested-col="period">${p.first?`${dateLabel(p.first)} a ${dateLabel(p.last)}`:'Sem datas'}</td><td data-tested-col="status"><span class="tag tested-status ${p.active?'active':'historical'}">${p.active?'Ativo':'Histórico'}</span></td><td data-tested-col="related" class="campaigns">${esc(p.campaigns.join(' · '))}</td><td data-tested-col="actions"><div class="row-actions"><button class="catalog-edit" data-key="${esc(p.key)}" data-product="${esc(p.label)}" type="button">Editar nome</button><button class="catalog-remove" data-key="${esc(p.key)}" data-product="${esc(p.label)}" type="button">Remover</button></div></td></tr>`).join(''):'<tr><td colspan="10" class="empty">Nenhum produto disponível neste cadastro.</td></tr>';renderTestedColumnPicker();bindTestedSorting();$$('.catalog-edit').forEach(button=>button.onclick=async()=>{const label=prompt('Nome do produto:',button.dataset.product);if(label===null)return;try{await actions.rename(button.dataset.key,label);renderTestedProducts();toast('Nome do produto atualizado')}catch(error){toast(error.message,true)}});$$('.catalog-remove').forEach(button=>button.onclick=async()=>{const name=button.dataset.product;if(!confirm(`Remover “${name}” da lista de produtos testados?\n\nOs dados das campanhas serão preservados.`))return;await actions.hide(button.dataset.key);renderTestedProducts();toast(`${name} foi removido da lista; o histórico foi preservado`)})}
    $('#downloadCatalog').onclick=actions.download;
    $('#purgeProducts').onclick=actions.purge;
    $('#restoreProducts').onclick=async()=>{await actions.restore();renderTestedProducts();toast('Produtos removidos foram restaurados')};
    return Object.freeze({render:renderTestedProducts});
  }
  window.TestedProductsView=Object.freeze({mount});
})();
